# Traveling Salesman Problem (TSP)
## Comparing Heuristic and Exact Optimization Methods

### Techniques Used
- Google OR-Tools (PATH_CHEAPEST_ARC + Guided Local Search)
- Gurobi MILP (MTZ Formulation)
- Warm Start using OR-Tools
- K-Nearest Neighbour Sparsification

### Dataset
- 1000 Indian Cities
- Road Network Distance Matrix (OSRM)

### Objective
Compare heuristic and exact optimization approaches on increasing TSP instances and study scalability, warm-starting, and sparsification.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import folium
import time

import gurobipy as gp
from gurobipy import GRB

from ortools.constraint_solver import pywrapcp
from ortools.constraint_solver import routing_enums_pb2

### OR-Tools Solver

This function constructs and solves the TSP using Google OR-Tools.

Configuration:
- PATH_CHEAPEST_ARC
- GUIDED_LOCAL_SEARCH
- Time Limit = 30 seconds

In [10]:
def solve_tsp_ortools(distance_matrix, N):

    city_names = distance_matrix.index[:N]

    D = distance_matrix.loc[
        city_names,
        city_names
    ].values

    D = (D * 1000).astype(int)

    manager = pywrapcp.RoutingIndexManager(
        N,
        1,
        0
    )

    routing = pywrapcp.RoutingModel(manager)

    def distance_callback(from_index, to_index):

        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)

        return int(
            D[from_node][to_node]
        )

    transit_callback_index = routing.RegisterTransitCallback(
        distance_callback
    )

    routing.SetArcCostEvaluatorOfAllVehicles(
        transit_callback_index
    )

    search_parameters = (
        pywrapcp.DefaultRoutingSearchParameters()
    )

    search_parameters.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    )

    search_parameters.local_search_metaheuristic = (
        routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    )

    search_parameters.time_limit.seconds = 30

    start = time.time()

    solution = routing.SolveWithParameters(
        search_parameters
    )

    runtime = time.time() - start

    if solution:

        route = []

        index = routing.Start(0)

        total_distance = 0

        while not routing.IsEnd(index):

            node = manager.IndexToNode(index)

            route.append(node)

            next_index = solution.Value(
                routing.NextVar(index)
            )

            total_distance += routing.GetArcCostForVehicle(
                index,
                next_index,
                0
            )

            index = next_index

        route.append(0)

        return {
            "N": N,
            "Distance_km": total_distance / 1000,
            "Runtime_sec": runtime,
            "Route": route,
            "Status": "Solved"
        }

    return {
        "N": N,
        "Distance_km": None,
        "Runtime_sec": runtime,
        "Route": None,
        "Status": "No Solution"
    }

# Load Dataset

In [11]:
distance_matrix = pd.read_csv(r"C:\Users\DELL\Documents\TSP-Optimization-using-Gurobi-and-OR-Tools\data\distance_matrix.csv",
    
)
distance_matrix = distance_matrix.pivot(
    index="fromplace",
    columns="toplace",
    values="dist_km"
)

In [12]:

res_10 = solve_tsp_ortools(
    distance_matrix,
    10
)

print(res_10)

{'N': 10, 'Distance_km': 8370.0, 'Runtime_sec': 30.025543689727783, 'Route': [0, 6, 5, 2, 3, 4, 7, 9, 8, 1, 0], 'Status': 'Solved'}

In [13]:
instances = [10,50,100,250,500,1000]

results_task1 = []

for N in instances:

    print(f"\nRunning N={N}")

    res = solve_tsp_ortools(
        distance_matrix,
        N
    )

    print(
        f"Distance={res['Distance_km']:.2f} km"
    )

    print(
        f"Runtime={res['Runtime_sec']:.2f} sec"
    )

    results_task1.append(res)

Running N=10
Distance=8370.00 km
Runtime=30.00 sec

Running N=50
Distance=14408.00 km
Runtime=30.00 sec

Running N=100
Distance=19128.00 km
Runtime=30.00 sec

Running N=250
Distance=26883.00 km
Runtime=30.00 sec

Running N=500
Distance=37015.00 km
Runtime=30.00 sec

Running N=1000
Distance=52546.00 km
Runtime=30.02 sec

## Task 1: OR-Tools Heuristic Results

Google OR-Tools was used to generate high-quality feasible tours within a fixed time limit of 30 seconds for each instance.

The heuristic consistently produced good-quality solutions with very low computational time, making it suitable for generating initial solutions for larger optimization models.

In [14]:
task1_df = pd.DataFrame(results_task1)

task1_df

,N,Distance_km,Runtime_sec,Route,Status
0,10,8370.0,30.000092,"[0, 6, 5, 2, 3, 4, 7, 9, 8, 1, 0]",Solved
1,50,14408.0,30.001317,"[0, 19, 11, 1, 40, 30, 8, 36, 41, 9, 25, 7, 20...",Solved
2,100,19128.0,30.000231,"[0, 66, 19, 11, 77, 1, 40, 30, 8, 36, 41, 97, ...",Solved
3,250,26883.0,30.000679,"[0, 230, 113, 104, 31, 112, 38, 89, 192, 23, 2...",Solved
4,500,37015.0,30.000493,"[0, 288, 290, 283, 113, 230, 414, 199, 387, 23...",Solved
5,1000,52546.0,30.019090,"[0, 565, 612, 507, 509, 283, 290, 600, 382, 53...",Solved

In [15]:
task1_df.to_csv(
    "Task1_ORTools.csv",
    index=False
)

# Warm Start using OR-Tools Solution

A warm start provides the optimization solver with an initial feasible solution before the branch-and-bound process begins.

Instead of starting from scratch, the high-quality tour generated by Google OR-Tools is supplied as a **MIP Start** to Gurobi.

### Purpose
- Improve the quality of the initial incumbent solution.
- Reduce the optimality gap within the same time limit.
- Accelerate convergence for larger TSP instances.

The OR-Tools route is converted into binary decision variables (`xᵢⱼ`) and supplied to Gurobi through the `Start` attribute. This allows the solver to focus on improving an already feasible solution rather than searching for one from scratch.

The performance of the warm-start model is compared with the cold-start MILP model using runtime, objective value, and MIP gap.

In [13]:
def solve_tsp_gurobi_warm(
    distance_matrix,
    N,
    route
):

    import gurobipy as gp
    from gurobipy import GRB
    import time

    city_names = distance_matrix.index[:N]

    D = distance_matrix.loc[
        city_names,
        city_names
    ].values

    model = gp.Model(
        f"TSP_WARM_{N}"
    )

    model.setParam(
        "TimeLimit",
        1800
    )

    # -------------------------
    # Variables
    # -------------------------

    x = {}

    for i in range(N):
        for j in range(N):

            if i != j:

                x[i,j] = model.addVar(
                    vtype=GRB.BINARY,
                    name=f"x_{i}_{j}"
                )

    u = {}

    for i in range(1,N):

        u[i] = model.addVar(
            lb=1,
            ub=N-1,
            vtype=GRB.CONTINUOUS,
            name=f"u_{i}"
        )

    model.update()

    # -------------------------
    # Warm Start
    # -------------------------

    for i,j in x.keys():

        x[i,j].Start = 0

    for k in range(len(route)-1):

        i = route[k]
        j = route[k+1]

        if (i,j) in x:

            x[i,j].Start = 1

    for pos, city in enumerate(
        route[1:-1],
        start=1
    ):

        if city in u:

            u[city].Start = pos

    # -------------------------
    # Objective
    # -------------------------

    model.setObjective(

        gp.quicksum(
            D[i,j] * x[i,j]
            for i in range(N)
            for j in range(N)
            if i != j
        ),

        GRB.MINIMIZE

    )

    # -------------------------
    # Outgoing
    # -------------------------

    for i in range(N):

        model.addConstr(

            gp.quicksum(
                x[i,j]
                for j in range(N)
                if i != j
            ) == 1

        )

    # -------------------------
    # Incoming
    # -------------------------

    for j in range(N):

        model.addConstr(

            gp.quicksum(
                x[i,j]
                for i in range(N)
                if i != j
            ) == 1

        )

    # -------------------------
    # MTZ
    # -------------------------

    for i in range(1,N):
        for j in range(1,N):

            if i != j:

                model.addConstr(

                    u[i]
                    - u[j]
                    + N*x[i,j]
                    <= N-1

                )

    # -------------------------
    # Solve
    # -------------------------

    
    print("Starting optimization...")
    start = time.time()

    

    end = time.time()

    print("Solver runtime:", end-start)
    print("Gurobi runtime:", model.Runtime)

    model.optimize()

    runtime = model.Runtime

    result = {

        "N": N,
        "ObjVal": None,
        "ObjBound": None,
        "Gap": None,
        "Runtime_sec": runtime,
        "Status": model.Status

    }

    if model.SolCount > 0:

        result["ObjVal"] = model.ObjVal
        result["ObjBound"] = model.ObjBound
        result["Gap"] = model.MIPGap * 100

    return result

In [14]:
route_10 = results_task1[0]["Route"]

warm_10 = solve_tsp_gurobi_warm(
    distance_matrix,
    10,
    route_10
)

print(warm_10)

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2835067
Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Set parameter TimeLimit to value 1800
Starting optimization...
Solver runtime: 2.384185791015625e-07
Gurobi runtime: 0.0
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 92 rows, 99 columns and 396 nonzeros (Min)
Model fingerprint: 0x5f49b726
Model has 90 linear objective coefficients
Variable types: 9 continuous, 90 integer (90 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [2e+02, 3e+03]
  Bounds range     [1e+00, 9e+00]
  RHS range        [1e+00, 9e+00]

Loaded user MIP start with objective 8370

Presolve time: 0.01s
Presolved: 92 rows, 99 columns, 795 nonzeros
Variable types: 9 continuous, 90 integer (90 binary)

Root relaxation: objective 7.948162e+03, 26 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 7948.16176    0   17 8370.00000 7948.16176  5.04%     -    0s
     0     0 infeasible    0      8370.00000 8370.00000  0.00%     -    0s

Cutting planes:
  Learned: 1
  Implied bound: 7
  Clique: 5
  MIR: 2
  Relax-and-lift: 1

Explored 1 nodes (30 simplex iterations) in 0.04 seconds (0.00 work units)
Thread count was 8 (of 8 available processors)

Solution count 1: 8370

Optimal solution found (tolerance 1.00e-04)
Best objective 8.370000000000e+03, best bound 8.370000000000e+03, gap 0.0000%
{'N': 10, 'ObjVal': 8370.0, 'ObjBound': 8370.0, 'Gap': 0.0, 'Runtime_sec': 0.05500006675720215, 'Status': 2}

# Exact Solution using Gurobi (MILP)

In this section, we formulate the Traveling Salesman Problem (TSP) as a Mixed Integer Linear Programming (MILP) model using the Miller-Tucker-Zemlin (MTZ) formulation.

### Model Components
- **Decision Variables (`xᵢⱼ`)**: Binary variables indicating whether the route travels directly from city *i* to city *j*.
- **MTZ Variables (`uᵢ`)**: Continuous variables used to eliminate subtours.
- **Objective**: Minimize the total travel distance.
- **Constraints**:
  - Each city has exactly one outgoing edge.
  - Each city has exactly one incoming edge.
  - MTZ constraints prevent the formation of subtours.

The model is solved using the Gurobi Optimizer with a fixed time limit. For larger problem instances, the solver may terminate before proving optimality, in which case the best feasible solution and optimality gap are reported.

In [16]:
def solve_tsp_gurobi(
    distance_matrix,
    N
):

    city_names = distance_matrix.index[:N]

    D = distance_matrix.loc[
        city_names,
        city_names
    ].values

    model = gp.Model(
        f"TSP_{N}"
    )

    model.setParam(
        "TimeLimit",
        1800
    )

    x = {}

    for i in range(N):
        for j in range(N):

            if i != j:

                x[i,j] = model.addVar(
                    vtype=GRB.BINARY
                )

    u = {}

    for i in range(1,N):

        u[i] = model.addVar(
            lb=1,
            ub=N-1,
            vtype=GRB.CONTINUOUS
        )

    model.update()

    model.setObjective(

        gp.quicksum(
            D[i,j] * x[i,j]
            for i in range(N)
            for j in range(N)
            if i != j
        ),

        GRB.MINIMIZE

    )

    for i in range(N):

        model.addConstr(

            gp.quicksum(
                x[i,j]
                for j in range(N)
                if i != j
            ) == 1

        )

    for j in range(N):

        model.addConstr(

            gp.quicksum(
                x[i,j]
                for i in range(N)
                if i != j
            ) == 1

        )

    for i in range(1,N):
        for j in range(1,N):

            if i != j:

                model.addConstr(

                    u[i]
                    - u[j]
                    + N*x[i,j]
                    <= N-1

                )

    start = time.time()

    model.optimize()

    runtime = runtime = model.Runtime

    result = {

        "N": N,
        "Runtime_sec": runtime,
        "Status": model.Status

    }

    if model.SolCount > 0:

     result["ObjVal"] = model.ObjVal
     result["ObjBound"] = model.ObjBound
     result["Gap"] = model.MIPGap * 100

    return result

In [17]:
route_10 = results_task1[0]["Route"]

cold_10 = solve_tsp_gurobi(
    distance_matrix,
    10
)

warm_10 = solve_tsp_gurobi_warm(
    distance_matrix,
    10,
    route_10
)

print(cold_10)
print(warm_10)

Set parameter TimeLimit to value 1800
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 92 rows, 99 columns and 396 nonzeros (Min)
Model fingerprint: 0x95a47b37
Model has 90 linear objective coefficients
Variable types: 9 continuous, 90 integer (90 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [2e+02, 3e+03]
  Bounds range     [1e+00, 9e+00]
  RHS range        [1e+00, 9e+00]

Found heuristic solution: objective 12872.000000
Presolve time: 0.00s
Presolved: 92 rows, 99 columns, 795 nonzeros
Variable types: 9 continuous, 90 integer (90 binary)

Root relaxation: objective 7.948162e+03, 26 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 7948.16176    0   17 12872.0000 7948.16176  38.3%     -    0s
H    0     0                    12563.000000 7948.16176  36.7%     -    0s
H    0     0                    9233.0000000 7948.16176  13.9%     -    0s
H    0     0                    8372.0000000 7948.16176  5.06%     -    0s
H    0     0                    8370.0000000 8034.59000  4.01%     -    0s

Cutting planes:
  Learned: 1
  Implied bound: 7
  Clique: 3
  MIR: 3
  Relax-and-lift: 2

Explored 1 nodes (26 simplex iterations) in 0.08 seconds (0.00 work units)
Thread count was 8 (of 8 available processors)

Solution count 5: 8370 8372 9233 ... 12872

Optimal solution found (tolerance 1.00e-04)
Best objective 8.370000000000e+03, best bound 8.370000000000e+03, gap 0.0000%
Set parameter TimeLimit to value 1800
Starting optimization...
Solver runtime: 2.384185791015625e-07
Gurobi runtime: 0.0
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 92 rows, 99 columns and 396 nonzeros (Min)
Model fingerprint: 0x5f49b726
Model has 90 linear objective coefficients
Variable types: 9 continuous, 90 integer (90 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [2e+02, 3e+03]
  Bounds range     [1e+00, 9e+00]
  RHS range        [1e+00, 9e+00]

Loaded user MIP start with objective 8370

Presolve time: 0.00s
Presolved: 92 rows, 99 columns, 795 nonzeros
Variable types: 9 continuous, 90 integer (90 binary)

Root relaxation: objective 7.948162e+03, 26 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 7948.16176    0   17 8370.00000 7948.16176  5.04%     -    0s
     0     0 infeasible    0      8370.00000 8370.00000  0.00%     -    0s

Cutting planes:
  Learned: 1
  Implied bound: 7
  Clique: 5
  MIR: 2
  Relax-and-lift: 1

Explored 1 nodes (30 simplex iterations) in 0.07 seconds (0.00 work units)
Thread count was 8 (of 8 available processors)

Solution count 1: 8370

Optimal solution found (tolerance 1.00e-04)
Best objective 8.370000000000e+03, best bound 8.370000000000e+03, gap 0.0000%
{'N': 10, 'Runtime_sec': 0.0840001106262207, 'Status': 2, 'ObjVal': 8370.0, 'ObjBound': 8370.0, 'Gap': 0.0}
{'N': 10, 'ObjVal': 8370.0, 'ObjBound': 8370.0, 'Gap': 0.0, 'Runtime_sec': 0.09200000762939453, 'Status': 2}

In [18]:
comparison_10 = pd.DataFrame(
    [
        {
            "Mode":"Cold",
            **cold_10
        },
        {
            "Mode":"Warm",
            **warm_10
        }
    ]
)

comparison_10

   Mode   N  Runtime_sec  Status  ObjVal  ObjBound  Gap
0  Cold  10        0.084       2  8370.0    8370.0  0.0
1  Warm  10        0.092       2  8370.0    8370.0  0.0

In [19]:
route_50 = results_task1[1]["Route"]

warm_50 = solve_tsp_gurobi_warm(
    distance_matrix,
    50,
    route_50
)

print(warm_50)

Set parameter TimeLimit to value 1800
Starting optimization...
Solver runtime: 2.384185791015625e-07
Gurobi runtime: 0.0
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 2452 rows, 2499 columns and 11956 nonzeros (Min)
Model fingerprint: 0x8cb0af69
Model has 2450 linear objective coefficients
Variable types: 49 continuous, 2450 integer (2450 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+01]
  Objective range  [8e+00, 4e+03]
  Bounds range     [1e+00, 5e+01]
  RHS range        [1e+00, 5e+01]

Loaded user MIP start with objective 14408

Presolve time: 0.02s
Presolved: 2452 rows, 2499 columns, 11956 nonzeros
Variable types: 49 continuous, 2450 integer (2450 binary)

Root relaxation: objective 9.059898e+03, 193 iterations, 0.01 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 9059.89796    0   84 14408.0000 9059.89796  37.1%     -    0s
     0     0 12148.0714    0   95 14408.0000 12148.0714  15.7%     -    0s
     0     0 12214.0408    0   88 14408.0000 12214.0408  15.2%     -    0s
     0     0 12214.0408    0   88 14408.0000 12214.0408  15.2%     -    0s
     0     0 12334.5018    0  103 14408.0000 12334.5018  14.4%     -    0s
     0     0 12358.9337    0   95 14408.0000 12358.9337  14.2%     -    0s
     0     0 12358.9337    0   95 14408.0000 12358.9337  14.2%     -    0s
     0     0 12584.4094    0  101 14408.0000 12584.4094  12.7%     -    0s
     0     0 12584.4753    0  103 14408.0000 12584.4753  12.7%     -    0s
     0     0 12593.9094    0  102 14408.0000 12593.9094  12.6%     -    0s
     0     0 12593.9693    0   91 14408.0000 12593.9693  12.6%     -    0s
     0     0 12593.9693    0   91 14408.0000 12593.9693  12.6%     -    0s
     0     0 12593.9693    0   89 14408.0000 12593.9693  12.6%     -    0s
     0     0 12594.2193    0   89 14408.0000 12594.2193  12.6%     -    0s
     0     0 12594.2193    0   93 14408.0000 12594.2193  12.6%     -    0s
     0     0 12603.5101    0   93 14408.0000 12603.5101  12.5%     -    0s
     0     0 12603.5101    0   93 14408.0000 12603.5101  12.5%     -    0s
     0     0 12603.5101    0   81 14408.0000 12603.5101  12.5%     -    0s
     0     0 12618.0101    0   84 14408.0000 12618.0101  12.4%     -    0s
     0     0 12618.0101    0   82 14408.0000 12618.0101  12.4%     -    1s
     0     0 12618.0101    0   88 14408.0000 12618.0101  12.4%     -    1s
     0     0 12618.0101    0  102 14408.0000 12618.0101  12.4%     -    1s
     0     0 12618.0101    0   91 14408.0000 12618.0101  12.4%     -    1s
     0     0 12683.6795    0   76 14408.0000 12683.6795  12.0%     -    1s
     0     0 12684.6824    0   71 14408.0000 12684.6824  12.0%     -    1s
     0     0 12719.3789    0   80 14408.0000 12719.3789  11.7%     -    1s
     0     0 12724.0631    0   78 14408.0000 12724.0631  11.7%     -    1s
     0     0 12724.0631    0   78 14408.0000 12724.0631  11.7%     -    1s
     0     0 12726.0710    0   80 14408.0000 12726.0710  11.7%     -    1s
     0     0 12728.5710    0   80 14408.0000 12728.5710  11.7%     -    1s
     0     0 12728.5710    0   80 14408.0000 12728.5710  11.7%     -    1s
     0     0 12728.5710    0   80 14408.0000 12728.5710  11.7%     -    1s
     0     2 12740.3418    0   80 14408.0000 12740.3418  11.6%     -    1s
  1310   949 12936.7445    9   87 14408.0000 12873.1288  10.7%   7.0    5s
  1339   968 14083.1969   31   96 14408.0000 13088.1289  9.16%   6.8   10s
  3142  1351 13611.5134   34   64 14408.0000 13327.8740  7.50%  11.8   15s
  7990  3114 14044.3241   39   66 14408.0000 13607.3664  5.56%  13.5   20s
 11384  4531 14144.1617   36   70 14408.0000 13665.7133  5.15%  14.1   25s
 15876  6234 14223.3638   49   16 14408.0000 13713.9801  4.82%  14.9   30s
 20023  7765 13939.0917   32   88 14408.0000 13764.1077  4.47%  15.5   35s
 26117  9524 13904.8029   34   82 14408.0000 13827.7629  4.03%  16.1   40s
 30288 10702 infeasible   35      14408.0000 13880.7083  3.66%  16.5   51s
 34783 11739     cutoff   35      14408.0000 13932.5000  3.30%  16.7   55s
 40767 13412 infeasible   41      14408.0000 13995.1870  2.87%  17.0   60s
 47127 15977 14287.8432   35   79 14408.0000 14038.0361  2.57%  17.0   65s
 55596 19509 14078.0225   42   64 14408.0000 14069.0647  2.35%  16.5   70s
 60325 21777 14359.9375   49    6 14408.0000 14078.9453  2.28%  16.1   75s
 68490 25408 14186.2274   55   19 14408.0000 14089.9650  2.21%  15.4   80s
 77479 29740 14355.1667   50   19 14408.0000 14096.9259  2.16%  14.9   85s
 83941 32535     cutoff   51      14408.0000 14102.0685  2.12%  14.5   90s
 92203 36230 14181.9435   47   33 14408.0000 14107.2640  2.09%  14.1   95s
 101829 39952 14151.3432   42   34 14408.0000 14112.2810  2.05%  13.7  100s
 106152 41639 14142.2178   51   38 14408.0000 14114.5384  2.04%  13.6  105s
 114254 44702 14343.9396   46   23 14408.0000 14118.4286  2.01%  13.3  110s
 121710 47457 14228.5628   53   19 14408.0000 14122.2166  1.98%  13.1  115s
 130704 51026 14400.7483   55   14 14408.0000 14125.9480  1.96%  12.9  120s
 137530 53319 infeasible   48      14408.0000 14128.5837  1.94%  12.7  125s
 144385 55730 14218.8312   47   33 14408.0000 14130.7778  1.92%  12.5  130s
 151970 58514 14373.2207   55   26 14408.0000 14133.0985  1.91%  12.3  135s
 158187 60698 14195.9791   53   20 14408.0000 14134.9452  1.90%  12.2  140s
 165978 63503 14174.7183   40   55 14408.0000 14137.2660  1.88%  12.0  145s
 174289 66537 14212.1533   43   53 14408.0000 14139.5725  1.86%  11.9  150s
 182810 69675 14169.0266   51   24 14408.0000 14141.6347  1.85%  11.7  155s
 184851 70329 14176.2371   51   22 14408.0000 14141.7733  1.85%  11.7  160s
 192839 73078     cutoff   52      14408.0000 14144.1042  1.83%  11.5  165s
 201288 75835 14216.5802   49   48 14408.0000 14146.1250  1.82%  11.4  170s
 209452 78680 14156.4370   45   60 14408.0000 14147.7998  1.81%  11.3  175s
 217499 81317 14257.3411   67   24 14408.0000 14149.5111  1.79%  11.2  180s
 223604 83340 14178.3307   37   26 14408.0000 14150.7782  1.79%  11.1  185s
 230988 85688 14374.9424   58    8 14408.0000 14152.2177  1.78%  11.1  190s
 238894 88239 14311.6464   54   20 14408.0000 14153.6685  1.77%  11.0  195s
 246327 90460 14236.1535   41   27 14408.0000 14155.2195  1.75%  10.9  200s
 250888 91816 14216.9844   42   40 14408.0000 14155.6790  1.75%  10.9  205s
 256803 93831 14182.7059   41   36 14408.0000 14156.9641  1.74%  10.8  211s
 261373 95250 14166.7612   56   17 14408.0000 14157.6944  1.74%  10.7  215s
 266644 96852 14208.8591   49   16 14408.0000 14158.4902  1.73%  10.7  220s
 272339 98621 14262.5031   51   23 14408.0000 14159.3194  1.73%  10.6  225s
 278806 100615 14251.0922   47   58 14408.0000 14160.3239  1.72%  10.6  230s
 285394 102733 14326.1283   47   25 14408.0000 14161.2120  1.71%  10.5  235s
 293682 105103 14284.2829   45   19 14408.0000 14162.5023  1.70%  10.5  240s
 299980 107055 14197.7665   49   57 14408.0000 14163.4273  1.70%  10.4  245s
 307156 109068     cutoff   54      14408.0000 14164.3540  1.69%  10.4  250s
 313589 110966 14376.1029   62   19 14408.0000 14165.2057  1.69%  10.3  255s
 320688 113379 14189.6884   54   68 14408.0000 14166.0408  1.68%  10.3  260s
 327091 115135     cutoff   60      14408.0000 14166.8928  1.67%  10.3  265s
 334096 117194 14186.0679   50   20 14408.0000 14167.7201  1.67%  10.2  270s
 339270 118524 14199.6692   51   24 14408.0000 14168.4141  1.66%  10.2  275s
 345394 120063 14201.9229   45   25 14408.0000 14169.0828  1.66%  10.2  280s
 351939 122195 14207.2408   59   80 14408.0000 14169.8528  1.65%  10.2  285s
 358833 124144 14284.7219   53   24 14408.0000 14170.7045  1.65%  10.1  290s
 364765 126126 14382.7917   59   27 14408.0000 14171.4515  1.64%  10.1  295s
 370950 127949 14197.1632   41   39 14408.0000 14172.1508  1.64%  10.1  300s
 377102 129758 14224.2734   46   21 14408.0000 14172.8340  1.63%  10.1  305s
 384316 131680 14364.5208   71   15 14408.0000 14173.6554  1.63%  10.0  310s
 389601 133163 infeasible   67      14408.0000 14174.2153  1.62%  10.0  315s
 392341 133880 14260.4730   41   20 14408.0000 14174.5751  1.62%  10.0  320s
 397213 135244 infeasible   49      14408.0000 14175.1244  1.62%  10.0  325s
 402897 136710 14222.1159   54   13 14408.0000 14175.7005  1.61%  10.0  330s
 409649 138404 14374.7361   57   12 14408.0000 14176.4178  1.61%  10.0  335s
 415889 139961 14233.2514   47   18 14408.0000 14176.9492  1.60%  10.0  340s
 422060 141534     cutoff   52      14408.0000 14177.6111  1.60%  10.0  345s
 425494 142534 14297.8819   59   33 14408.0000 14177.8775  1.60%   9.9  350s
 431270 144063 14186.1671   53   18 14408.0000 14178.4448  1.59%   9.9  355s
 437341 145569 14229.1542   55   18 14408.0000 14179.0000  1.59%   9.9  360s
 443789 147304 14208.4208   38   57 14408.0000 14179.6944  1.58%   9.9  365s
 449798 148853 14302.4861   47   34 14408.0000 14180.2600  1.58%   9.9  370s
 455893 150468     cutoff   54      14408.0000 14180.8333  1.58%   9.9  375s
 462043 152077 infeasible   45      14408.0000 14181.4950  1.57%   9.9  380s
 468388 153724 14213.7986   49   24 14408.0000 14182.0657  1.57%   9.9  385s
 474613 155263 14308.8088   49   31 14408.0000 14182.6685  1.56%   9.9  390s
 480856 156795 14208.3063   57   17 14408.0000 14183.2744  1.56%   9.9  395s
 487019 158307 14205.7475   43   34 14408.0000 14183.8542  1.56%   9.9  400s
 492293 159516 14239.0239   52   23 14408.0000 14184.3550  1.55%   9.8  405s
 497575 160718 14286.1739   46   54 14408.0000 14184.8603  1.55%   9.8  410s
 502892 161920 infeasible   55      14408.0000 14185.3117  1.55%   9.8  415s
 508252 163229 14277.6875   75    6 14408.0000 14185.8090  1.54%   9.8  420s
 513537 164459 14297.7040   71   14 14408.0000 14186.2983  1.54%   9.8  425s
 519102 165593 14336.2905   50   24 14408.0000 14186.7493  1.54%   9.8  430s
 524468 166947     cutoff   43      14408.0000 14187.2083  1.53%   9.8  435s
 530606 168728 14201.5190   41   31 14408.0000 14187.6880  1.53%   9.8  440s
 535806 170017 14335.1423   48   27 14408.0000 14188.2015  1.53%   9.8  445s
 540979 171279 14331.5866   40   24 14408.0000 14188.6505  1.52%   9.8  450s
 546600 172634 14230.0315   44   27 14408.0000 14189.1213  1.52%   9.8  455s
 551801 173682 14234.4271   52   20 14408.0000 14189.6052  1.52%   9.8  460s
 556845 174880 infeasible   62      14408.0000 14189.9861  1.51%   9.8  465s
 562461 176044 14350.6080   44   19 14408.0000 14190.3318  1.51%   9.8  470s
 566878 176991 14205.6718   44   32 14408.0000 14190.7153  1.51%   9.8  475s
 571253 178062     cutoff   45      14408.0000 14191.0201  1.51%   9.8  480s
 577591 179473 14229.8816   46   29 14408.0000 14191.6091  1.50%   9.8  485s
 582351 180477 14319.1271   80   19 14408.0000 14192.0365  1.50%   9.8  490s
 587938 181757 14366.5647   47   19 14408.0000 14192.4883  1.50%   9.8  495s
 594356 183313 14307.6829   57   23 14408.0000 14192.9511  1.49%   9.8  500s
 599838 184603 infeasible   82      14408.0000 14193.3653  1.49%   9.7  505s
 606202 186019     cutoff   49      14408.0000 14193.8461  1.49%   9.7  510s
 611414 187212 14256.1096   57   33 14408.0000 14194.3239  1.48%   9.7  515s
 618048 188661 14253.7049   56   15 14408.0000 14194.7948  1.48%   9.7  520s
 623392 189854     cutoff   64      14408.0000 14195.2150  1.48%   9.7  525s
 629776 191190 14229.2860   41   35 14408.0000 14195.6916  1.47%   9.7  530s
 635138 192209 14225.0072   47   29 14408.0000 14196.1097  1.47%   9.7  535s
 641214 193508 14338.0611   51   38 14408.0000 14196.6003  1.47%   9.7  540s
 646472 194516 infeasible   50      14408.0000 14196.9585  1.46%   9.7  545s
 652614 195810 14214.4460   42   41 14408.0000 14197.4445  1.46%   9.7  550s
 658109 196956 14273.0000   53   21 14408.0000 14197.8125  1.46%   9.6  555s
 663381 198267 14335.5215   55   22 14408.0000 14198.2266  1.46%   9.6  560s
 669808 199696 14210.4516   53   30 14408.0000 14198.6870  1.45%   9.6  565s
 675157 201027     cutoff   61      14408.0000 14199.0880  1.45%   9.6  570s
 680694 202272 14208.8333   42   18 14408.0000 14199.5117  1.45%   9.6  575s
 686165 203628 14247.2563   48   31 14408.0000 14199.9157  1.44%   9.6  580s
 692414 204935     cutoff   48      14408.0000 14200.3608  1.44%   9.6  585s
 697911 206001 14240.5510   57   18 14408.0000 14200.7772  1.44%   9.6  590s
 703309 207065     cutoff   45      14408.0000 14201.2153  1.44%   9.6  595s
 708831 208233 14388.7500   55    6 14408.0000 14201.6111  1.43%   9.6  600s
 714452 209283 14258.6704   40   70 14408.0000 14201.9893  1.43%   9.6  605s
 720543 210422 14281.4856   59   36 14408.0000 14202.5000  1.43%   9.6  610s
 725939 211632     cutoff   54      14408.0000 14202.8333  1.42%   9.5  615s
 731266 212671 14257.0084   53   25 14408.0000 14203.2593  1.42%   9.5  620s
 732111 212690     cutoff   57      14408.0000 14203.3333  1.42%   9.5  625s
 733974 213365 14367.1680   59   58 14408.0000 14203.4689  1.42%   9.5  631s
 737307 213891 14258.4917   45   63 14408.0000 14203.6459  1.42%   9.5  635s
 741966 214600 14396.3893   52   21 14408.0000 14203.9777  1.42%   9.5  640s
 747959 215599 14315.2537   78   11 14408.0000 14204.4233  1.41%   9.5  645s
 753266 216649 14357.6250   54    9 14408.0000 14204.7788  1.41%   9.5  650s
 758744 217814 14308.0675   54   27 14408.0000 14205.1262  1.41%   9.5  655s
 762404 218355 14334.3163   48   50 14408.0000 14205.3702  1.41%   9.5  660s
 767054 219362 14339.3243   68   12 14408.0000 14205.6554  1.40%   9.5  665s
 772320 220529 14391.9856   47   25 14408.0000 14205.9996  1.40%   9.5  670s
 776863 221409 14267.4573   53   36 14408.0000 14206.2500  1.40%   9.5  675s
 782222 222417 14245.7654   43   17 14408.0000 14206.6554  1.40%   9.5  680s
 785858 223224 14328.6250   82    6 14408.0000 14206.8819  1.40%   9.5  685s
 789582 223848 14239.9001   46   12 14408.0000 14207.1583  1.39%   9.5  690s
 793234 224545 infeasible   55      14408.0000 14207.4383  1.39%   9.5  695s
 796665 225277 14404.9131   41   57 14408.0000 14207.6517  1.39%   9.5  701s
 799487 225883     cutoff   46      14408.0000 14207.7846  1.39%   9.4  705s
 803152 226547     cutoff   60      14408.0000 14208.0037  1.39%   9.4  712s
 805082 226865     cutoff   47      14408.0000 14208.1042  1.39%   9.4  716s
 806762 227275 14395.9308   57   50 14408.0000 14208.2321  1.39%   9.4  720s
 809498 227725 14276.7433   52   21 14408.0000 14208.4028  1.39%   9.4  725s
 814063 228633 14241.2803   55   35 14408.0000 14208.6829  1.38%   9.4  730s
 818604 229489 14312.0306   54   32 14408.0000 14208.9633  1.38%   9.4  735s
 823016 230384 14224.4423   48   34 14408.0000 14209.2708  1.38%   9.4  740s
 827549 231183     cutoff   45      14408.0000 14209.5699  1.38%   9.4  745s
 832160 232031 14249.3782   45   24 14408.0000 14209.8216  1.38%   9.4  750s
 836830 232892 14228.5491   43   31 14408.0000 14210.1304  1.37%   9.4  755s
 841285 233763 14374.2535   45   12 14408.0000 14210.4091  1.37%   9.4  760s
 845715 234658 14371.9375   67    6 14408.0000 14210.6699  1.37%   9.4  765s
 851120 235716 14348.7778   76   28 14408.0000 14211.0139  1.37%   9.4  770s
 855785 236680 infeasible   53      14408.0000 14211.2986  1.37%   9.4  775s
 860187 237476 14389.5448   44   43 14408.0000 14211.5717  1.36%   9.4  780s
 865606 238499 14268.3056   50   31 14408.0000 14211.8949  1.36%   9.4  785s
 869998 239312 14251.0822   53   42 14408.0000 14212.1545  1.36%   9.4  790s
 874551 240167 14255.4528   60   25 14408.0000 14212.4121  1.36%   9.4  795s
 879126 240942 14383.0162   47   12 14408.0000 14212.6944  1.36%   9.4  800s
 884484 241896     cutoff   56      14408.0000 14213.0444  1.35%   9.3  805s
 889007 242738 14389.4854   43   26 14408.0000 14213.3333  1.35%   9.3  810s
 894311 243714 14285.7750   58   27 14408.0000 14213.6667  1.35%   9.3  815s
 898818 244479 14339.1392   54   17 14408.0000 14213.8798  1.35%   9.3  820s
 903286 245209     cutoff   57      14408.0000 14214.1516  1.35%   9.3  825s
 908667 246257 14355.7468   38   19 14408.0000 14214.4964  1.34%   9.3  830s
 913150 247090     cutoff   50      14408.0000 14214.7081  1.34%   9.3  835s
 917592 247887 14350.5328   56   31 14408.0000 14215.0000  1.34%   9.3  840s
 923227 249003 14331.6004   58   16 14408.0000 14215.3057  1.34%   9.3  845s
 928647 250005 14369.0804   55   14 14408.0000 14215.6190  1.34%   9.3  850s
 932388 250593 14268.9370   47   23 14408.0000 14215.7958  1.33%   9.3  855s
 937666 251564 14276.2500   38   32 14408.0000 14216.1042  1.33%   9.3  860s
 941209 252235     cutoff   49      14408.0000 14216.3333  1.33%   9.3  865s
 946452 253237 infeasible   45      14408.0000 14216.6389  1.33%   9.3  870s
 950498 253828 infeasible   50      14408.0000 14216.8248  1.33%   9.3  875s
 955123 254735 14242.9642   54   14 14408.0000 14217.0811  1.33%   9.3  880s
 959606 255464 14259.1185   40   33 14408.0000 14217.3238  1.32%   9.3  885s
 964848 256278 14304.2121   58   38 14408.0000 14217.6432  1.32%   9.3  890s
 969394 257065 14279.1179   65   40 14408.0000 14217.8548  1.32%   9.3  895s
 973911 257901 14358.9687   48   14 14408.0000 14218.1042  1.32%   9.2  900s
 977830 258404 14382.1208   52   10 14408.0000 14218.3190  1.32%   9.2  905s
 980203 258939 infeasible   57      14408.0000 14218.4235  1.32%   9.2  910s
 985727 259851 14260.9054   37   40 14408.0000 14218.7500  1.31%   9.2  915s
 990980 260647 14362.7487   43   49 14408.0000 14219.0689  1.31%   9.2  920s
 997320 261750 14242.1008   50   42 14408.0000 14219.4583  1.31%   9.2  925s
 1001873 262680 14257.8844   48   12 14408.0000 14219.6817  1.31%   9.2  930s
 1007390 263631 14345.5000   52   13 14408.0000 14219.9964  1.30%   9.2  935s
 1011882 264285 14355.1277   44   29 14408.0000 14220.2369  1.30%   9.2  940s
 1017378 265188 14222.4473   54   24 14408.0000 14220.5417  1.30%   9.2  945s
 1023088 266277 14375.5912   48   21 14408.0000 14220.8106  1.30%   9.2  950s
 1027599 267043 14391.1581   51   28 14408.0000 14221.0574  1.30%   9.2  955s
 1031764 267769     cutoff   67      14408.0000 14221.2137  1.30%   9.2  960s
 1036832 268629     cutoff   48      14408.0000 14221.5417  1.29%   9.2  965s
 1041485 269473 14235.0483   43   29 14408.0000 14221.7329  1.29%   9.2  970s
 1047959 270392 14297.5366   55   13 14408.0000 14222.1042  1.29%   9.2  976s
 1052484 271154 14319.1307   51   51 14408.0000 14222.3635  1.29%   9.2  980s
 1057076 272004     cutoff   56      14408.0000 14222.6042  1.29%   9.2  985s
 1062271 272893     cutoff   48      14408.0000 14222.8087  1.29%   9.2  990s
 1067511 273881 14318.2522   51   29 14408.0000 14223.1042  1.28%   9.2  995s
 1072006 274733 14347.2831   56   26 14408.0000 14223.3333  1.28%   9.2 1000s
 1076509 275474 14290.6544   53   22 14408.0000 14223.6162  1.28%   9.2 1005s
 1082140 276349 14275.7507   45   30 14408.0000 14223.8902  1.28%   9.2 1010s
 1086580 277199     cutoff   52      14408.0000 14224.1042  1.28%   9.1 1015s
 1091987 278134     cutoff   49      14408.0000 14224.3613  1.27%   9.1 1020s
 1097352 279061 14254.9739   44   31 14408.0000 14224.6554  1.27%   9.1 1025s
 1102002 279891 14229.9770   48   74 14408.0000 14224.8470  1.27%   9.1 1030s
 1107417 280646 14298.4128   43   26 14408.0000 14225.1439  1.27%   9.1 1035s
 1111853 281452 infeasible   44      14408.0000 14225.3785  1.27%   9.1 1040s
 1117351 282420 14306.8981   52   36 14408.0000 14225.6554  1.27%   9.1 1045s
 1121928 283177 14293.8472   63   16 14408.0000 14225.8488  1.26%   9.1 1050s
 1126470 283953     cutoff   46      14408.0000 14226.1101  1.26%   9.1 1055s
 1130876 284703 infeasible   43      14408.0000 14226.3333  1.26%   9.1 1060s

In [20]:
cold_50 = solve_tsp_gurobi(
    distance_matrix,
    50
)

print(cold_50)

Set parameter TimeLimit to value 1800
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 2452 rows, 2499 columns and 11956 nonzeros (Min)
Model fingerprint: 0x7c540698
Model has 2450 linear objective coefficients
Variable types: 49 continuous, 2450 integer (2450 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+01]
  Objective range  [8e+00, 4e+03]
  Bounds range     [1e+00, 5e+01]
  RHS range        [1e+00, 5e+01]

Presolve time: 0.04s
Presolved: 2452 rows, 2499 columns, 11956 nonzeros
Variable types: 49 continuous, 2450 integer (2450 binary)
Found heuristic solution: objective 66555.000000
Found heuristic solution: objective 61764.000000

Root relaxation: objective 9.059898e+03, 193 iterations, 0.01 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 9059.89796    0   84 61764.0000 9059.89796  85.3%     -    0s
H    0     0                    19035.000000 9059.89796  52.4%     -    0s
H    0     0                    17855.000000 9059.89796  49.3%     -    0s
H    0     0                    17326.000000 9059.89796  47.7%     -    0s
H    0     0                    17262.000000 9059.89796  47.5%     -    0s
H    0     0                    16615.000000 9059.89796  45.5%     -    0s
H    0     0                    16452.000000 9059.89796  44.9%     -    0s
H    0     0                    16283.000000 9059.89796  44.4%     -    0s
H    0     0                    16166.000000 9059.89796  44.0%     -    0s
H    0     0                    15805.000000 9059.89796  42.7%     -    0s
H    0     0                    15795.000000 9059.89796  42.6%     -    0s
H    0     0                    15600.000000 9059.89796  41.9%     -    0s
H    0     0                    15496.000000 12148.0714  21.6%     -    0s
     0     0 12148.0714    0   95 15496.0000 12148.0714  21.6%     -    0s
H    0     0                    15405.000000 12150.5714  21.1%     -    0s
H    0     0                    15242.000000 12214.0408  19.9%     -    1s
H    0     0                    15221.000000 12214.0408  19.8%     -    1s
H    0     0                    15206.000000 12214.0408  19.7%     -    1s
     0     0 12214.0408    0   88 15206.0000 12214.0408  19.7%     -    1s
     0     0 12333.4696    0  105 15206.0000 12333.4696  18.9%     -    1s
     0     0 12334.8367    0   97 15206.0000 12334.8367  18.9%     -    1s
     0     0 12368.0516    0   94 15206.0000 12368.0516  18.7%     -    1s
     0     0 12584.1728    0   96 15206.0000 12584.1728  17.2%     -    1s
     0     0 12584.1728    0   96 15206.0000 12584.1728  17.2%     -    1s
     0     0 12584.1728    0   98 15206.0000 12584.1728  17.2%     -    1s
     0     0 12584.6728    0   98 15206.0000 12584.6728  17.2%     -    1s
     0     0 12584.6728    0  102 15206.0000 12584.6728  17.2%     -    1s
     0     0 12593.6728    0  103 15206.0000 12593.6728  17.2%     -    1s
     0     0 12593.6728    0   88 15206.0000 12593.6728  17.2%     -    1s
     0     0 12593.6728    0   90 15206.0000 12593.6728  17.2%     -    1s
H    0     0                    14887.000000 12593.6728  15.4%     -    2s
     0     0 12600.4300    0   96 14887.0000 12600.4300  15.4%     -    2s
     0     0 12616.4300    0   96 14887.0000 12616.4300  15.3%     -    2s
     0     0 12616.4300    0   96 14887.0000 12616.4300  15.3%     -    2s
     0     0 12616.4300    0   90 14887.0000 12616.4300  15.3%     -    2s
     0     2 12646.4300    0   90 14887.0000 12646.4300  15.1%     -    2s
H  489   487                    14840.000000 12668.4186  14.6%   8.5    2s
H  539   499                    14750.000000 12669.6621  14.1%   8.4    2s
H 1149  1016                    14748.000000 12692.1667  13.9%   7.4    3s
H 1151   967                    14686.000000 12692.1667  13.6%   7.4    3s
H 1155   920                    14639.000000 12692.1667  13.3%   7.4    4s
  1160   924 13573.0945   96   88 14639.0000 12751.3152  12.9%   7.4    5s
H 1165   880                    14625.000000 12849.0653  12.1%   7.3    6s
H 1165   836                    14614.000000 12849.0653  12.1%   7.3    7s
H 1165   794                    14611.000000 12849.0653  12.1%   7.3    7s
H 1165   754                    14584.000000 12849.0653  11.9%   7.3    7s
H 1166   717                    14572.000000 12849.0653  11.8%   7.3    7s
  1178   725 13381.4300   83  105 14572.0000 12947.6997  11.1%   7.3   10s
H 2384   974                    14504.000000 13101.1295  9.67%  14.5   13s
  3199  1136 13336.6428   17   72 14504.0000 13217.3191  8.87%  15.5   15s
H 5910  2200                    14425.000000 13395.6667  7.14%  15.5   17s
  9160  3703 14056.4010   29   60 14425.0000 13531.0102  6.20%  15.5   20s
 15176  5901     cutoff   37      14425.0000 13628.7526  5.52%  16.2   25s
 20285  7710 13825.4558   26   69 14425.0000 13673.3868  5.21%  16.6   30s
 24825  9314 14295.2153   35   30 14425.0000 13710.2618  4.95%  17.0   35s
 29770 10820 infeasible   27      14425.0000 13748.3333  4.69%  17.3   44s
 30714 11101 14222.2500   24   62 14425.0000 13756.8868  4.63%  17.4   45s
 36295 13020 13939.2500   24   70 14425.0000 13803.7778  4.31%  18.3   50s
 41944 14827 14213.7083   25   27 14425.0000 13852.6368  3.97%  18.9   55s
 46573 16402 14308.7917   31   29 14425.0000 13896.3903  3.66%  19.4   60s
 52851 18311 14070.2340   34   42 14425.0000 13942.1472  3.35%  19.7   65s
 56876 19374 14159.5231   33   72 14425.0000 13974.0000  3.13%  20.0   70s
 61453 20993 14148.3889   27   27 14425.0000 14003.6773  2.92%  20.1   75s
 65560 22346 14417.1944   50   10 14425.0000 14022.6346  2.79%  20.1   80s
 67552 23379     cutoff   43      14425.0000 14031.5000  2.73%  20.1   85s
 71808 25208 infeasible   28      14425.0000 14050.7092  2.59%  20.0   90s
 74012 30122 14311.4167   36   34 14425.0000 14056.4127  2.56%  19.9  102s
 82900 31007 14134.5717   52   18 14425.0000 14074.1118  2.43%  19.3  105s
 89674 35293 infeasible   28      14425.0000 14081.6500  2.38%  18.8  110s
 96286 38766 14329.7847   50   15 14425.0000 14087.6517  2.34%  18.3  115s
 104110 43807 14384.2380   32   45 14425.0000 14092.3611  2.31%  17.9  121s
 111424 47981 14356.9375   71    6 14425.0000 14095.8359  2.28%  17.4  125s
 118294 52045 14381.7892   55   23 14425.0000 14099.2571  2.26%  17.1  130s
 125480 56340 14220.3156   48   29 14425.0000 14101.6726  2.24%  16.7  135s
 132280 60333 14198.2509   48   12 14425.0000 14104.0417  2.23%  16.4  140s
 139481 64300 14384.3194   48   20 14425.0000 14106.0968  2.21%  16.1  145s
 146968 68806     cutoff   62      14425.0000 14108.3451  2.20%  15.8  150s
 153367 72463 14142.7604   39   14 14425.0000 14110.0691  2.18%  15.6  155s
 160661 76679 14174.6622   47   16 14425.0000 14111.9871  2.17%  15.4  160s
 167156 80169 14144.7014   59   12 14425.0000 14113.6965  2.16%  15.1  165s
 173772 84135     cutoff   69      14425.0000 14115.1947  2.15%  15.0  170s
 180826 88209     cutoff   67      14425.0000 14116.8333  2.14%  14.8  175s
 187192 91611 14273.2500   43   27 14425.0000 14118.2208  2.13%  14.7  180s
 193212 95141 infeasible   57      14425.0000 14119.6984  2.12%  14.6  185s
 198695 97882 14390.3906   57    8 14425.0000 14120.8307  2.11%  14.5  190s
 205416 101525 14293.2500   49   10 14425.0000 14122.0408  2.10%  14.4  195s
 211724 105108 14200.9722   39   64 14425.0000 14123.2542  2.09%  14.2  200s
 217778 108320 14162.7292   47   22 14425.0000 14124.3925  2.08%  14.2  205s
 223002 111182 14410.8576   61   26 14425.0000 14125.3133  2.08%  14.1  210s
 229378 114672 14211.4000   27   36 14425.0000 14126.5769  2.07%  14.0  215s
 235655 117887 14379.3188   53   27 14425.0000 14127.5591  2.06%  13.9  220s
 240884 120861 14274.0224   68   29 14425.0000 14128.4814  2.06%  13.8  225s
 247220 124114 14249.0415   50   28 14425.0000 14129.6111  2.05%  13.7  230s
 251294 126058 14371.2917   36   61 14425.0000 14130.3078  2.04%  13.7  235s
 256998 129343 14277.5688   41   30 14425.0000 14131.2158  2.04%  13.6  240s
 263103 132799 14317.1905   27   69 14425.0000 14132.2567  2.03%  13.6  245s
 268221 135691 14421.2500   49   21 14425.0000 14133.0885  2.02%  13.5  250s
 274373 138778 14210.3542   56   20 14425.0000 14133.8990  2.02%  13.4  255s
 279915 141563 14201.8980   66   14 14425.0000 14134.6042  2.01%  13.4  260s
 285434 144332 14210.5777   58   26 14425.0000 14135.2917  2.01%  13.4  265s
 290570 146505 14271.9536   55   16 14425.0000 14136.1585  2.00%  13.3  270s
 294548 148731 14190.5554   65   41 14425.0000 14136.7198  2.00%  13.3  275s
 300096 151285 14173.3759   32   72 14425.0000 14137.6042  1.99%  13.3  280s
 304742 153471 14250.6049   38   31 14425.0000 14138.1667  1.99%  13.2  285s
 309893 156153 14346.1514   67   18 14425.0000 14138.8417  1.98%  13.2  290s
 315439 158919 14351.5690   53   23 14425.0000 14139.5360  1.98%  13.2  295s
 320850 161303 14265.7673   67   12 14425.0000 14140.2500  1.97%  13.1  300s
 326276 163978 14258.5361   40   21 14425.0000 14141.0117  1.97%  13.1  305s
 331496 166655 14315.4861   69   20 14425.0000 14141.6515  1.96%  13.1  310s
 336722 169420 infeasible   52      14425.0000 14142.2798  1.96%  13.0  315s
 342008 172149 14228.2778   51   14 14425.0000 14142.8730  1.96%  13.0  320s
 347233 175002 14211.9690   51   40 14425.0000 14143.5142  1.95%  13.0  325s
 352431 177600 14354.5876   41   45 14425.0000 14144.1594  1.95%  12.9  330s
 357716 180465 14186.4138   52   26 14425.0000 14144.6675  1.94%  12.9  335s
 362704 183205 14203.9050   63   21 14425.0000 14145.1597  1.94%  12.9  340s
 368461 185932     cutoff   63      14425.0000 14145.7346  1.94%  12.9  345s
 373768 188538 14197.6780   43   57 14425.0000 14146.2272  1.93%  12.8  350s
 379020 191131 14412.7902   48   37 14425.0000 14146.8207  1.93%  12.8  355s
 384241 193745 14331.3255   49   27 14425.0000 14147.3981  1.92%  12.8  360s
 388660 195895 14321.0566   50   23 14425.0000 14147.8394  1.92%  12.8  365s
 393084 198174 14363.5651   54   20 14425.0000 14148.2694  1.92%  12.8  370s
 398397 200480 14314.2059   54   23 14425.0000 14148.8366  1.91%  12.7  375s
 402443 202689 14218.4722   49   16 14425.0000 14149.2355  1.91%  12.7  380s
 406704 204797 14291.9768   40   23 14425.0000 14149.6806  1.91%  12.7  385s
 411713 207138 14288.7926   48   27 14425.0000 14150.1069  1.91%  12.7  390s
 415942 209277 14310.1042   48   19 14425.0000 14150.4766  1.90%  12.7  395s
 419965 211607 14237.0577   44   40 14425.0000 14150.8806  1.90%  12.6  400s
 424821 213781 14335.8512   27   54 14425.0000 14151.4218  1.90%  12.6  405s
 429954 216109 14244.1458   70   19 14425.0000 14151.8299  1.89%  12.6  410s
 434923 218391     cutoff   67      14425.0000 14152.2104  1.89%  12.6  415s
 438189 219995 14340.0208   42   10 14425.0000 14152.2709  1.89%  12.6  421s
 440714 221499 14414.1699   45   12 14425.0000 14152.6096  1.89%  12.6  425s
 445161 223574 14294.0670   56   10 14425.0000 14153.1267  1.88%  12.6  430s
 450856 225752 14164.5880   43   32 14425.0000 14153.6607  1.88%  12.5  435s
 454859 228011     cutoff   33      14425.0000 14153.9205  1.88%  12.5  440s
 460245 230523     cutoff   75      14425.0000 14154.4260  1.88%  12.5  445s
 465293 232973 14223.1462   43   28 14425.0000 14154.8655  1.87%  12.5  450s
 470526 235457 14233.6539   50   19 14425.0000 14155.2945  1.87%  12.5  455s
 473389 236861 infeasible   46      14425.0000 14155.4514  1.87%  12.5  460s
 476937 238720 14400.2470   36   35 14425.0000 14155.7499  1.87%  12.4  465s
 480327 240416 14224.2552   50   26 14425.0000 14156.0000  1.86%  12.4  470s
 485316 242660 14343.7300   69    8 14425.0000 14156.3579  1.86%  12.4  475s
 489602 244637 14169.8125   51   22 14425.0000 14156.7234  1.86%  12.4  480s
 493866 246592 14274.6201   41   27 14425.0000 14157.0156  1.86%  12.4  485s
 498312 248605 infeasible   54      14425.0000 14157.3833  1.86%  12.4  490s
 502803 250921 14349.3906   52   29 14425.0000 14157.6944  1.85%  12.4  495s
 508030 253227 infeasible   56      14425.0000 14158.0777  1.85%  12.4  500s
 511407 254841 14210.6250   46   12 14425.0000 14158.3444  1.85%  12.4  505s
 515943 256535 14399.5347   52   16 14425.0000 14158.7083  1.85%  12.4  510s
 517059 257385 14281.1875   55    8 14425.0000 14158.7390  1.85%  12.3  515s
 520612 258916 14371.3950   50   24 14425.0000 14159.0653  1.84%  12.3  521s
 524061 260563 14408.4750   51   16 14425.0000 14159.3398  1.84%  12.3  525s
 528193 262560 14293.4236   36   10 14425.0000 14159.6250  1.84%  12.3  530s
 533085 264792 14330.9735   46   29 14425.0000 14159.9338  1.84%  12.3  535s
 537298 266684 14266.0625   58   12 14425.0000 14160.2824  1.84%  12.3  540s
 541678 268802 14400.0789   31   27 14425.0000 14160.5649  1.83%  12.3  545s
 546623 270996 14232.5298   69   16 14425.0000 14160.9087  1.83%  12.3  550s
 550892 273072 infeasible   63      14425.0000 14161.2556  1.83%  12.3  555s
 554709 274872 14279.1287   42   20 14425.0000 14161.5000  1.83%  12.3  560s
 558795 276683 14297.9660   44   15 14425.0000 14161.7840  1.82%  12.3  565s
 563326 278579 14351.5000   30   14 14425.0000 14162.0840  1.82%  12.3  570s
 567540 280731 14266.9782   63   24 14425.0000 14162.3694  1.82%  12.3  575s
 571834 282785 14314.0154   54   12 14425.0000 14162.6248  1.82%  12.2  580s
 576022 284736 14385.8375   57   26 14425.0000 14162.8917  1.82%  12.2  585s
 580550 286882 14395.8177   46   22 14425.0000 14163.2193  1.81%  12.2  590s
 585032 288867 14236.5625   65    6 14425.0000 14163.4819  1.81%  12.2  595s
 589207 290979 14244.8799   33   12 14425.0000 14163.7710  1.81%  12.2  600s
 593637 292788 14360.5637   62   17 14425.0000 14164.0622  1.81%  12.2  605s
 597900 294542 14386.6250   45   24 14425.0000 14164.3389  1.81%  12.2  611s
 600722 296033 14327.1535   38   24 14425.0000 14164.5156  1.81%  12.2  615s
 604791 297903 14255.3629   50   52 14425.0000 14164.8100  1.80%  12.2  620s
 608913 299814     cutoff   49      14425.0000 14165.0889  1.80%  12.2  625s
 613429 301986 14199.7292   40   12 14425.0000 14165.3710  1.80%  12.2  630s
 617522 304016 14277.1679   59   25 14425.0000 14165.6632  1.80%  12.2  635s
 621860 305871 14255.5651   44   21 14425.0000 14165.9167  1.80%  12.2  640s
 625983 307955     cutoff   44      14425.0000 14166.1610  1.79%  12.2  645s
 628741 309057 14376.4722   52   14 14425.0000 14166.2982  1.79%  12.1  650s
 632777 310980 14184.4757   44   17 14425.0000 14166.5525  1.79%  12.1  655s
 637617 313400 14267.5833   61   14 14425.0000 14166.8073  1.79%  12.1  660s
 642179 315367 14363.2361   43   24 14425.0000 14167.0594  1.79%  12.1  665s
 645715 316960 14412.1875   44   14 14425.0000 14167.2931  1.79%  12.1  670s
 648802 318394     cutoff   61      14425.0000 14167.4931  1.79%  12.1  675s
 653503 320365 infeasible   46      14425.0000 14167.7497  1.78%  12.1  680s
 657697 322366 14275.9135   72   24 14425.0000 14167.9974  1.78%  12.1  685s
 662158 324270 14228.6431   41   12 14425.0000 14168.3021  1.78%  12.1  690s
 666754 326323 14216.3072   62   39 14425.0000 14168.5333  1.78%  12.1  695s
 671064 328513 infeasible   58      14425.0000 14168.7488  1.78%  12.1  700s
 675250 330379 14357.1055   62   23 14425.0000 14169.0000  1.77%  12.1  705s
 679474 332235 infeasible   48      14425.0000 14169.2292  1.77%  12.1  710s
 683885 334021     cutoff   40      14425.0000 14169.4663  1.77%  12.1  715s
 687067 335393     cutoff   60      14425.0000 14169.6409  1.77%  12.1  720s
 691294 337252 14325.9167   39   16 14425.0000 14169.8771  1.77%  12.1  725s
 694964 338741 14248.7294   39   31 14425.0000 14170.0647  1.77%  12.1  730s
 695888 339067     cutoff   56      14425.0000 14170.0996  1.77%  12.1  735s
 696693 339774 14328.7917   38   47 14425.0000 14170.1324  1.77%  12.1  740s
 700373 341523 14222.1646   38   25 14425.0000 14170.3571  1.77%  12.1  745s
 704074 343092 14254.3253   50   16 14425.0000 14170.5846  1.76%  12.0  750s
 707509 344743 14393.5842   51   22 14425.0000 14170.7619  1.76%  12.0  755s
 711683 346560 14200.1674   64   15 14425.0000 14171.0059  1.76%  12.0  760s
 715063 347980 14344.6806   46   24 14425.0000 14171.2092  1.76%  12.0  765s
 719355 349897 14380.6875   58    9 14425.0000 14171.4214  1.76%  12.0  771s
 723003 351591 14356.8460   61   31 14425.0000 14171.5890  1.76%  12.0  775s
 726663 353046 14269.0630   47   14 14425.0000 14171.8215  1.76%  12.0  780s
 730205 354875 14185.4377   49   29 14425.0000 14172.0132  1.75%  12.0  785s
 733558 356109 14250.9514   72   12 14425.0000 14172.1972  1.75%  12.0  790s
 737148 357845 14237.6918   48   30 14425.0000 14172.3955  1.75%  12.0  796s
 739986 359225 14181.9637   37   18 14425.0000 14172.5176  1.75%  12.0  800s
 742702 360359 14292.2750   51   29 14425.0000 14172.6712  1.75%  12.0  805s
 746287 361679 14410.6992   48   18 14425.0000 14172.7969  1.75%  12.0  810s
 750045 363603 14280.4792   45   12 14425.0000 14173.0082  1.75%  12.0  816s
 753721 365222 14247.7061   53   14 14425.0000 14173.2061  1.75%  12.0  820s
 757029 366660 14216.2453   41   15 14425.0000 14173.3542  1.74%  12.0  825s
 760187 368079 14414.6645   45   21 14425.0000 14173.5193  1.74%  12.0  830s
 764330 369610 14213.0210   39   14 14425.0000 14173.7474  1.74%  12.0  835s
 767437 371129 14326.0417   46   18 14425.0000 14173.8914  1.74%  12.0  840s
 771565 373206 infeasible   49      14425.0000 14174.0833  1.74%  12.0  845s
 774867 374545     cutoff   44      14425.0000 14174.2900  1.74%  12.0  850s
 778188 375863 14263.8672   44   30 14425.0000 14174.4444  1.74%  12.0  855s
 781717 377547 14248.6979   45   22 14425.0000 14174.6250  1.74%  12.0  860s
 786073 379286 14194.1963   45   51 14425.0000 14174.8111  1.73%  12.0  865s
 788604 380334 infeasible   46      14425.0000 14174.9444  1.73%  12.0  870s
 792297 381961 14275.8236   46   29 14425.0000 14175.1250  1.73%  12.0  875s
 795773 383653 14283.4603   57   32 14425.0000 14175.3125  1.73%  12.0  880s
 799439 385142 14356.1505   56   12 14425.0000 14175.4905  1.73%  12.0  885s
 802094 386265 14248.8281   45   38 14425.0000 14175.6296  1.73%  12.0  890s
 804924 387798 14326.8333   49   24 14425.0000 14175.7644  1.73%  12.0  895s
 809006 389608 14279.9167   38   18 14425.0000 14175.9780  1.73%  12.0  900s
 812460 390928 14419.2708   63   22 14425.0000 14176.1161  1.73%  12.0  905s
 815921 392539     cutoff   53      14425.0000 14176.2621  1.72%  12.0  910s
 819892 394122 14286.4722   50   14 14425.0000 14176.4773  1.72%  12.0  916s
 822546 395229 14248.1788   45   43 14425.0000 14176.5885  1.72%  12.0  920s
 824508 395850 14341.3229   47   18 14425.0000 14176.6894  1.72%  12.0  925s
 826406 396689 14394.2500   62   25 14425.0000 14176.7886  1.72%  12.0  930s
 830250 398275 14408.6982   58   15 14425.0000 14177.0000  1.72%  12.0  936s
 832852 399308 14289.0074   34   36 14425.0000 14177.1433  1.72%  11.9  940s
 836399 401002 14192.6944   36   15 14425.0000 14177.2969  1.72%  11.9  946s
 839635 402425 infeasible   52      14425.0000 14177.4560  1.72%  11.9  950s
 843572 404228 14261.6193   45   28 14425.0000 14177.6300  1.71%  11.9  956s
 846907 405775 14348.0252   53   24 14425.0000 14177.7729  1.71%  11.9  960s
 850040 407195     cutoff   71      14425.0000 14177.8965  1.71%  11.9  965s
 852937 408448 14265.3750   41   16 14425.0000 14178.0349  1.71%  11.9  970s
 856682 410066 14350.8575   47   31 14425.0000 14178.1875  1.71%  11.9  975s
 859973 411494 14250.0590   32   27 14425.0000 14178.3097  1.71%  11.9  980s
 863344 412973     cutoff   69      14425.0000 14178.4794  1.71%  11.9  986s
 865838 414061 14373.8750   62   12 14425.0000 14178.5982  1.71%  11.9  990s

In [21]:
comparison_50 = pd.DataFrame(
    [
        {
            "Mode":"Cold",
            **cold_50
        },
        {
            "Mode":"Warm",
            **warm_50
        }
    ]
)

comparison_50

   Mode   N  Runtime_sec  Status   ObjVal  ObjBound       Gap
0  Cold  50     1800.196       9  14425.0   14196.0  1.587522
1  Warm  50     1800.115       9  14408.0   14253.0  1.075791

In [22]:
print(cold_50)
print(warm_50)

{'N': 50, 'Runtime_sec': 1800.1960000991821, 'Status': 9, 'ObjVal': 14425.0, 'ObjBound': 14196.0, 'Gap': 1.587521663778163}
{'N': 50, 'ObjVal': 14408.0, 'ObjBound': 14253.0, 'Gap': 1.075791227096058, 'Runtime_sec': 1800.1150000095367, 'Status': 9}

In [23]:
route_100 = results_task1[2]["Route"]

cold_100 = solve_tsp_gurobi(
    distance_matrix,
    100
)

warm_100 = solve_tsp_gurobi_warm(
    distance_matrix,
    100,
    route_100
)

print(cold_100)
print(warm_100)

Set parameter TimeLimit to value 1800
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 9902 rows, 9999 columns and 48906 nonzeros (Min)
Model fingerprint: 0xaee3978c
Model has 9900 linear objective coefficients
Variable types: 99 continuous, 9900 integer (9900 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+02]
  Objective range  [2e+00, 4e+03]
  Bounds range     [1e+00, 1e+02]
  RHS range        [1e+00, 1e+02]

Presolve time: 0.08s
Presolved: 9902 rows, 9999 columns, 48906 nonzeros
Variable types: 99 continuous, 9900 integer (9900 binary)

Root relaxation: objective 1.340069e+04, 407 iterations, 0.04 seconds (0.03 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 13400.6902    0  166          - 13400.6902      -     -    0s
H    0     0                    118967.00000 13400.6902  88.7%     -    0s
H    0     0                    116813.00000 13400.6902  88.5%     -    0s
H    0     0                    89643.000000 13400.6902  85.1%     -    0s
H    0     0                    86475.000000 13400.6902  84.5%     -    0s
H    0     0                    69423.000000 13400.6902  80.7%     -    0s
H    0     0                    56604.000000 13400.6902  76.3%     -    0s
H    0     0                    56155.000000 13400.6902  76.1%     -    1s
     0     0 16698.7495    0  199 56155.0000 16698.7495  70.3%     -    1s
H    0     0                    51291.000000 16701.7842  67.4%     -    1s
H    0     0                    43439.000000 16701.7842  61.6%     -    1s
H    0     0                    43396.000000 16701.7842  61.5%     -    1s
H    0     0                    40224.000000 16701.7842  58.5%     -    1s
H    0     0                    40054.000000 16701.7842  58.3%     -    2s
H    0     0                    37034.000000 16701.7842  54.9%     -    2s
H    0     0                    27519.000000 16708.7238  39.3%     -    2s
H    0     0                    27441.000000 16708.7238  39.1%     -    2s
H    0     0                    26956.000000 16708.7238  38.0%     -    2s
H    0     0                    26919.000000 16708.7238  37.9%     -    2s
H    0     0                    26373.000000 16708.7238  36.6%     -    2s
H    0     0                    25543.000000 16708.7238  34.6%     -    2s
H    0     0                    25491.000000 16708.7238  34.5%     -    2s
H    0     0                    25371.000000 16708.7238  34.1%     -    2s
     0     0 16708.7238    0  198 25371.0000 16708.7238  34.1%     -    2s
     0     0 16708.7238    0  198 25371.0000 16708.7238  34.1%     -    2s
     0     0 17223.1597    0  170 25371.0000 17223.1597  32.1%     -    3s
H    0     0                    24130.000000 17231.7804  28.6%     -    4s
     0     0 17254.4128    0  178 24130.0000 17254.4128  28.5%     -    4s
     0     0 17384.8485    0  178 24130.0000 17384.8485  28.0%     -    4s
     0     0 17416.0152    0  194 24130.0000 17416.0152  27.8%     -    5s
     0     0 17736.1440    0  204 24130.0000 17736.1440  26.5%     -    5s
     0     0 17740.1212    0  207 24130.0000 17740.1212  26.5%     -    5s
     0     0 17743.2690    0  207 24130.0000 17743.2690  26.5%     -    5s
     0     0 17743.2690    0  207 24130.0000 17743.2690  26.5%     -    5s
     0     0 17801.8069    0  209 24130.0000 17801.8069  26.2%     -    6s
     0     0 17801.8069    0  209 24130.0000 17801.8069  26.2%     -    6s
     0     0 17847.5506    0  207 24130.0000 17847.5506  26.0%     -    6s
     0     0 17853.2173    0  200 24130.0000 17853.2173  26.0%     -    6s
     0     0 17853.2173    0  200 24130.0000 17853.2173  26.0%     -    6s
     0     0 17854.8637    0  205 24130.0000 17854.8637  26.0%     -    6s
     0     0 17856.8637    0  205 24130.0000 17856.8637  26.0%     -    6s
     0     0 17856.8637    0  205 24130.0000 17856.8637  26.0%     -    7s
     0     0 17858.0303    0  205 24130.0000 17858.0303  26.0%     -    7s
     0     0 17858.0303    0  192 24130.0000 17858.0303  26.0%     -    7s
     0     2 18043.3637    0  192 24130.0000 18043.3637  25.2%     -    8s
   436   443 19368.5330   84  119 24130.0000 18043.3637  25.2%  10.3   10s
H 1104  1094                    24098.000000 18043.3637  25.1%   9.5   11s
H 1457  1419                    23891.000000 18043.3637  24.5%   9.5   12s
  1801  1746 21167.4445  161  192 23891.0000 18043.3637  24.5%   9.6   18s
H 1802  1659                    22186.000000 18043.3637  18.7%   9.6   21s
H 1802  1576                    22164.000000 18043.3637  18.6%   9.6   21s
H 1802  1497                    22162.000000 18043.3637  18.6%   9.6   21s
H 1802  1422                    22136.000000 18043.3637  18.5%   9.6   21s
H 1803  1351                    22038.000000 18043.3637  18.1%   9.6   24s
  1804  1352 18131.1413   65  160 22038.0000 18043.3637  18.1%   9.6   29s
  1808  1355 21623.2889  416  206 22038.0000 18043.3637  18.1%   9.5   30s
  1815  1359 22038.0000  197  198 22038.0000 18043.3637  18.1%   9.5   35s
  1925  1436 19000.8050   32  171 22038.0000 18124.2185  17.8%  11.4   40s
  2511  1839 20781.3898  108   73 22038.0000 18124.2185  17.8%  15.1   45s
  3286  2275 18526.2476   38  138 22038.0000 18124.2185  17.8%  16.3   50s
H 3385  2107                    21501.000000 18124.2185  15.7%  16.5   51s
H 3627  2128                    21358.000000 18124.2185  15.1%  16.9   53s
  3758  2257 20026.6469  101  111 21358.0000 18124.2185  15.1%  17.0   55s
  4465  2670 18557.5574   71  162 21358.0000 18124.2185  15.1%  17.5   60s
H 4896  2604                    21201.000000 18124.2185  14.5%  17.3   62s
H 4991  2592                    21199.000000 18124.2185  14.5%  17.3   64s
  4995  2793 20796.0255  209   80 21199.0000 18124.2185  14.5%  17.3   65s
  5239  2755 18344.4885   47  179 21199.0000 18124.2185  14.5%  17.2   70s
H 5243  2749                    21192.000000 18124.2185  14.5%  17.2   72s
H 5244  2736                    21170.000000 18124.2185  14.4%  17.2   72s
  5516  3085 19107.3824  122  122 21170.0000 18124.2185  14.4%  17.0   75s
  6109  3605 18475.8707   90  141 21170.0000 18124.2185  14.4%  16.9   80s
H 6306  3525                    20947.000000 18124.2185  13.5%  16.8   83s
  6381  3761 18543.4992  131  145 20947.0000 18124.2185  13.5%  16.7   85s
  7241  4440 20268.1658  104   59 20947.0000 18124.2185  13.5%  16.6   90s
  8462  5437 18802.6429  145  110 20947.0000 18124.2185  13.5%  16.8   96s
  9425  6259 19625.3938   75  122 20947.0000 18124.2185  13.5%  17.2  101s
 10078  6867 18294.0006   25  199 20947.0000 18124.2185  13.5%  17.4  105s
 10893  7547 20765.9260  104  103 20947.0000 18124.2185  13.5%  17.5  110s
 12334  8788 19367.3041   85   69 20947.0000 18124.2185  13.5%  17.4  115s
*12410  8495             161    20828.000000 18124.2185  13.0%  17.4  115s
H13733  9264                    20811.000000 18124.2185  12.9%  17.1  120s
 14724 10415 19672.9948   70  107 20811.0000 18124.2185  12.9%  16.9  125s
H15395 10408                    20745.000000 18124.2185  12.6%  16.9  126s
H15735  8978                    20318.000000 18124.2185  10.8%  17.2  129s
 15822  9302 18647.8270   70  160 20318.0000 18124.2185  10.8%  17.2  132s
 16647  9822 18215.4043   39  146 20318.0000 18124.2185  10.8%  17.2  135s
 17683 10684 18772.9677   40  116 20318.0000 18124.2185  10.8%  17.4  140s
 18988 11678 19913.9099  103   73 20318.0000 18128.0255  10.8%  17.6  145s
 20311 12607 19305.3041  166   75 20318.0000 18129.6888  10.8%  17.4  150s
 20723 12678 18968.6071  184  192 20318.0000 18130.1343  10.8%  17.6  182s
H20724 12045                    20257.000000 18130.1343  10.5%  17.6  184s
 20726 12046 18337.0592   26  150 20257.0000 18130.1343  10.5%  17.6  190s
 20731 12049 18786.9786   44  182 20257.0000 18130.1343  10.5%  17.6  195s
 20733 12051 20007.7730   80  177 20257.0000 18130.1343  10.5%  17.6  200s
 20735 12052 18226.0918   57  183 20257.0000 18130.1343  10.5%  17.6  205s
 20737 12053 19273.6765   64  172 20257.0000 18130.1343  10.5%  17.6  212s
 20738 12054 19733.1901  116  161 20257.0000 18130.1343  10.5%  17.6  215s
H20738 11451                    20221.000000 18130.1343  10.3%  17.6  215s
 20742 11454 18407.1337   84  181 20221.0000 18130.1343  10.3%  17.6  225s
 20744 11455 19294.4935   61  186 20221.0000 18130.1343  10.3%  17.6  233s
 20745 11456 20221.0000   56  179 20221.0000 18130.1343  10.3%  17.6  236s
 20746 11456 19742.3653   61  179 20221.0000 18130.1343  10.3%  17.6  240s
 20748 11458 18280.0741   24  192 20221.0000 18130.1343  10.3%  17.6  247s
 20749 11458 19686.6097  108  187 20221.0000 18130.1343  10.3%  17.5  250s
 20751 11460 19081.0541   33  192 20221.0000 18130.1343  10.3%  17.5  256s
 20752 11460 19613.0433  165  192 20221.0000 18130.1343  10.3%  17.5  260s
 20754 11462 18753.7829   40  193 20221.0000 18130.1343  10.3%  17.5  267s
 20755 11462 18902.5558   50  193 20221.0000 18130.1343  10.3%  17.5  273s
 20756 11463 19767.7895   61  193 20221.0000 18130.1343  10.3%  17.5  276s
 20758 11464 19701.3408   61  193 20221.0000 18219.0000  9.90%  17.5  285s
 20832 11520 18219.0000   41  189 20221.0000 18219.0000  9.90%  17.7  290s
H20884 10976                    20188.000000 18219.0000  9.75%  17.8  294s
 20886 10985 18347.8711   47  174 20188.0000 18219.0000  9.75%  17.8  295s
 20993 11037 infeasible   60      20188.0000 18219.0000  9.75%  17.8  300s
H20996 10491                    20181.000000 18219.0000  9.72%  17.8  300s
 21165 10581 18219.0000   34  179 20181.0000 18219.0000  9.72%  17.9  305s
 21437 10736 18252.7721   52  153 20181.0000 18219.0000  9.72%  17.9  310s
 21897 11032 19678.1883  101  106 20181.0000 18219.0000  9.72%  18.1  315s
 22458 11273 19809.7821  108  119 20181.0000 18219.0000  9.72%  18.0  320s
 23042 11531 18310.4423   55  127 20181.0000 18219.0000  9.72%  18.0  325s
 23776 11809 19181.5286   76  142 20181.0000 18219.0000  9.72%  17.9  330s
 24529 12203 18513.3903  102   71 20181.0000 18219.0000  9.72%  18.0  336s
 25280 12394 18575.3670  153   66 20181.0000 18219.0000  9.72%  18.0  340s
H25391 12057                    20179.000000 18219.0000  9.71%  18.0  342s
 26012 12273 18590.6496  172   79 20179.0000 18219.0000  9.71%  18.0  346s
H26020 11747                    20147.000000 18219.0000  9.57%  18.0  346s
 26526 11956 18603.5595  194   73 20147.0000 18219.0000  9.57%  18.1  351s
 27069 12335 18637.6789  225   80 20147.0000 18219.0000  9.57%  18.2  355s
 28405 12911 18781.6819  307   75 20147.0000 18219.0000  9.57%  18.2  362s
 28872 12764 18717.0419   97   96 20147.0000 18219.0000  9.57%  18.1  367s
H28873 12106                    20063.999943 18219.0000  9.20%  18.1  367s
 29450 12822 19630.8694  136  115 20063.9999 18219.0000  9.20%  18.1  372s
 30051 12994 19121.9300   64  157 20063.9999 18219.0000  9.20%  18.2  375s
H31155 12625                    20020.000000 18219.0000  9.00%  18.3  378s
 31156 12626 19043.3624   85  192 20020.0000 18219.0000  9.00%  18.3  382s
 31159 12628 19810.5930  135  149 20020.0000 18219.0000  9.00%  18.3  389s
 31162 12630 18436.6213   40  186 20020.0000 18219.0000  9.00%  18.3  390s
 31166 12633 19427.3196   54  183 20020.0000 18219.0000  9.00%  18.3  396s
 31168 12634 18540.3103   81  174 20020.0000 18219.0000  9.00%  18.3  401s
 31169 12635 19016.2305  145  174 20020.0000 18219.0000  9.00%  18.3  405s
 31171 12636 19532.4753  339  172 20020.0000 18219.0000  9.00%  18.3  410s
 31173 12637 18429.9092   44  184 20020.0000 18219.0000  9.00%  18.3  416s
 31175 12639 19412.5990  106  188 20020.0000 18219.0000  9.00%  18.3  422s
 31177 12640 19832.2457   99  188 20020.0000 18219.0000  9.00%  18.3  427s
 31178 12641 18666.6687   63  188 20020.0000 18219.0000  9.00%  18.3  430s
 31180 12642 18507.9966   52  188 20020.0000 18219.0000  9.00%  18.3  437s
 31181 12643 18495.7915   50  188 20020.0000 18219.0000  9.00%  18.3  441s
 31183 12644 18617.5315   68  188 20020.0000 18219.0000  9.00%  18.3  445s
H31183 12011                    20002.000000 18219.0000  8.91%  18.3  448s
 31184 12012 18594.7356   56  188 20002.0000 18229.5593  8.86%  18.3  452s
 31242 12058 18229.5593   54  159 20002.0000 18229.5593  8.86%  18.5  455s
 31319 12105 18332.5554   61  148 20002.0000 18229.5593  8.86%  18.5  460s
 31435 12180 18466.2104   66  140 20002.0000 18229.5593  8.86%  18.6  465s
H31548 11625                    19936.000000 18229.5593  8.56%  18.7  470s
 31778 11720 18229.5593   48  178 19936.0000 18229.5593  8.56%  18.7  475s
 32140 11967 18330.7514   72  145 19936.0000 18229.5593  8.56%  18.8  480s
 32602 12173 19609.8896  127  108 19936.0000 18229.5593  8.56%  18.9  485s
 33153 12499 18261.7465   52  151 19936.0000 18229.5593  8.56%  18.8  490s
 33931 12937 19813.8418  115  142 19936.0000 18233.1544  8.54%  18.8  496s
 34665 13285 19455.2051   79  124 19936.0000 18235.7589  8.53%  18.8  500s
 35895 13885 18562.7745   80   90 19936.0000 18245.5905  8.48%  18.8  506s
 36774 14265 19169.0105   80  162 19936.0000 18249.5344  8.46%  18.9  511s
 37463 14643 18874.3871  104  106 19936.0000 18253.1125  8.44%  18.8  515s
 38610 15086 18941.0439   83  130 19936.0000 18258.7653  8.41%  19.0  520s
 39089 15264 19132.9955   85  142 19936.0000 18260.0799  8.41%  19.0  525s
 40296 15964 18444.3072   93  102 19936.0000 18265.1939  8.38%  19.0  532s
 41163 16152 infeasible  122      19936.0000 18266.4051  8.37%  19.0  535s
 42035 17096 18571.8162   77  135 19936.0000 18270.5837  8.35%  18.9  541s
 43321 17451 18934.4393   84  123 19936.0000 18274.0072  8.34%  19.0  545s
 44616 17705 19022.9252  267   88 19936.0000 18275.7458  8.33%  18.9  550s
 44632 17713 19033.7468  270  100 19936.0000 18275.7458  8.33%  18.9  555s
 45111 18261 19016.8784   85  140 19936.0000 18276.1819  8.33%  18.9  560s
 46370 18883 19626.7653   88  113 19936.0000 18278.2062  8.32%  18.9  565s
 47647 19472 19526.2177  122  135 19936.0000 18280.8546  8.30%  18.9  570s
 49079 20159 18355.8180   84   54 19936.0000 18283.7663  8.29%  18.9  575s
 50612 20701 19323.9207   88   86 19936.0000 18285.9853  8.28%  18.8  580s
 52172 21480 19375.5315  113  101 19936.0000 18289.1104  8.26%  18.7  585s
 53929 22282 19387.2968   92   76 19936.0000 18292.1842  8.25%  18.7  591s
 55435 23055 19324.0668   79   89 19936.0000 18293.9768  8.24%  18.7  596s
 56722 23698 18744.2376   76  123 19936.0000 18296.6933  8.22%  18.7  600s
 58017 24248 18533.1497   66   78 19936.0000 18297.3401  8.22%  18.6  605s
 59139 24745 18520.9396   93   84 19936.0000 18299.8246  8.21%  18.7  610s
 60606 25483 19237.9355   84  102 19936.0000 18302.2577  8.19%  18.7  616s
 61641 25814 18429.4762   60  166 19936.0000 18303.1016  8.19%  18.6  620s
 62864 26311 18651.9323   53  166 19936.0000 18305.0087  8.18%  18.6  626s
 63096 26237 18793.8003   82  117 19936.0000 18305.0087  8.18%  18.6  630s
H63100 25651                    19932.000000 18305.0087  8.16%  18.6  633s
 63104 25681 18794.3324   83  110 19932.0000 18305.0087  8.16%  18.6  638s
 63137 26631 19352.0822   98   94 19932.0000 18305.0087  8.16%  18.6  644s
 64488 26999 18468.9445   69   88 19932.0000 18308.3418  8.15%  18.7  647s
 65736 27873 18760.4632   68  125 19932.0000 18311.8424  8.13%  18.7  651s
 67314 28978 18575.8963   60  168 19932.0000 18314.2901  8.12%  18.8  656s
 68868 30288 18398.1004   57  160 19932.0000 18315.5524  8.11%  18.8  661s
 70087 31136 19302.6687  147   88 19932.0000 18316.4215  8.11%  18.8  666s
 71322 32197 18513.1190   62  180 19932.0000 18318.3827  8.10%  18.9  671s
 72249 32925 18664.0500   68  113 19932.0000 18319.1582  8.09%  18.9  675s
 73990 33973 19784.8121  104   97 19932.0000 18321.6089  8.08%  18.8  689s
 74003 34261 18347.9244   54  205 19932.0000 18321.6488  8.08%  18.8  690s
 74413 34317 19752.1997   92   98 19932.0000 18322.0466  8.08%  18.8  695s
 75390 35304 18583.1241  159   49 19932.0000 18323.1301  8.07%  18.8  700s
 76719 36278 18419.6220  127  100 19932.0000 18323.8801  8.07%  18.9  705s
 78440 37636 19305.5391   88   61 19932.0000 18325.4962  8.06%  18.9  711s
 79415 38448 18833.9850  265   99 19932.0000 18326.7886  8.05%  18.9  715s
 80972 39636 18437.3853   65  127 19932.0000 18327.2516  8.05%  18.8  721s
 82481 40857 18398.2711   79   96 19932.0000 18328.3371  8.05%  18.7  726s
 83965 42335 18583.8836   76  113 19932.0000 18329.0797  8.04%  18.6  732s
 85130 42892 18548.6275  175   97 19932.0000 18329.8236  8.04%  18.6  735s
 86500 43916 19237.0677  110   96 19932.0000 18330.6456  8.03%  18.5  740s
 87836 45075 19133.7126  236   93 19932.0000 18331.5000  8.03%  18.5  745s
 89583 46304 18991.6513  247   84 19932.0000 18332.5268  8.02%  18.4  750s
 91312 47689 infeasible  155      19932.0000 18333.5264  8.02%  18.4  756s
 92735 48711 19914.4694  131   86 19932.0000 18333.9136  8.02%  18.3  760s
 94181 49971 18563.5170  221   61 19932.0000 18334.4554  8.01%  18.4  767s
 95264 50691 18813.6445   90   84 19932.0000 18334.8197  8.01%  18.4  770s
 97246 52310 18569.9032  251   87 19932.0000 18335.2500  8.01%  18.3  776s
 98585 53366 19275.8715  122   89 19932.0000 18336.4226  8.01%  18.2  780s
 99900 54417 18437.9745  146   65 19932.0000 18337.5271  8.00%  18.2  785s
 101461 55703 18666.1165   76  124 19932.0000 18338.1696  8.00%  18.2  790s
 103027 56887 18540.1436   56  132 19932.0000 18339.1085  7.99%  18.2  795s
 104295 57865 19161.4272  115   77 19932.0000 18339.9132  7.99%  18.2  800s
 105344 58854 18603.9614   75   85 19932.0000 18340.6250  7.98%  18.2  805s
 106644 60002 18590.5335   86   83 19932.0000 18341.1020  7.98%  18.1  810s
 108439 61423 18647.7189   69  139 19932.0000 18341.6057  7.98%  18.1  815s
 110191 62846 19545.8866  122   73 19932.0000 18342.4401  7.97%  18.0  820s
 111512 63880 19501.6302  147   70 19932.0000 18342.6233  7.97%  18.0  825s
 112959 65118 18534.8894   70  102 19932.0000 18343.4558  7.97%  18.0  830s
 114414 66252 18735.7020  139  120 19932.0000 18343.6547  7.97%  18.0  836s
 115113 67120 19140.8806  115  112 19932.0000 18343.8952  7.97%  17.9  840s
 116554 68059 18631.0905  334   66 19932.0000 18344.3867  7.97%  17.9  845s
 118106 69168 18836.5884   84   69 19932.0000 18344.9340  7.96%  17.9  850s
 119338 70258 18735.5136  182   78 19932.0000 18346.0317  7.96%  17.8  855s
 120522 71184 18767.8403   64  173 19932.0000 18346.6283  7.95%  17.8  860s
 121872 72427 18378.6272   58  124 19932.0000 18346.6933  7.95%  17.8  865s
 123263 73479 18494.0918   64   95 19932.0000 18347.1431  7.95%  17.8  871s
 124408 74411 18519.4830   91   55 19932.0000 18347.5164  7.95%  17.8  876s
 125728 75672 19652.5121  161  120 19932.0000 18348.0799  7.95%  17.8  882s
 126921 76449 infeasible   88      19932.0000 18348.4024  7.95%  17.7  885s
 128225 77533 18486.4799   60  155 19932.0000 18348.9132  7.94%  17.8  891s
 129383 78431 19872.0017  110   20 19932.0000 18349.4044  7.94%  17.8  895s
 130471 79237 18866.2374   64  157 19932.0000 18349.7633  7.94%  17.8  900s
 131637 80212 19073.7823   75  131 19932.0000 18350.2264  7.94%  17.8  905s
 132876 81192 infeasible  202      19932.0000 18350.6216  7.93%  17.8  910s
 134055 82079 18431.3474   66  119 19932.0000 18351.3701  7.93%  17.8  915s
 135223 83066 18962.2687   95   71 19932.0000 18351.6241  7.93%  17.9  921s
 136062 83835 18396.5669   65  138 19932.0000 18351.8679  7.93%  17.9  926s
 137457 84697 18714.3052   62  109 19932.0000 18352.2817  7.93%  17.9  931s
 138455 85767 18752.5046  220  106 19932.0000 18352.3804  7.93%  17.9  935s
 140288 87115 19459.3547  127   91 19932.0000 18353.1001  7.92%  17.8  941s
 141561 88210 19410.6777  103   34 19932.0000 18353.3962  7.92%  17.8  946s

In [24]:
comparison_100 = pd.DataFrame(
    [
        {"Mode":"Cold", **cold_100},
        {"Mode":"Warm", **warm_100}
    ]
)

comparison_100

   Mode    N  Runtime_sec  Status   ObjVal  ObjBound       Gap
0  Cold  100     1800.286       9  19896.0   18376.0  7.639727
1  Warm  100     1800.086       9  18850.0   18585.0  1.405836

In [25]:
route_250 = results_task1[3]["Route"]

cold_250 = solve_tsp_gurobi(
    distance_matrix,
    250
)

warm_250 = solve_tsp_gurobi_warm(
    distance_matrix,
    250,
    route_250
)

print(cold_250)
print(warm_250)

Set parameter TimeLimit to value 1800
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 62252 rows, 62499 columns and 309756 nonzeros (Min)
Model fingerprint: 0xfb97034f
Model has 62250 linear objective coefficients
Variable types: 249 continuous, 62250 integer (62250 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [1e+00, 4e+03]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Presolve time: 0.75s
Presolved: 62252 rows, 62499 columns, 309756 nonzeros
Variable types: 249 continuous, 62250 integer (62250 binary)
Deterministic concurrent LP optimizer: primal and dual simplex
Showing primal log only...

Concurrent spin time: 0.01s

Solved with dual simplex

Root relaxation: objective 1.827843e+04, 974 iterations, 0.61 seconds (0.24 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 18278.4324    0  410          - 18278.4324      -     -    3s
H    0     0                    298890.00000 18278.4324  93.9%     -    9s
     0     0 23328.2369    0  458 298890.000 23328.2369  92.2%     -   10s
H    0     0                    205995.00000 23328.7369  88.7%     -   11s
H    0     0                    159412.00000 23328.7369  85.4%     -   12s
H    0     0                    140175.00000 23328.7369  83.4%     -   13s
H    0     0                    102502.00000 23328.7369  77.2%     -   14s
H    0     0                    91213.000000 23328.7369  74.4%     -   14s
H    0     0                    91147.000000 23328.7369  74.4%     -   14s
H    0     0                    86961.000000 23328.7369  73.2%     -   14s
H    0     0                    86895.000000 23328.7369  73.2%     -   15s
H    0     0                    85885.000000 23328.7369  72.8%     -   16s
H    0     0                    72624.000000 23328.7369  67.9%     -   16s
     0     0 23371.8795    0  450 72624.0000 23371.8795  67.8%     -   19s
     0     0 23371.8795    0  450 72624.0000 23371.8795  67.8%     -   19s
H    0     0                    68240.000000 23371.8795  65.8%     -   22s
H    0     0                    68225.000000 23371.8795  65.7%     -   22s
H    0     0                    68096.000000 24267.2973  64.4%     -   22s
     0     0 24267.2973    0  481 68096.0000 24267.2973  64.4%     -   22s
     0     0 24275.8193    0  441 68096.0000 24275.8193  64.4%     -   23s
H    0     0                    67698.000000 24275.8193  64.1%     -   23s
     0     0 24275.8193    0  441 67698.0000 24275.8193  64.1%     -   23s
H    0     0                    65062.000000 24275.8193  62.7%     -   26s
H    0     0                    61650.000000 24275.8193  60.6%     -   26s
H    0     0                    49059.000000 24510.4975  50.0%     -   27s
H    0     0                    47924.000000 24510.4975  48.9%     -   27s
     0     0 24510.4975    0  426 47924.0000 24510.4975  48.9%     -   27s
     0     0 24517.3269    0  459 47924.0000 24517.3269  48.8%     -   27s
     0     0 24517.4102    0  459 47924.0000 24517.4102  48.8%     -   27s
H    0     0                    47057.000000 24517.4102  47.9%     -   30s
H    0     0                    38798.000000 24517.4102  36.8%     -   30s
     0     0 24538.6355    0  459 38798.0000 24538.6355  36.8%     -   30s
     0     0 24547.1355    0  459 38798.0000 24547.1355  36.7%     -   31s
     0     0 24547.1355    0  472 38798.0000 24547.1355  36.7%     -   33s
     0     0 24547.1355    0  472 38798.0000 24547.1355  36.7%     -   33s
H    0     0                    38587.000000 24547.1355  36.4%     -   36s
H    0     0                    38464.000000 24547.1355  36.2%     -   36s
     0     0 24547.1355    0  472 38464.0000 24547.1355  36.2%     -   36s
     0     0 24560.1412    0  472 38464.0000 24560.1412  36.1%     -   36s
     0     0 24560.1412    0  472 38464.0000 24560.1412  36.1%     -   38s
     0     0 24560.1412    0  462 38464.0000 24560.1412  36.1%     -   39s
     0     0 24560.1412    0  465 38464.0000 24560.1412  36.1%     -   40s
     0     0 24560.1412    0  470 38464.0000 24560.1412  36.1%     -   42s
     0     0 24560.1412    0  470 38464.0000 24560.1412  36.1%     -   43s
     0     0 24560.1412    0  462 38464.0000 24560.1412  36.1%     -   45s
     0     0 24580.0218    0  462 38464.0000 24580.0218  36.1%     -   49s
     0     0 24580.0218    0  461 38464.0000 24580.0218  36.1%     -   50s
     0     0 24580.0218    0  464 38464.0000 24580.0218  36.1%     -   51s
     0     0 24580.0218    0  461 38464.0000 24580.0218  36.1%     -   55s
     0     0 24580.0218    0  461 38464.0000 24580.0218  36.1%     -   55s
     0     0 24580.0218    0  461 38464.0000 24580.0218  36.1%     -   56s
     0     0 24580.0218    0  459 38464.0000 24580.0218  36.1%     -   56s
     0     2 24836.4218    0  459 38464.0000 24836.4218  35.4%     -   66s
    76    82 24836.4218   13  420 38464.0000 24836.4218  35.4%  32.4   70s
   236   261 25171.3329   39  302 38464.0000 24836.4218  35.4%  28.9   75s
   575   574 25815.2180   98  312 38464.0000 24836.4218  35.4%  20.1   80s
   885   879 27273.8806  177  270 38464.0000 24836.4218  35.4%  17.9   85s
H  899   879                    37261.000000 24836.4218  33.3%  17.8   85s
  1182  1193 27805.4227  274  270 37261.0000 24836.4218  33.3%  16.9   90s
H 1191  1193                    37008.000000 24836.4218  32.9%  16.9   90s
H 1235  1193                    36759.000000 24836.4218  32.4%  16.8   90s
H 1315  1268                    36554.000000 24836.4218  32.1%  16.5   92s
  1436  1389 27879.1072  322  212 36554.0000 24836.4218  32.1%  16.7   96s
H 1438  1389                    36543.000000 24836.4218  32.0%  16.7   96s
  1623  1619 28733.6647  369  231 36543.0000 24836.4218  32.0%  17.3  100s
  1890  1911 29136.0040  461  195 36543.0000 24836.4218  32.0%  18.3  105s
  2186  2232 32358.0148  539  223 36543.0000 24836.4218  32.0%  17.9  110s
H 2455  2374                    35285.000000 24836.4218  29.6%  17.3  114s
H 2456  2364                    34756.000000 24836.4218  28.5%  17.3  114s
  2459  2482 33110.0428  599  233 34756.0000 24836.4218  28.5%  17.3  115s
  2793  2822 33127.4097  684  191 34756.0000 24836.4218  28.5%  17.3  121s
H 2931  2745                    33518.000000 24836.4218  25.9%  17.0  123s
H 2933  1945                    30769.000000 24836.4218  19.3%  17.0  123s
  2935  2029     cutoff  726      30769.0000 24836.4218  19.3%  17.0  125s
H 3149  2103                    30580.000000 24836.4218  18.8%  17.3  127s
  3150  2104 25581.1601   88  459 30580.0000 24836.4218  18.8%  17.3  164s
  3152  2105 28677.8515  367  412 30580.0000 24836.4218  18.8%  17.3  212s
  3153  2106 25228.6637   35  460 30580.0000 24836.4218  18.8%  17.3  310s
  3156  2108 30513.8812  472  472 30580.0000 24836.4218  18.8%  17.3  318s
  3157  2109 29873.7090  205  453 30580.0000 24836.4218  18.8%  17.3  329s
  3159  2110 26646.4819   71  465 30580.0000 24836.4218  18.8%  17.3  337s
  3160  2111 27003.9017   98  462 30580.0000 24846.7628  18.7%  17.2  347s
  3162  2112 27524.0320  230  460 30580.0000 24847.0888  18.7%  17.2  356s
  3163  2113 24888.0952   11  453 30580.0000 24888.0952  18.6%  17.2  361s
  3165  2114 27170.3208  219  462 30580.0000 24890.9176  18.6%  17.2  369s
  3166  2115 24894.5943   10  478 30580.0000 24894.5943  18.6%  17.2  370s
  3168  2116 25038.9073   30  457 30580.0000 24902.7976  18.6%  17.2  375s
  3170  2117 27441.9178  227  460 30580.0000 24903.8726  18.6%  17.2  381s
  3172  2119 29143.6850  371  492 30580.0000 24904.7553  18.6%  17.2  386s
  3174  2120 28587.9479  346  447 30580.0000 24906.9655  18.6%  17.2  392s
  3176  2121 28606.5717  155  428 30580.0000 24931.5671  18.5%  17.2  398s
  3178  2123 27811.1545  274  474 30580.0000 24937.6226  18.5%  17.1  400s
  3180  2124 25329.0583   47  482 30580.0000 24939.0839  18.4%  17.1  406s
  3181  2125 25103.5586   37  464 30580.0000 24939.9424  18.4%  17.1  411s
  3184  2127 25687.8057   48  474 30580.0000 24948.8311  18.4%  17.1  418s
  3185  2127 26242.6627   50  475 30580.0000 24948.8311  18.4%  17.1  420s
  3188  2129 25860.7937  107  476 30580.0000 24948.8311  18.4%  17.1  426s
  3189  2130 29874.5291  211  474 30580.0000 24948.8311  18.4%  17.1  430s
  3191  2131 30255.1172  417  485 30580.0000 24948.8311  18.4%  17.1  435s
  3193  2133 29798.1603  449  485 30580.0000 25105.0000  17.9%  17.1  501s
  3196  2140 25105.0000   16  466 30580.0000 25105.0000  17.9%  19.8  508s
  3204  2149 25105.0000   18  448 30580.0000 25105.0000  17.9%  20.0  510s
  3228  2162 25105.0000   21  440 30580.0000 25105.0000  17.9%  20.6  515s
  3256  2183 25105.0000   25  445 30580.0000 25105.0000  17.9%  21.2  520s
  3294  2207 25105.0000   30  355 30580.0000 25105.0000  17.9%  21.5  525s
  3340  2236 25297.6836   35  426 30580.0000 25105.0000  17.9%  21.6  531s
  3381  2261 infeasible   40      30580.0000 25105.0000  17.9%  21.8  536s
  3424  2282 26455.4718   45  417 30580.0000 25105.0000  17.9%  21.9  540s
  3471  2307 26615.9637   52  414 30580.0000 25105.0000  17.9%  22.0  545s
  3519  2345 26534.2735   59  393 30580.0000 25105.0000  17.9%  22.2  550s
  3605  2393 26541.0661   71  385 30580.0000 25105.0000  17.9%  22.4  557s
  3668  2443 26548.5677   78  343 30580.0000 25105.0000  17.9%  22.9  561s
  3738  2477 26669.5126   90  400 30580.0000 25105.0000  17.9%  23.2  565s
  3804  2528 26710.7159   97  346 30580.0000 25105.0000  17.9%  23.9  571s
  3892  2583 27263.3620  111  279 30580.0000 25105.0000  17.9%  24.6  576s
  3979  2647 28113.0243  122  297 30580.0000 25105.0000  17.9%  25.0  581s
  4096  2727 28140.1996  140  276 30580.0000 25105.0000  17.9%  25.3  588s
  4151  2712 28120.5964  149  316 30580.0000 25105.0000  17.9%  25.5  597s
H 4155  2607                    30504.999982 25105.0000  17.7%  25.5  602s
  4159  2666 28121.3692  150  312 30505.0000 25105.0000  17.7%  25.5  606s
  4282  2744 28147.2254  172  306 30505.0000 25105.0000  17.7%  25.8  613s
  4341  2778 28154.8582  183  303 30505.0000 25105.0000  17.7%  25.9  617s
  4395  2834 28161.5135  192  262 30505.0000 25105.0000  17.7%  26.0  621s
  4471  2886 28172.9556  202  305 30505.0000 25105.0000  17.7%  26.0  625s
  4549  2931 28670.9113  213  293 30505.0000 25105.0000  17.7%  26.0  630s
  4692  3007 29949.8077  233  282 30505.0000 25105.0000  17.7%  26.3  638s
  4751  3059 28199.7042  241  297 30505.0000 25105.0000  17.7%  26.5  644s
  4823  3115 28205.0577  251  262 30505.0000 25105.0000  17.7%  26.9  649s
  4903  3174 28495.9806  259  301 30505.0000 25105.0000  17.7%  27.1  654s
  4990  3149 28210.8099  268  274 30505.0000 25105.0000  17.7%  27.3  664s
  4994  3156 30395.5976  268  306 30505.0000 25105.0000  17.7%  27.4  671s
  5003  3189 28211.6565  269  266 30505.0000 25105.0000  17.7%  27.4  679s
H 5022  3080                    30440.000000 25105.0000  17.5%  27.6  679s
  5039  3163 28358.5695  278  261 30440.0000 25105.0000  17.5%  27.7  685s
  5132  3244 28219.3006  287  289 30440.0000 25105.0000  17.5%  27.9  691s
  5244  3323 28236.9213  301  294 30440.0000 25105.0000  17.5%  28.0  698s
  5368  3387 28264.2567  321  304 30440.0000 25105.0000  17.5%  28.0  704s
  5488  3460 25105.0000   36  443 30440.0000 25105.0000  17.5%  28.3  712s
  5605  3537 25466.7688   55  334 30440.0000 25105.0000  17.5%  28.7  719s
  5730  3594 27273.8357   72  335 30440.0000 25105.0000  17.5%  29.0  726s
  5857  3666 infeasible   86      30440.0000 25105.0000  17.5%  29.2  733s
  6000  3746 28025.3250  110  236 30440.0000 25105.0000  17.5%  29.4  741s
  6136  3804 28034.1972  133  257 30440.0000 25105.0000  17.5%  29.7  749s
  6273  3913 28050.2996  153  243 30440.0000 25105.0000  17.5%  29.8  757s
  6433  3966 28053.6317  170  254 30440.0000 25105.0000  17.5%  30.1  766s
  6572  4090 28206.3982  186  245 30440.0000 25105.0000  17.5%  30.1  775s
  6760  4136 28407.3584  211  235 30440.0000 25105.0000  17.5%  30.5  784s
  6877  4288 29328.3794  228  221 30440.0000 25105.0000  17.5%  30.9  794s
  7081  4321 29891.8239  251  205 30440.0000 25105.0000  17.5%  31.1  804s
  7218  4448 30110.7594  281  251 30440.0000 25105.0000  17.5%  31.2  815s
  7459  4587 25105.0000   21  455 30440.0000 25105.0000  17.5%  31.3  825s
  7711  4702 25165.3538   49  347 30440.0000 25105.0000  17.5%  31.3  836s
  7928  4903 26161.3987   70  326 30440.0000 25105.0000  17.5%  31.3  848s
  8220  4964 26385.9326  102  272 30440.0000 25105.0000  17.5%  31.4  859s
  8398  5266 27431.7606  119  316 30440.0000 25105.0000  17.5%  31.3  871s
  8805  5233 27418.8651  157  245 30440.0000 25105.0000  17.5%  30.9  888s
H 8847  5149                    30403.000000 25105.0000  17.4%  30.9  888s
H 8894  4975                    30161.000000 25105.0000  16.8%  30.8  888s
  8916  5236 27427.9659  178  257 30161.0000 25105.0000  16.8%  30.8  903s
  9204  5475 28141.3827  201  295 30161.0000 25105.0000  16.8%  30.8  918s
  9513  5681 30155.9589  242  278 30161.0000 25105.0000  16.8%  30.7  933s
H 9857  5679                    30154.000000 25105.0000  16.7%  30.2  958s
H 9858  5539                    29975.000000 25105.0000  16.2%  30.2  958s
  9861  5846 28624.4905  298  260 29975.0000 25105.0000  16.2%  30.2  973s
 10218  6249 28468.7611  356  268 29975.0000 25105.0000  16.2%  30.0 1001s
 10648  6611 29043.7181  395  232 29975.0000 25105.0000  16.2%  29.9 1014s
 11055  6645 29627.6758  445  240 29975.0000 25105.0000  16.2%  29.5 1028s
 11169  6908     cutoff  445      29975.0000 25105.0000  16.2%  29.4 1042s
H11276  6736                    29827.000000 25105.0000  15.8%  29.4 1042s
 11440  6976 infeasible  446      29827.0000 25105.0000  15.8%  29.3 1057s
 11722  7444 25670.3730   59  346 29827.0000 25105.0000  15.8%  29.2 1073s
 12220  7818 26793.4893  130  350 29827.0000 25105.0000  15.8%  28.9 1089s
 12674  7822 27831.8993  278  235 29827.0000 25105.0000  15.8%  28.5 1108s
H12676  7813                    29814.000000 25105.0000  15.8%  28.5 1108s
 12678  8254 27871.4652  279  236 29814.0000 25105.0000  15.8%  28.5 1124s
 13131  8607     cutoff  370      29814.0000 25105.0000  15.8%  28.3 1145s
H13278  8544                    29775.000000 25105.0000  15.7%  28.3 1145s
 13523  9116 28005.4161   79  288 29775.0000 25105.0000  15.7%  28.1 1162s
 14129  9431 27637.4098  109  335 29775.0000 25105.0000  15.7%  27.7 1178s
 14530  9839 28477.0162  253  326 29775.0000 25105.0000  15.7%  27.6 1193s
 14973 10232 25910.3341   87  284 29775.0000 25105.0000  15.7%  27.4 1209s
 15408 10531 28053.5128  251  205 29775.0000 25105.0000  15.7%  27.2 1224s
 15746 10899 25255.5518   26  366 29775.0000 25105.0000  15.7%  27.2 1238s
 16153 11152 26107.2016   94  297 29775.0000 25105.0000  15.7%  27.4 1252s
 16436 11537 26540.5682  157  305 29775.0000 25105.0000  15.7%  27.5 1266s
 16873 11885 26951.2636  302  253 29775.0000 25105.0000  15.7%  27.4 1281s
 17255 12186 27540.1856  442  242 29775.0000 25105.0000  15.7%  27.4 1295s
 17600 12522 27567.6592  561  214 29775.0000 25105.0000  15.7%  27.6 1309s
 18008 12830 27589.6140  668  232 29775.0000 25105.0000  15.7%  27.6 1323s
 18348 12834 26179.6244   91  314 29775.0000 25105.0000  15.7%  27.7 1339s
 18349 12834 29477.4941  126  297 29775.0000 25105.0000  15.7%  27.7 1340s
 18352 12838 26199.0841   92  313 29775.0000 25105.0000  15.7%  27.7 1357s
H18353 12764                    29731.000000 25105.0000  15.6%  27.7 1357s
 18356 12977 26199.3271   93  309 29731.0000 25105.0000  15.6%  27.7 1373s
 18584 13259 27684.0832  172  275 29731.0000 25105.0000  15.6%  27.8 1392s
 18903 13436 29188.9586  273  254 29731.0000 25105.0000  15.6%  27.7 1410s
 19087 13550 29188.9932  274  252 29731.0000 25105.0000  15.6%  27.8 1429s
 19299 13830 29189.6642  275  261 29731.0000 25105.0000  15.6%  27.8 1450s
H19584 13699                    29607.000000 25105.0000  15.2%  27.8 1482s
 19703 14258 29189.9228  277  259 29607.0000 25105.0000  15.2%  27.9 1500s
 20311 14722 27756.7075  155  334 29607.0000 25105.0000  15.2%  27.8 1517s
H20803 14240                    29412.000000 25105.0000  14.6%  27.6 1662s
H20803 13677                    29206.000000 25105.0000  14.0%  27.6 1663s
 20804 13675 28954.4918  535  459 29206.0000 25105.0000  14.0%  27.6 1715s
 20806 13676 25105.0000   29  411 29206.0000 25105.0000  14.0%  27.6 1738s
H20806 12992                    29176.000000 25105.0000  14.0%  27.6 1800s

Cutting planes:
  Learned: 12
  Gomory: 115
  Cover: 3
  MIR: 22
  Mixing: 1
  Knapsack: 1
  Flow cover: 79
  GUB cover: 1
  Inf proof: 1
  Zero half: 41

Explored 20806 nodes (581548 simplex iterations) in 1800.58 seconds (1232.51 work units)
Thread count was 8 (of 8 available processors)

Solution count 10: 29176 29206 29412 ... 30154

Time limit reached
Best objective 2.917600000000e+04, best bound 2.510500000000e+04, gap 13.9532%
Set parameter TimeLimit to value 1800
Starting optimization...
Solver runtime: 2.384185791015625e-07
Gurobi runtime: 0.0
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 62252 rows, 62499 columns and 309756 nonzeros (Min)
Model fingerprint: 0xdb39ffe8
Model has 62250 linear objective coefficients
Variable types: 249 continuous, 62250 integer (62250 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [1e+00, 4e+03]
  Bounds range     [1e+00, 2e+02]
  RHS range        [1e+00, 2e+02]

Loaded user MIP start with objective 26883

Presolve time: 0.64s
Presolved: 62252 rows, 62499 columns, 309756 nonzeros
Variable types: 249 continuous, 62250 integer (62250 binary)
Deterministic concurrent LP optimizer: primal and dual simplex
Showing primal log only...

Concurrent spin time: 0.00s

Solved with dual simplex

Root relaxation: objective 1.827843e+04, 974 iterations, 0.45 seconds (0.24 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 18278.4324    0  410 26883.0000 18278.4324  32.0%     -    2s
H    0     0                    26820.000000 18278.4324  31.8%     -    3s
     0     0 23328.2369    0  463 26820.0000 23328.2369  13.0%     -   10s
H    0     0                    26698.000000 23347.6446  12.5%     -   20s
     0     0 23371.8795    0  453 26698.0000 23371.8795  12.5%     -   20s
     0     0 23371.8795    0  456 26698.0000 23371.8795  12.5%     -   20s
     0     0 23980.1443    0  462 26698.0000 23980.1443  10.2%     -   25s
     0     0 24008.9776    0  471 26698.0000 24008.9776  10.1%     -   25s
     0     0 24008.9816    0  481 26698.0000 24008.9816  10.1%     -   26s
     0     0 24517.9902    0  491 26698.0000 24517.9902  8.17%     -   30s
     0     0 24520.5272    0  491 26698.0000 24520.5272  8.16%     -   31s
     0     0 24520.5272    0  491 26698.0000 24520.5272  8.16%     -   31s
     0     0 24574.8860    0  477 26698.0000 24574.8860  7.95%     -   36s
     0     0 24579.3498    0  477 26698.0000 24579.3498  7.94%     -   36s
     0     0 24579.3498    0  477 26698.0000 24579.3498  7.94%     -   37s
     0     0 24585.0289    0  481 26698.0000 24585.0289  7.91%     -   39s
     0     0 24592.0289    0  481 26698.0000 24592.0289  7.89%     -   40s
     0     0 24592.0289    0  481 26698.0000 24592.0289  7.89%     -   43s

## Task 2: Warm-Start vs Cold-Start MILP

The OR-Tools routes were provided to Gurobi as MIP Start solutions.

The objective of this experiment is to evaluate whether supplying an initial feasible solution improves the branch-and-bound search compared to solving the MILP from scratch.

The comparison focuses on:
- Best feasible objective value
- Remaining optimality gap
- Runtime
- Solver status

In [26]:
task2_results = [
    {"Mode":"Cold", **cold_50},
    {"Mode":"Warm", **warm_50},
    {"Mode":"Cold", **cold_100},
    {"Mode":"Warm", **warm_100},
    {"Mode":"Cold", **cold_250},
    {"Mode":"Warm", **warm_250},
]

task2_df = pd.DataFrame(task2_results)

task2_df

   Mode    N  Runtime_sec  Status   ObjVal  ObjBound        Gap
0  Cold   50     1800.196       9  14425.0   14196.0   1.587522
1  Warm   50     1800.115       9  14408.0   14253.0   1.075791
2  Cold  100     1800.286       9  19896.0   18376.0   7.639727
3  Warm  100     1800.086       9  18850.0   18585.0   1.405836
4  Cold  250     1800.602       9  29176.0   25105.0  13.953249
5  Warm  250     1800.213       9  26521.0   25321.0   4.524716

In [27]:
task2_df.to_csv(
    "Task2_WarmStart.csv",
    index=False
)

In [28]:
route_500 = results_task1[4]["Route"]

cold_500 = solve_tsp_gurobi(
    distance_matrix,
    500
)

warm_500 = solve_tsp_gurobi_warm(
    distance_matrix,
    500,
    route_500
)

Set parameter TimeLimit to value 1800

Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 249502 rows, 249999 columns and 1244506 nonzeros (Min)
Model fingerprint: 0xb120642e
Model has 249500 linear objective coefficients
Variable types: 499 continuous, 249500 integer (249500 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+02]
  Objective range  [1e+00, 4e+03]
  Bounds range     [1e+00, 5e+02]
  RHS range        [1e+00, 5e+02]

Presolve time: 3.06s
Presolved: 249502 rows, 249999 columns, 1244506 nonzeros
Variable types: 499 continuous, 249500 integer (249500 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 0.58s

Barrier statistics:
 Dense cols : 499
 AA' NZ     : 1.244e+06
 Factor NZ  : 2.366e+06 (roughly 220 MB of memory)
 Factor Ops : 1.128e+09 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.14839849e+07 -1.71639337e+05  4.69e+02 0.00e+00  6.47e+01     9s
   1   7.03520129e+05 -1.32325478e+05  8.81e+00 9.09e-13  1.15e+00     9s
   2   3.00364447e+05 -4.83659717e+04  4.78e-01 9.09e-13  4.66e-01    10s

Barrier performed 2 iterations in 9.64 seconds (5.42 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 0.07s

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    1986    2.6887189e+04   0.000000e+00   0.000000e+00     10s

Root relaxation: objective 2.688719e+04, 1986 iterations, 3.86 seconds (1.16 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 26887.1890    0  889          - 26887.1890      -     -   13s
H    0     0                    637493.00000 26887.1890  95.8%     -   34s
     0     0 30010.2294    0  938 637493.000 30010.2294  95.3%     -   36s
H    0     0                    628466.00000 30010.3120  95.2%     -   40s
H    0     0                    539625.00000 30010.3120  94.4%     -   43s
H    0     0                    517669.00000 30010.3120  94.2%     -   52s
H    0     0                    509023.00000 30010.3120  94.1%     -   54s
H    0     0                    504514.00000 30010.3120  94.1%     -   55s
H    0     0                    504454.00000 30010.3120  94.1%     -   58s
     0     0 30023.6252    0  940 504454.000 30023.6252  94.0%     -   59s
     0     0 30023.6252    0  940 504454.000 30023.6252  94.0%     -   59s
     0     0 31118.7352    0  937 504454.000 31118.7352  93.8%     -   70s
     0     0 31165.3019    0  940 504454.000 31165.3019  93.8%     -   72s
     0     0 31165.3019    0  936 504454.000 31165.3019  93.8%     -   72s
     0     0 32167.0961    0  944 504454.000 32167.0961  93.6%     -   84s
     0     0 32248.5115    0  945 504454.000 32248.5115  93.6%     -   86s
     0     0 32269.8448    0  938 504454.000 32269.8448  93.6%     -   86s
     0     0 32517.6040    0  951 504454.000 32517.6040  93.6%     -   97s
     0     0 32555.5050    0  946 504454.000 32555.5050  93.5%     -   98s
     0     0 32555.5050    0  949 504454.000 32555.5050  93.5%     -   99s
     0     0 32555.5050    0  954 504454.000 32555.5050  93.5%     -  106s
     0     0 32564.0050    0  954 504454.000 32564.0050  93.5%     -  108s
     0     0 32564.0050    0  954 504454.000 32564.0050  93.5%     -  115s
     0     0 32564.0050    0  954 504454.000 32564.0050  93.5%     -  124s
     0     0 32564.0050    0  928 504454.000 32564.0050  93.5%     -  127s
     0     2 32870.5050    0  928 504454.000 32870.5050  93.5%     -  159s
     1     4 32870.5050    1  922 504454.000 32870.5050  93.5%  12.0  160s
    25    33 32870.5050    6  914 504454.000 32870.5050  93.5%  34.2  165s
    59    65 32870.5050   12  925 504454.000 32870.5050  93.5%  34.8  170s
H   87    91                    460441.00000 32870.5050  92.9%  35.7  174s
    90    96 32870.5050   17  909 460441.000 32870.5050  92.9%  37.3  175s
   111   116 32870.5050   20  893 460441.000 32870.5050  92.9%  40.9  180s
H  117   120                    448343.00000 32870.5050  92.7%  39.6  184s
   119   128 32870.5050   22  895 448343.000 32870.5050  92.7%  39.3  185s
   163   168 32870.5050   28  821 448343.000 32870.5050  92.7%  37.2  191s
   167   172 32920.0485   29  830 448343.000 32870.5050  92.7%  37.3  195s
H  170   172                    441909.00000 32870.5050  92.6%  37.7  195s
   192   209 32940.8501   31  837 441909.000 32870.5050  92.6%  38.5  200s
   232   245 32979.5724   36  831 441909.000 32870.5050  92.6%  36.0  205s
   275   286 32990.1609   42  809 441909.000 32870.5050  92.6%  34.7  211s
   301   317 33061.8415   49  792 441909.000 32870.5050  92.6%  35.9  215s
H  318   321                    441787.00000 32870.5050  92.6%  35.2  220s
H  321   321                    435993.00000 32870.5050  92.5%  34.9  220s
   339   360 33145.7375   58  763 435993.000 32870.5050  92.5%  34.9  225s
   378   391 33196.3184   65  772 435993.000 32870.5050  92.5%  34.5  231s
H  394   395                    435966.00000 32870.5050  92.5%  35.0  233s
H  396   395                    433046.00000 32870.5050  92.4%  34.9  233s
H  397   395                    413401.00000 32870.5050  92.0%  34.9  233s
   398   422 33199.0378   67  780 413401.000 32870.5050  92.0%  34.9  236s
H  426   426                    260660.00000 32870.5050  87.4%  34.3  242s
H  427   426                    256166.00000 32870.5050  87.2%  34.3  242s
   430   447 33325.5899   76  767 256166.000 32870.5050  87.2%  34.2  245s
   471   495 33595.5623   83  768 256166.000 32870.5050  87.2%  35.2  252s
   503   541 33710.8692   90  732 256166.000 32870.5050  87.2%  35.2  257s
   551   575 33718.0603   93  743 256166.000 32870.5050  87.2%  34.9  262s
H  587   579                    256080.00000 32870.5050  87.2%  35.3  267s
H  588   579                    254426.00000 32870.5050  87.1%  35.3  267s
   591   662 33814.7770   97  769 254426.000 32870.5050  87.1%  35.2  272s
   677   740 34884.2920  123  765 254426.000 32870.5050  87.1%  32.4  277s
   766   802 35224.8775  140  764 254426.000 32870.5050  87.1%  30.0  282s
   834   854 35606.7999  164  755 254426.000 32870.5050  87.1%  29.7  287s
   895   913 36054.4659  178  750 254426.000 32870.5050  87.1%  29.6  292s
   964   946 36197.1092  194  691 254426.000 32870.5050  87.1%  28.8  299s
H  976   946                    254408.00000 32870.5050  87.1%  28.7  299s
H  987   946                    250437.00000 32870.5050  86.9%  28.6  299s
   997  1005 36329.4762  205  665 250437.000 32870.5050  86.9%  28.9  304s
  1062  1085 36462.3225  213  669 250437.000 32870.5050  86.9%  28.8  309s
  1154  1144 infeasible  233      250437.000 32870.5050  86.9%  27.6  314s
H 1217  1148                    247902.00000 32870.5050  86.7%  27.5  318s
H 1218  1148                    194073.00000 32870.5050  83.1%  27.6  318s
H 1221  1152                    130695.00000 32870.5050  74.8%  27.6  328s
H 1224  1152                    121718.00000 32870.5050  73.0%  27.7  328s
  1225  1202 36742.9298  249  618 121718.000 32870.5050  73.0%  27.7  333s
  1279  1266 36969.4829  261  602 121718.000 32870.5050  73.0%  27.8  339s
  1347  1332 37262.8536  270  595 121718.000 32870.5050  73.0%  27.9  346s
  1414  1406 37675.7955  295  606 121718.000 32870.5050  73.0%  28.1  353s
  1499  1499 38622.5298  321  621 121718.000 32870.5050  73.0%  28.0  359s
H 1598  1503                    119395.00000 32870.5050  72.5%  27.5  371s
H 1599  1503                    113150.00000 32870.5050  70.9%  27.4  371s
  1602  1580 38747.9866  355  613 113150.000 32870.5050  70.9%  27.4  378s
  1683  1637 40903.5469  372  566 113150.000 32870.5050  70.9%  27.4  384s
  1745  1691 40932.9384  383  570 113150.000 32870.5050  70.9%  27.9  391s
  1812  1784 41634.2771  390  570 113150.000 32870.5050  70.9%  28.3  399s
H 1911  1873                    113079.00000 32870.5050  70.9%  28.1  407s
H 1918  1873                    103876.00000 32870.5050  68.4%  28.4  407s
  2008  1941 41806.8027  406  567 103876.000 32870.5050  68.4%  28.1  415s
  2087  2029 41815.3612  409  567 103876.000 32870.5050  68.4%  28.6  425s
  2175  2119 41927.0132  431  535 103876.000 32870.5050  68.4%  28.9  433s
H 2271  2123                    102925.00000 32870.5050  68.1%  29.1  446s
H 2272  2123                    99606.000000 32870.5050  67.0%  29.1  446s
  2275  2219 42125.9188  438  548 99606.0000 32870.5050  67.0%  29.1  455s
  2381  2317 42143.6119  444  518 99606.0000 32870.5050  67.0%  29.1  465s
  2489  2426 42369.7019  454  546 99606.0000 32870.5050  67.0%  29.3  475s
  2610  2524 43122.8338  471  520 99606.0000 32870.5050  67.0%  29.1  487s
H 2629  2524                    99481.000000 32870.5050  67.0%  29.2  487s
H 2723  2528                    74645.000000 32870.5050  56.0%  28.9  503s
  2727  2674 44000.4812  486  515 74645.0000 32870.5050  56.0%  28.9  515s
H 2884  2678                    72733.000000 32870.5050  54.8%  28.6  530s
H 2886  2678                    70946.000000 32870.5050  53.7%  28.6  530s
  2888  2841 44164.6992  505  456 70946.0000 32870.5050  53.7%  28.6  541s
  3058  3022 44180.8258  519  440 70946.0000 32870.5050  53.7%  28.0  553s
  3252  3218 44257.8890  534  407 70946.0000 32870.5050  53.7%  27.2  569s
  3463  3394 44297.5134  557  416 70946.0000 32870.5050  53.7%  26.5  584s
  3557  3394 44340.8018  711  399 70946.0000 32870.5050  53.7%  26.3  585s
  3664  3578 44410.7626  584  397 70946.0000 32870.5050  53.7%  26.0  598s
H 3856  3747                    70901.000000 32870.5050  53.6%  25.7  614s
H 3933  3747                    70849.000000 32870.5050  53.6%  25.8  614s
H 4035  3751                    70696.000000 32870.5050  53.5%  25.5  635s
H 4036  3751                    70301.000000 32870.5050  53.2%  25.5  635s
H 4038  3751                    67478.000000 32870.5050  51.3%  25.5  635s
  4039  3961 44561.3392  664  378 67478.0000 32870.5050  51.3%  25.5  652s
  4253  4164 45418.5147  702  395 67478.0000 32870.5050  51.3%  25.2  669s
  4458  4405 45599.0046  760  375 67478.0000 32870.5050  51.3%  25.4  686s
  4701  4653 45674.0437  820  396 67478.0000 32870.5050  51.3%  25.1  703s
  4950  4867 46616.2300  882  363 67478.0000 32870.5050  51.3%  24.9  723s
H 5041  4867                    67421.000000 32870.5050  51.2%  24.8  723s
H 5104  4867                    67420.000000 32870.5050  51.2%  24.9  723s
  5168  4868 38637.9961  353  928 67420.0000 32870.5050  51.2%  24.8  841s
H 5169  4625                    56236.000000 32870.5050  41.5%  24.8  884s
H 5169  4394                    52954.000000 32870.5050  37.9%  24.8  896s
H 5169  4174                    44206.000000 32870.5050  25.6%  24.8  919s
  5170  4174 35516.0395  186  882 44206.0000 32870.5050  25.6%  24.8  985s
H 5170  3965                    42819.000000 32870.5050  23.2%  24.8 1095s
  5171  3966 33078.5082   52  927 42819.0000 32870.5050  23.2%  24.8 1300s
H 5171  3768                    41895.000000 32870.5050  21.5%  24.8 1308s
  5173  3769 32898.3983    8  944 41895.0000 32898.3983  21.5%  24.8 1395s
  5174  3770 36746.1869  255  922 41895.0000 33030.7770  21.2%  24.8 1483s
  5175  3771 41895.0000  804  952 41895.0000 33099.7605  21.0%  24.8 1535s
  5176  3771 41895.0000  999  971 41895.0000 33115.6302  21.0%  24.8 1540s
  5178  3773 41895.0000  910  974 41895.0000 33118.1206  20.9%  24.8 1604s
  5179  3773 36745.0169  249  951 41895.0000 33352.1010  20.4%  24.8 1673s
  5180  3774 41895.0000  860  946 41895.0000 33369.1673  20.4%  24.8 1708s
  5181  3775 41895.0000  605  954 41895.0000 33369.6048  20.3%  24.8 1792s

Cutting planes:
  Learned: 40
  Gomory: 69
  Cover: 4
  Implied bound: 28
  Projected implied bound: 3
  MIR: 149
  Mixing: 11
  Knapsack: 2
  Flow cover: 1124
  GUB cover: 1
  Zero half: 63
  RLT: 9
  Relax-and-lift: 10

Explored 5181 nodes (144980 simplex iterations) in 1802.95 seconds (969.17 work units)
Thread count was 8 (of 8 available processors)

Solution count 10: 41895 42819 44206 ... 70696

Time limit reached
Best objective 4.189500000000e+04, best bound 3.340900000000e+04, gap 20.2554%
Set parameter TimeLimit to value 1800
Starting optimization...
Solver runtime: 2.384185791015625e-07
Gurobi runtime: 0.0
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 249502 rows, 249999 columns and 1244506 nonzeros (Min)
Model fingerprint: 0x8f709b45
Model has 249500 linear objective coefficients
Variable types: 499 continuous, 249500 integer (249500 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+02]
  Objective range  [1e+00, 4e+03]
  Bounds range     [1e+00, 5e+02]
  RHS range        [1e+00, 5e+02]

Loaded user MIP start with objective 37015

Presolve time: 2.53s
Presolved: 249502 rows, 249999 columns, 1244506 nonzeros
Variable types: 499 continuous, 249500 integer (249500 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 0.31s

Barrier statistics:
 Dense cols : 499
 AA' NZ     : 1.244e+06
 Factor NZ  : 2.366e+06 (roughly 220 MB of memory)
 Factor Ops : 1.128e+09 (less than 1 second per iteration)
 Threads    : 2

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.14839849e+07 -1.71639337e+05  4.69e+02 0.00e+00  6.47e+01     5s
   1   7.03520129e+05 -1.32325478e+05  8.81e+00 9.09e-13  1.15e+00     6s
   2   3.00364447e+05 -4.83659717e+04  4.78e-01 9.09e-13  4.66e-01     6s
   3   9.95327129e+04 -1.92273344e+04  9.73e-04 9.09e-13  1.59e-01     6s

Barrier performed 3 iterations in 6.17 seconds (4.84 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 0.18s

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    1986    2.6887189e+04   0.000000e+00   0.000000e+00      6s

Root relaxation: objective 2.688719e+04, 1986 iterations, 2.88 seconds (1.16 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 26887.1890    0  889 37015.0000 26887.1890  27.4%     -    8s
     0     0 30010.2294    0  938 37015.0000 30010.2294  18.9%     -   31s
H    0     0                    36964.000000 30010.3434  18.8%     -   37s
     0     0 30023.6252    0  937 36964.0000 30023.6252  18.8%     -   57s
     0     0 30023.6252    0  937 36964.0000 30023.6252  18.8%     -   57s
     0     0 30653.6613    0  944 36964.0000 30653.6613  17.1%     -   68s
     0     0 30664.1583    0  913 36964.0000 30664.1583  17.0%     -   70s
     0     0 30664.1681    0  915 36964.0000 30664.1681  17.0%     -   71s
     0     0 32045.6593    0  976 36964.0000 32045.6593  13.3%     -   84s
     0     0 32209.8417    0  976 36964.0000 32209.8417  12.9%     -   85s
     0     0 32231.1757    0  973 36964.0000 32231.1757  12.8%     -   86s
     0     0 32231.1757    0  973 36964.0000 32231.1757  12.8%     -   86s
     0     0 32500.1684    0  960 36964.0000 32500.1684  12.1%     -   97s
     0     0 32534.5099    0  957 36964.0000 32534.5099  12.0%     -   98s
     0     0 32534.5099    0  957 36964.0000 32534.5099  12.0%     -   99s
     0     0 32534.5219    0  957 36964.0000 32534.5219  12.0%     -  107s
     0     0 32550.0219    0  957 36964.0000 32550.0219  11.9%     -  108s
     0     0 32550.0219    0  960 36964.0000 32550.0219  11.9%     -  116s
     0     0 32550.0219    0  960 36964.0000 32550.0219  11.9%     -  118s
     0     0 32552.9758    0  957 36964.0000 32552.9758  11.9%     -  125s
     0     0 32572.4415    0  957 36964.0000 32572.4415  11.9%     -  127s
     0     0 32572.4415    0  957 36964.0000 32572.4415  11.9%     -  135s
     0     0 32572.4415    0  957 36964.0000 32572.4415  11.9%     -  143s
     0     0 32572.4415    0  929 36964.0000 32572.4415  11.9%     -  146s
     0     0 32572.4415    0  929 36964.0000 32572.4415  11.9%     -  147s
     0     0 32572.4415    0  929 36964.0000 32572.4415  11.9%     -  155s
     0     0 32572.4415    0  929 36964.0000 32572.4415  11.9%     -  156s
     0     0 32572.4415    0  929 36964.0000 32572.4415  11.9%     -  161s
     0     0 32572.4415    0  929 36964.0000 32572.4415  11.9%     -  162s
H    0     0                    36844.000000 32572.4415  11.6%     -  191s
     0     2 32867.2258    0  929 36844.0000 32867.2258  10.8%     -  194s
     3     8 32867.2258    2  917 36844.0000 32867.2258  10.8%  41.7  195s
    36    43 32867.2258    8  892 36844.0000 32867.2258  10.8%  24.5  200s
    67    74 32867.2258   11  913 36844.0000 32867.2258  10.8%  30.9  205s
    90    97 32867.2258   15  891 36844.0000 32867.2258  10.8%  35.2  210s
   125   132 32902.7186   22  893 36844.0000 32867.2258  10.8%  37.5  215s
   166   173 33001.2426   30  864 36844.0000 32867.2258  10.8%  37.6  220s
   203   211 33041.3694   40  888 36844.0000 32867.2258  10.8%  37.8  226s
   226   235 33058.4220   44  870 36844.0000 32867.2258  10.8%  37.9  231s
   267   276 33529.3019   54  872 36844.0000 32867.2258  10.8%  39.1  236s
   298   304 34198.5978   62  865 36844.0000 32867.2258  10.8%  38.1  241s
   328   328 34266.8416   65  859 36844.0000 32867.2258  10.8%  38.1  245s
   360   363 34293.6628   69  826 36844.0000 32867.2258  10.8%  37.9  250s
   395   404 34543.5015   80  830 36844.0000 32867.2258  10.8%  37.0  255s
   446   505 34548.3768   89  860 36844.0000 32867.2258  10.8%  34.6  261s
   524   571 34559.2165  108  860 36844.0000 32867.2258  10.8%  30.6  265s
   655   699 34569.7451  141  846 36844.0000 32867.2258  10.8%  26.3  272s
   721   758 34572.2942  160  834 36844.0000 32867.2258  10.8%  24.7  276s
   782   799 34587.4440  176  834 36844.0000 32867.2258  10.8%  23.5  280s
   888   897 34825.7278  211  857 36844.0000 32867.2258  10.8%  22.8  287s
   942   950 34827.9669  230  844 36844.0000 32867.2258  10.8%  22.4  291s
   996  1004 34901.8547  245  828 36844.0000 32867.2258  10.8%  22.0  295s
  1138  1113 34911.0862  289  824 36844.0000 32867.2258  10.8%  20.7  303s
  1187  1173 34946.9233  294  806 36844.0000 32867.2258  10.8%  20.8  308s
  1254  1221 35139.9976  310  801 36844.0000 32867.2258  10.8%  20.6  312s
  1314  1276 35145.8092  326  789 36844.0000 32867.2258  10.8%  20.7  318s
  1371  1332 35147.0209  344  750 36844.0000 32867.2258  10.8%  21.2  324s
  1431  1367 35148.8879  360  787 36844.0000 32867.2258  10.8%  21.2  329s
  1480  1401 33021.2288   34  855 36844.0000 32867.2258  10.8%  21.6  334s
  1515  1470 33173.1051   38  863 36844.0000 32867.2258  10.8%  22.2  340s
  1588  1547 33222.0020   46  853 36844.0000 32867.2258  10.8%  22.2  345s
  1667  1632 33374.5762   59  879 36844.0000 32867.2258  10.8%  21.9  351s
  1758  1756 33582.0437   72  820 36844.0000 32867.2258  10.8%  21.5  357s
  1893  1882 33592.8039  119  829 36844.0000 32867.2258  10.8%  20.6  364s
  2032  1975 33616.6036  166  830 36844.0000 32867.2258  10.8%  19.9  371s
  2137  2025 35327.8114  198  820 36844.0000 32867.2258  10.8%  19.6  378s

In [29]:
print(cold_500)
print(warm_500)

{'N': 500, 'Runtime_sec': 1802.970999956131, 'Status': 9, 'ObjVal': 41895.0, 'ObjBound': 33409.0, 'Gap': 20.255400405776346}
{'N': 500, 'ObjVal': 36331.0, 'ObjBound': 33251.0, 'Gap': 8.477608653766755, 'Runtime_sec': 1801.0409998893738, 'Status': 9}

In [30]:
comparison_500 = pd.DataFrame(
    [
        {"Mode":"Cold", **cold_500},
        {"Mode":"Warm", **warm_500}
    ]
)

comparison_500

   Mode    N  Runtime_sec  Status   ObjVal  ObjBound        Gap
0  Cold  500     1802.971       9  41895.0   33409.0  20.255400
1  Warm  500     1801.041       9  36331.0   33251.0   8.477609

### Observations

- Warm-start consistently produced better incumbent solutions than the cold-start model.
- The MIP gap decreased significantly after providing an initial feasible solution.
- The improvement became more noticeable for larger problem instances.
- Both approaches reached the specified time limit for larger instances, but warm-starting produced higher-quality solutions within the same computational budget.

In [31]:
route_1000 = results_task1[5]["Route"]

cold_1000 = solve_tsp_gurobi(
    distance_matrix,
    1000
)

warm_1000 = solve_tsp_gurobi_warm(
    distance_matrix,
    1000,
    route_1000
)

print(cold_1000)
print(warm_1000)

Set parameter TimeLimit to value 1800
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 999002 rows, 999999 columns and 4989006 nonzeros (Min)
Model fingerprint: 0x1ccd8ff8
Model has 999000 linear objective coefficients
Variable types: 999 continuous, 999000 integer (999000 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+03]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Presolve removed 0 rows and 0 columns (presolve time = 5s)...
Presolve removed 0 rows and 0 columns (presolve time = 10s)...
Presolve time: 12.16s
Presolved: 999002 rows, 999999 columns, 4989006 nonzeros
Variable types: 999 continuous, 999000 integer (999000 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 1.87s

Barrier statistics:
 Dense cols : 999
 AA' NZ     : 4.987e+06
 Factor NZ  : 9.482e+06 (roughly 900 MB of memory)
 Factor Ops : 9.012e+09 (roughly 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.18116987e+07 -2.51598587e+05  6.87e+02 0.00e+00  4.53e+01    37s
   1   1.45709157e+06 -2.31326423e+05  1.07e+01 9.09e-13  5.80e-01    38s
   2   6.02277980e+05 -1.18253119e+05  7.20e-01 9.09e-13  2.41e-01    40s
   3   2.00926791e+05 -5.35774606e+04  1.65e-02 9.09e-13  8.49e-02    42s
   4   7.04179047e+04  1.69359246e+04  5.49e-05 9.09e-13  1.78e-02    44s
   5   4.43214427e+04  3.53685900e+04  2.09e-08 9.09e-13  2.99e-03    46s

Barrier performed 5 iterations in 45.93 seconds (25.14 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 0.27s

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4167    3.9151872e+04   0.000000e+00   0.000000e+00     46s

Root relaxation: objective 3.915187e+04, 4167 iterations, 20.66 seconds (5.78 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 39151.8724    0 1757          - 39151.8724      -     -   57s
     0     0 42687.4201    0 1981          - 42687.4201      -     -  216s
     0     0 42716.0201    0 1975          - 42716.0201      -     -  371s
     0     0 42716.0201    0 1976          - 42716.0201      -     -  373s
H    0     0                    1288614.0000 42716.0201  96.7%     -  430s
     0     0 43764.4758    0 1996 1288614.00 43764.4758  96.6%     -  444s
     0     0 43775.2617    0 1961 1288614.00 43775.2617  96.6%     -  454s
     0     0 43775.2617    0 1966 1288614.00 43775.2617  96.6%     -  456s
     0     0 44922.8096    0 1968 1288614.00 44922.8096  96.5%     -  537s
     0     0 44926.1732    0 1965 1288614.00 44926.1732  96.5%     -  545s
     0     0 44926.1732    0 1965 1288614.00 44926.1732  96.5%     -  546s
     0     0 45034.9632    0 1960 1288614.00 45034.9632  96.5%     -  608s
     0     0 45038.2921    0 1958 1288614.00 45038.2921  96.5%     -  615s
     0     0 45038.2921    0 1958 1288614.00 45038.2921  96.5%     -  617s
     0     0 45038.2921    0 1958 1288614.00 45038.2921  96.5%     -  658s
     0     0 45038.9587    0 1958 1288614.00 45038.9587  96.5%     -  666s
     0     0 45038.9587    0 1958 1288614.00 45038.9587  96.5%     -  707s
     0     0 45038.9587    0 1958 1288614.00 45038.9587  96.5%     -  714s
     0     0 45038.9587    0 1958 1288614.00 45038.9587  96.5%     -  756s
     0     0 45038.9587    0 1898 1288614.00 45038.9587  96.5%     -  769s
     0     0 45038.9587    0 1922 1288614.00 45038.9587  96.5%     -  776s
     0     0 45038.9587    0 1925 1288614.00 45038.9587  96.5%     -  819s
     0     0 45038.9587    0 1885 1288614.00 45038.9587  96.5%     -  830s
     0     0 45051.9459    0 1897 1288614.00 45051.9459  96.5%     -  837s
     0     0 45051.9459    0 1903 1288614.00 45051.9459  96.5%     -  882s
     0     0 45051.9459    0 1875 1288614.00 45051.9459  96.5%     -  893s
     0     0 45051.9459    0 1875 1288614.00 45051.9459  96.5%     -  898s
     0     0 45051.9459    0 1875 1288614.00 45051.9459  96.5%     -  904s
     0     2 45389.2459    0 1875 1288614.00 45389.2459  96.5%     - 1050s
     3     8 45389.2459    2 1889 1288614.00 45389.2459  96.5%  77.7 1059s
     7    12 45389.2459    3 1892 1288614.00 45389.2459  96.5%   113 1063s
    11    20 45389.2459    4 1894 1288614.00 45389.2459  96.5%  92.2 1071s
    19    25 45389.2459    5 1892 1288614.00 45389.2459  96.5%  68.5 1079s
H   24    30                    1143129.0000 45389.2459  96.0%  81.8 1088s
    29    36 45389.2459    7 1890 1143129.00 45389.2459  96.0%  82.3 1095s
    35    41 45389.2459    8 1882 1143129.00 45389.2459  96.0%  79.9 1106s
    40    45 45389.2459   10 1829 1143129.00 45389.2459  96.0%  98.5 1118s
    44    49 45389.2459   10 1847 1143129.00 45389.2459  96.0%   110 1129s
    48    53 45389.2459   11 1842 1143129.00 45389.2459  96.0%   117 1153s
H   49    53                    771534.00000 45389.2459  94.1%   115 1153s
    52    57 45389.2459   12 1842 771534.000 45389.2459  94.1%   118 1162s
H   54    57                    771521.00000 45389.2459  94.1%   120 1163s
H   55    57                    768495.00000 45389.2459  94.1%   118 1163s
    56    64 45389.2459   13 1837 768495.000 45389.2459  94.1%   117 1176s
    63    74 45389.2459   15 1795 768495.000 45389.2459  94.1%   126 1192s
    73    83 45389.2459   17 1830 768495.000 45389.2459  94.1%   113 1201s
    82    87 45389.2459   18 1839 768495.000 45389.2459  94.1%   111 1210s
    86    91 45389.2459   19 1816 768495.000 45389.2459  94.1%   111 1219s
H   90    95                    688704.00000 45389.2459  93.4%   109 1242s
    94    99 45389.2459   20 1814 688704.000 45389.2459  93.4%   110 1252s
    98   105 45389.2459   20 1808 688704.000 45389.2459  93.4%   109 1280s
H  101   105                    513667.00000 45389.2459  91.2%   108 1280s
   104   114 45389.2459   22 1821 513667.000 45389.2459  91.2%   110 1293s
   113   126 45389.2459   22 1815 513667.000 45389.2459  91.2%   104 1303s
   125   138 45389.2459   23 1819 513667.000 45389.2459  91.2%  98.0 1311s
   137   148 45389.2459   25 1843 513667.000 45389.2459  91.2%  90.8 1319s

Cutting planes:
  Learned: 52
  Gomory: 37
  Lift-and-project: 1
  Cover: 1
  Implied bound: 193
  MIR: 355
  Knapsack: 19
  RLT: 225
  Relax-and-lift: 116
  BQP: 4
  PSD: 20
H  147   112                    475165.00000 45389.2459  90.4%  87.6 1340s

Explored 147 nodes (30614 simplex iterations) in 1340.77 seconds (632.78 work units)
Thread count was 8 (of 8 available processors)

Solution count 1: 513667

Solve interrupted (error code 10001)
Best objective 5.136670000000e+05, best bound 4.539000000000e+04, gap 91.1635%

GurobiError: Out of memory

In [32]:
warm_1000 = solve_tsp_gurobi_warm(
    distance_matrix,
    1000,
    route_1000
)

print(cold_1000)
print(warm_1000)

Set parameter TimeLimit to value 1800
Starting optimization...
Solver runtime: 2.384185791015625e-07
Gurobi runtime: 0.0
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  1800

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 999002 rows, 999999 columns and 4989006 nonzeros (Min)
Model fingerprint: 0x0f4cd146
Model has 999000 linear objective coefficients
Variable types: 999 continuous, 999000 integer (999000 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 4e+03]
  Bounds range     [1e+00, 1e+03]
  RHS range        [1e+00, 1e+03]

Loaded user MIP start with objective 52374

Presolve removed 0 rows and 0 columns (presolve time = 5s)...
Presolve removed 0 rows and 0 columns (presolve time = 10s)...
Presolve time: 14.61s
Presolved: 999002 rows, 999999 columns, 4989006 nonzeros
Variable types: 999 continuous, 999000 integer (999000 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 1.92s

Barrier statistics:
 Dense cols : 999
 AA' NZ     : 4.987e+06
 Factor NZ  : 9.482e+06 (roughly 900 MB of memory)
 Factor Ops : 9.012e+09 (less than 1 second per iteration)
 Threads    : 2

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.18116987e+07 -2.51598587e+05  6.87e+02 0.00e+00  4.53e+01    31s
   1   1.45709157e+06 -2.31326423e+05  1.07e+01 9.09e-13  5.80e-01    32s
   2   6.02277980e+05 -1.18253119e+05  7.20e-01 9.09e-13  2.41e-01    34s
   3   2.00926791e+05 -5.35774606e+04  1.65e-02 6.82e-13  8.49e-02    35s
   4   7.04179047e+04  1.69359246e+04  5.49e-05 6.82e-13  1.78e-02    37s
   5   4.43214427e+04  3.53685900e+04  2.09e-08 9.09e-13  2.99e-03    39s
   6   3.97473620e+04  3.84070767e+04  5.99e-10 9.09e-13  4.47e-04    40s

Barrier performed 6 iterations in 40.30 seconds (22.41 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 0.22s

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    4167    3.9151872e+04   0.000000e+00   0.000000e+00     41s

Root relaxation: objective 3.915187e+04, 4167 iterations, 19.73 seconds (5.78 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 39151.8724    0 1757 52374.0000 39151.8724  25.2%     -   49s
H    0     0                    52123.000000 39151.8724  24.9%     -   66s
H    0     0                    51995.000000 39151.8724  24.7%     -   80s
     0     0 42687.4201    0 2001 51995.0000 42687.4201  17.9%     -  166s
H    0     0                    51957.000000 42716.0201  17.8%     -  188s
H    0     0                    51759.000000 42716.0201  17.5%     -  203s
H    0     0                    51296.000000 42716.0201  16.7%     -  290s
     0     0 42716.0201    0 1987 51296.0000 42716.0201  16.7%     -  299s
     0     0 42716.0201    0 1988 51296.0000 42716.0201  16.7%     -  301s
     0     0 43757.6766    0 1952 51296.0000 43757.6766  14.7%     -  368s
     0     0 43762.1758    0 1936 51296.0000 43762.1758  14.7%     -  376s
     0     0 43762.1758    0 1936 51296.0000 43762.1758  14.7%     -  378s
     0     0 44904.6014    0 1924 51296.0000 44904.6014  12.5%     -  460s
     0     0 44916.7252    0 1931 51296.0000 44916.7252  12.4%     -  468s
     0     0 44919.3919    0 1933 51296.0000 44919.3919  12.4%     -  470s
     0     0 45044.1655    0 1951 51296.0000 45044.1655  12.2%     -  530s
     0     0 45044.8321    0 1951 51296.0000 45044.8321  12.2%     -  538s
     0     0 45044.8321    0 1949 51296.0000 45044.8321  12.2%     -  579s
     0     0 45044.8321    0 1948 51296.0000 45044.8321  12.2%     -  587s
     0     0 45044.8321    0 1948 51296.0000 45044.8321  12.2%     -  629s
     0     0 45046.0425    0 1948 51296.0000 45046.0425  12.2%     -  636s
     0     0 45046.0425    0 1951 51296.0000 45046.0425  12.2%     -  678s
     0     0 45046.0425    0 1905 51296.0000 45046.0425  12.2%     -  690s
     0     0 45052.1685    0 1909 51296.0000 45052.1685  12.2%     -  701s
     0     0 45052.1685    0 1919 51296.0000 45052.1685  12.2%     -  744s
     0     0 45052.1685    0 1919 51296.0000 45052.1685  12.2%     -  751s
     0     0 45052.1685    0 1919 51296.0000 45052.1685  12.2%     -  795s
     0     0 45052.1685    0 1919 51296.0000 45052.1685  12.2%     -  799s
     0     0 45052.1685    0 1904 51296.0000 45052.1685  12.2%     -  809s
     0     2 45397.2266    0 1900 51296.0000 45397.2266  11.5%     -  956s
     3     8 45397.2266    2 1904 51296.0000 45397.2266  11.5%  60.7  966s
     7    12 45397.2266    3 1901 51296.0000 45397.2266  11.5%   106  971s
    11    19 45397.2266    4 1879 51296.0000 45397.2266  11.5%  91.7  980s
    18    27 45397.2266    6 1836 51296.0000 45397.2266  11.5%  83.7  987s
    26    31 45397.2266    7 1830 51296.0000 45397.2266  11.5%  83.0  997s
    30    39 45397.2266    8 1830 51296.0000 45397.2266  11.5%  96.2 1003s
    38    47 45397.2266    9 1824 51296.0000 45397.2266  11.5%  83.5 1008s
    46    53 45397.2266   10 1838 51296.0000 45397.2266  11.5%  74.8 1012s
    52    61 45397.2266   11 1836 51296.0000 45397.2266  11.5%  70.3 1017s
    60    67 45397.2266   13 1820 51296.0000 45397.2266  11.5%  64.9 1022s
    66    74 45397.2266   15 1805 51296.0000 45397.2266  11.5%  61.7 1029s
    73    79 45397.2266   16 1812 51296.0000 45397.2266  11.5%  62.7 1037s
    78    85 45397.2266   17 1815 51296.0000 45397.2266  11.5%  64.2 1041s
    84    90 45397.2266   17 1811 51296.0000 45397.2266  11.5%  60.8 1047s
    89    94 45397.2266   18 1802 51296.0000 45397.2266  11.5%  62.6 1054s
    93    99 45397.2266   19 1798 51296.0000 45397.2266  11.5%  63.5 1060s
    98   104 45397.2266   20 1795 51296.0000 45397.2266  11.5%  64.8 1068s

Cutting planes:
  Learned: 53
  Gomory: 35
  Lift-and-project: 2
  Cover: 1
  Implied bound: 175
  MIR: 354
  Knapsack: 17
  RLT: 231
  Relax-and-lift: 144
  BQP: 4
  PSD: 20

Explored 103 nodes (21514 simplex iterations) in 1074.47 seconds (471.55 work units)
Thread count was 8 (of 8 available processors)

Solution count 2: 51296

Solve interrupted (error code 10001)
Best objective 5.129600000000e+04, best bound 4.539800000000e+04, gap 11.4980%

GurobiError: Out of memory

In [33]:
comparison_1000 = pd.DataFrame(
    [
        {"Mode":"Cold", **cold_1000},
        {"Mode":"Warm", **warm_1000}
    ]
)

comparison_1000

NameError: name 'cold_1000' is not defined

# K-Nearest Neighbour (KNN) Sparsification

The complete MILP model contains an edge between every pair of cities, resulting in a very large number of decision variables and constraints for large problem instances.

To improve computational efficiency, a **K-Nearest Neighbour (KNN) sparsification** strategy is adopted.

### Approach
- For each city, only the **K nearest neighbouring cities** are retained as candidate edges.
- All other edges are removed from the optimization model.
- The resulting graph is symmetrized to preserve connectivity.

### Objective
Reduce:
- Number of binary variables
- Number of constraints
- Memory consumption
- Solver runtime

Different values of **K** are evaluated to study the trade-off between computational efficiency and solution quality. As K increases, the solution quality generally improves, while the computational cost also increases.

In [34]:
import numpy as np

def create_knn_arcs(distance_matrix, N, K):

    city_names = distance_matrix.index[:N]

    D = distance_matrix.loc[
        city_names,
        city_names
    ]

    arcs = set()

    for i in range(N):

        distances = D.iloc[i].values

        nearest = np.argsort(
            distances
        )[1:K+1]

        for j in nearest:

            arcs.add((i,j))

            # Symmetrize
            arcs.add((j,i))

    return arcs

In [35]:
for K in [10,20,50]:

    arcs = create_knn_arcs(
        distance_matrix,
        500,
        K
    )

    print(
        f"K={K}, Arcs={len(arcs)}"
    )

K=10, Arcs=6146
K=20, Arcs=12316
K=50, Arcs=30862

In [36]:
def solve_tsp_knn(
    distance_matrix,
    N,
    K,
    timelimit=1800
):

    import gurobipy as gp
    from gurobipy import GRB

    city_names = distance_matrix.index[:N]

    D = distance_matrix.loc[
        city_names,
        city_names
    ].values

    arcs = create_knn_arcs(
        distance_matrix,
        N,
        K
    )

    model = gp.Model(
        f"TSP_KNN_{N}_{K}"
    )

    model.setParam(
        "TimeLimit",
        timelimit
    )

    # -----------------
    # Variables
    # -----------------

    x = {}

    for i,j in arcs:

        x[i,j] = model.addVar(
            vtype=GRB.BINARY,
            name=f"x_{i}_{j}"
        )

    u = {}

    for i in range(1,N):

        u[i] = model.addVar(
            lb=1,
            ub=N-1,
            name=f"u_{i}"
        )

    model.update()

    # -----------------
    # Objective
    # -----------------

    model.setObjective(

        gp.quicksum(
            D[i,j] * x[i,j]
            for i,j in arcs
        ),

        GRB.MINIMIZE

    )

    # -----------------
    # Outgoing
    # -----------------

    for i in range(N):

        outgoing = [
            x[i,j]
            for (a,j) in arcs
            if a == i
        ]

        if outgoing:

            model.addConstr(
                gp.quicksum(
                    outgoing
                ) == 1
            )

    # -----------------
    # Incoming
    # -----------------

    for j in range(N):

        incoming = [
            x[i,j]
            for (i,b) in arcs
            if b == j
        ]

        if incoming:

            model.addConstr(
                gp.quicksum(
                    incoming
                ) == 1
            )

    # -----------------
    # MTZ
    # -----------------

    for i,j in arcs:

        if i != 0 and j != 0:

            model.addConstr(

                u[i]
                - u[j]
                + N*x[i,j]
                <= N-1

            )

    # -----------------
    # Solve
    # -----------------

    model.optimize()

    result = {

        "N": N,
        "K": K,
        "Arcs": len(arcs),
        "Status": model.Status,
        "Runtime_sec": model.Runtime,
        "ObjVal": None,
        "ObjBound": None,
        "Gap": None

    }

    if model.SolCount > 0:

        result["ObjVal"] = model.ObjVal
        result["ObjBound"] = model.ObjBound
        result["Gap"] = model.MIPGap * 100

    return result

In [37]:
knn10 = solve_tsp_knn(
    distance_matrix,
    500,
    10,
    timelimit=900
)

print(knn10)

Set parameter TimeLimit to value 900
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  900

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 7124 rows, 6645 columns and 30664 nonzeros (Min)
Model fingerprint: 0xa8e7fbae
Model has 6146 linear objective coefficients
Variable types: 499 continuous, 6146 integer (6146 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+02]
  Objective range  [1e+00, 7e+02]
  Bounds range     [1e+00, 5e+02]
  RHS range        [1e+00, 5e+02]

Presolve time: 0.33s
Presolved: 7124 rows, 6645 columns, 61331 nonzeros
Variable types: 499 continuous, 6146 integer (6146 binary)

Root relaxation: objective 2.688721e+04, 2085 iterations, 0.09 seconds (0.03 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 26887.2120    0  886          - 26887.2120      -     -    0s
     0     0 32478.8653    0  970          - 32478.8653      -     -    1s
     0     0 32538.3386    0  969          - 32538.3386      -     -    1s
     0     0 32538.3386    0  967          - 32538.3386      -     -    1s
     0     0 32857.0766    0 1003          - 32857.0766      -     -    2s
     0     0 32902.5448    0 1021          - 32902.5448      -     -    2s
     0     0 32908.9311    0 1027          - 32908.9311      -     -    2s
     0     0 32908.9311    0 1025          - 32908.9311      -     -    2s
     0     0 33023.7214    0  996          - 33023.7214      -     -    3s
     0     0 33038.4707    0 1014          - 33038.4707      -     -    3s
     0     0 33049.0886    0 1018          - 33049.0886      -     -    3s
     0     0 33049.1209    0 1019          - 33049.1209      -     -    3s
     0     0 33165.3434    0 1014          - 33165.3434      -     -    4s
     0     0 33212.0470    0 1019          - 33212.0470      -     -    4s
     0     0 33212.3775    0 1008          - 33212.3775      -     -    4s
     0     0 33222.1103    0 1011          - 33222.1103      -     -    4s
     0     0 33247.5104    0 1018          - 33247.5104      -     -    4s
     0     0 33247.9232    0 1015          - 33247.9232      -     -    4s
     0     0 33326.5934    0 1029          - 33326.5934      -     -    5s
     0     0 33333.0934    0  989          - 33333.0934      -     -    5s
     0     0 33333.0934    0  980          - 33333.0934      -     -    5s
     0     0 33357.6320    0  978          - 33357.6320      -     -    5s
     0     0 33366.8017    0  973          - 33366.8017      -     -    5s
     0     0 33366.8017    0  973          - 33366.8017      -     -    5s
     0     0 33373.7607    0  972          - 33373.7607      -     -    5s
     0     0 33374.4501    0  972          - 33374.4501      -     -    5s
     0     0 33385.1835    0  987          - 33385.1835      -     -    6s
     0     0 33389.8710    0  997          - 33389.8710      -     -    6s
     0     0 33389.8710    0 1002          - 33389.8710      -     -    6s
     0     0 33390.4331    0 1002          - 33390.4331      -     -    6s
     0     0 33390.4331    0  976          - 33390.4331      -     -    6s
     0     2 33415.2286    0  972          - 33415.2286      -     -    7s
    94   104 33692.4213   23  723          - 33540.6344      -  93.0   10s
   221   233 34828.2156   87  770          - 33540.6344      -  76.0   15s
   998  1011 35220.5108  130  616          - 33554.4870      -  47.9   20s
  1104  1021 34685.0585  116  780          - 33861.9414      -  46.3   25s
  1117  1029 34081.8685   39 1087          - 34081.8685      -  45.7   30s
  1127  1036 34847.5935   97 1114          - 34136.8586      -  45.3   35s
  1135  1041 34601.1000  110 1136          - 34169.9210      -  45.0   40s
  1144  1047 34188.4972   41 1083          - 34188.4972      -  44.6   47s
  1149  1051 35503.1174  153 1113          - 34217.8187      -  44.4   50s
  1170  1066 34236.4241   29  933          - 34236.4241      -  72.0   55s
  1181  1074 34640.2174   98 1131          - 34256.8159      -  71.4   60s
  1189  1079 34275.2000   12 1149          - 34275.2000      -  70.9   65s
  1194  1082 35459.0594  129 1135          - 34285.1657      -  70.6   71s
  1201  1092 34289.5561   21 1058          - 34289.2062      -  85.2   75s
  1470  1279 34544.4004   42  912          - 34289.2062      -  97.2   80s
  1783  1433 35718.6920   91  748          - 34289.2062      -  94.1   85s
  1983  1578 36041.1639  114  614          - 34289.2062      -  93.5   90s
  2607  2032 37184.2324  193  412          - 34289.2062      -  84.1   95s
  3317  2525 38130.1070  285  396          - 34289.2062      -  78.2  100s
  4455  3193 42034.5273  454  188          - 34289.2062      -  65.9  105s
  5172  3741 34556.6464   58  785          - 34289.2062      -  62.2  110s
  5277  3866 34571.9319   65  597          - 34289.2062      -  61.8  115s
  5804  4364 36423.0926  118  411          - 34290.0994      -  61.2  120s
  6377  4964 37025.5024  180  455          - 34290.1888      -  60.8  125s
  7362  5899 40444.0327  324  199          - 34290.3356      -  58.6  131s
  8207  6794 41469.8024  397   90          - 34290.3356      -  55.3  135s
  9992  8172 infeasible  576               - 34290.3356      -  50.2  141s
 11616  9608 34357.4132   43  834          - 34290.3356      -  46.3  145s
H12196  9558                    42143.000000 34290.9629  18.6%  45.3  147s
 12685  9757 34402.9720   62  809 42143.0000 34290.9629  18.6%  45.4  151s
H12792  9689                    42078.000000 34290.9629  18.5%  45.5  151s
H12805  9613                    42055.000000 34290.9629  18.5%  45.6  151s
H13328  9625                    41728.000000 34290.9629  17.8%  45.4  155s
H13347  9061                    41569.000000 34290.9629  17.5%  45.5  155s
 14252 10210 40121.0217  364  617 41569.0000 34290.9629  17.5%  45.0  160s
H14630  9391                    40871.999984 34290.9629  16.1%  44.8  162s
H14802  7897                    39916.000000 34290.9629  14.1%  44.7  163s
H14869  7840                    39844.000000 34290.9629  13.9%  44.8  165s
H14870  7513                    39513.000000 34290.9629  13.2%  44.8  165s
 15669  8619 38534.0620  309  460 39513.0000 34293.1769  13.2%  44.6  170s
H16084  8564                    39307.000000 34293.1769  12.8%  44.5  172s
H16229  8531                    39275.000000 34293.1769  12.7%  44.5  172s
H16397  8082                    38929.000000 34293.1769  11.9%  44.3  174s
H16431  7628                    38626.000000 34293.1769  11.2%  44.3  174s
H16452  7103                    38126.000000 34293.1769  10.1%  44.4  174s
 16497  7360 34928.2558   86  620 38126.0000 34293.1769  10.1%  44.5  175s
H17434  7658                    37887.000000 34293.4906  9.48%  45.3  180s
H17611  7621                    37860.000000 34293.4906  9.42%  45.3  180s
H18543  8448                    37809.000000 34293.4906  9.30%  45.4  186s
H18579  7879                    37470.000000 34293.4906  8.48%  45.6  186s
H19154  8000                    37373.000000 34293.4906  8.24%  45.6  189s
H19156  7918                    37327.000000 34293.4906  8.13%  45.6  189s
 19158  8281 35437.0899  149  771 37327.0000 34293.4906  8.13%  45.6  191s
H20048  8899                    37320.000000 34293.4906  8.11%  45.3  195s
H20048  8376                    37115.000000 34293.4906  7.60%  45.3  195s
H20569  8632                    37114.000000 34293.6535  7.60%  45.5  226s
H20569  8630                    37111.000000 34293.6535  7.59%  45.5  226s
H20569  8609                    37097.000000 34293.6535  7.56%  45.5  226s
H20571  8180                    37074.000000 34293.4906  7.50%  45.5  228s
H20571  7771                    37052.000000 34293.4906  7.44%  45.5  228s
H20572  7382                    37028.000000 34293.4906  7.38%  45.5  228s
H20572  7013                    37000.000000 34293.4906  7.31%  45.5  228s
H20572  6662                    36998.000000 34293.4906  7.31%  45.5  228s
H20574  6331                    36962.000000 34293.4906  7.22%  45.5  229s
 20576  6332 35277.7769  113 1018 36962.0000 34293.4906  7.22%  45.5  230s
H20580  6018                    36946.000000 34311.3553  7.13%  45.5  231s
H20580  5717                    36903.000000 34311.3553  7.02%  45.5  231s
H20580  5431                    36901.000000 34313.6130  7.01%  45.5  233s
H20581  5159                    36730.000000 34313.6130  6.58%  45.5  234s
H20581  4901                    36720.000000 34313.6130  6.55%  45.5  234s
H20581  4656                    36663.000000 34313.6130  6.41%  45.5  234s
H20581  4423                    36526.000000 34313.6130  6.06%  45.5  234s
 20583  4425 36526.0000  423 1157 36526.0000 34313.6130  6.06%  45.5  236s
H20583  4203                    36515.000000 34324.7570  6.00%  45.5  239s
 20585  4204 34359.4141   36 1153 36515.0000 34324.7570  6.00%  45.5  240s
 20589  4207 34628.9899   83 1144 36515.0000 34339.5379  5.96%  45.5  245s
 20594  4210 34980.4771  116 1149 36515.0000 34351.3652  5.93%  45.5  250s
H20594  3999                    36501.000000 34351.3652  5.89%  45.5  252s
 20596  4000 34891.1070  159  983 36501.0000 34351.4013  5.89%  45.5  255s
 20599  4002 35255.3800  128 1071 36501.0000 34372.0543  5.83%  45.5  260s
H20599  3802                    36434.000000 34372.0543  5.66%  45.5  260s
 20601  3804 36226.3466  295 1119 36434.0000 34372.1105  5.66%  45.5  265s
H20601  3613                    36425.000000 34372.7591  5.63%  45.5  265s
H20601  3432                    36423.000000 34372.7591  5.63%  45.5  265s
H20601  3260                    36381.000000 34372.7591  5.52%  45.5  265s
H20601  3096                    36369.000000 34372.7591  5.49%  45.5  265s
H20601  2941                    36331.000000 34372.7591  5.39%  45.5  265s
H20602  2793                    36315.000000 34372.9211  5.35%  45.5  268s
H20602  2653                    36313.000000 34372.9211  5.34%  45.5  268s
H20603  2521                    36296.000000 34381.4190  5.27%  45.5  270s
H20604  2395                    36240.000000 34382.1582  5.13%  45.4  271s
H20604  2275                    36238.000000 34382.1582  5.12%  45.4  271s
H20604  2160                    36237.000000 34382.1582  5.12%  45.4  271s
H20604  2052                    36233.000000 34382.1582  5.11%  45.4  271s
H20605  1949                    36208.000000 34382.4762  5.04%  45.4  274s
H20605  1851                    36179.000000 34382.4762  4.97%  45.4  274s
 20607  1853 35843.0483  210 1060 36179.0000 34389.9670  4.94%  45.4  276s
 20610  1855 34482.2569   93 1161 36179.0000 34390.9642  4.94%  45.4  282s
 20613  1857 36076.0948  162 1117 36179.0000 34396.4217  4.93%  45.4  287s
 20615  1858 36160.4137  208 1180 36179.0000 34396.4217  4.93%  45.4  292s
 20616  1859 35822.3992  144 1206 36179.0000 34396.4217  4.93%  45.4  295s
 20617  1859 34457.4816   63 1153 36179.0000 34396.7987  4.93%  45.4  300s
H20617  1765                    36157.000000 34396.7987  4.87%  45.4  302s
 20619  1767 35251.5757  165 1222 36157.0000 34397.5339  4.87%  45.4  305s
H20619  1678                    36129.000000 34398.7221  4.79%  45.4  306s
H20619  1593                    36123.000000 34398.7221  4.77%  45.4  306s
 20622  1595 34399.8335   30 1164 36123.0000 34399.8335  4.77%  45.4  312s
H20622  1514                    36085.000000 34399.8335  4.67%  45.4  312s
 20624  1515 34444.0942   32 1211 36085.0000 34400.6716  4.67%  45.4  317s
 20626  1516 36085.0000  342 1218 36085.0000 34400.6716  4.67%  45.4  321s
H20626  1440                    36004.000000 34400.6716  4.45%  45.4  321s
 20628  1442 36004.0000  144 1200 36004.0000 34401.3091  4.45%  45.4  325s
 20631  1444 36004.0000  146 1228 36004.0000 34401.3091  4.45%  45.4  331s
 20633  1445 34712.4288   66 1213 36004.0000 34405.3649  4.44%  45.4  335s
 20635  1446 34413.7819   43 1234 36004.0000 34405.3649  4.44%  45.4  340s
 20638  1448 34648.2590   64 1190 36004.0000 34406.3377  4.44%  45.4  347s
 20640  1450 34462.2760   67 1218 36004.0000 34406.3377  4.44%  45.4  352s
 20642  1451 36004.0000  169 1177 36004.0000 34406.3377  4.44%  45.4  356s
 20644  1452 34699.2318  107 1195 36004.0000 34406.3377  4.44%  45.4  361s
 20646  1454 36004.0000  380 1163 36004.0000 34406.3377  4.44%  45.4  366s
 20648  1455 34602.1740   66 1169 36004.0000 34406.3377  4.44%  45.4  372s
H20648  1380                    35999.000000 34406.3377  4.42%  45.4  372s
H20649  1311                    35989.000000 34406.3377  4.40%  45.4  377s
 20652  1313 35229.7191  173 1177 35989.0000 34406.3377  4.40%  45.3  382s
 20654  1314 34406.3377   41 1190 35989.0000 34406.3377  4.40%  45.3  387s
 20656  1315 34604.4596   64 1173 35989.0000 34406.3377  4.40%  45.3  391s
 20658  1317 35989.0000  180 1203 35989.0000 34406.3377  4.40%  45.3  396s
 20660  1318 34756.4668   83 1214 35989.0000 34406.3377  4.40%  45.3  401s
H20660  1251                    35968.000000 34406.3377  4.34%  45.3  403s
H20660  1187                    35924.000000 34406.3377  4.22%  45.3  403s
 20662  1188 35625.4174  186 1196 35924.0000 34406.3377  4.22%  45.3  405s
 20664  1190 34651.7193   61 1211 35924.0000 34406.3377  4.22%  45.3  410s
H20665  1128                    35914.000000 34406.3377  4.20%  45.3  415s
 20668  1130 35914.0000  154 1253 35914.0000 34406.3377  4.20%  45.3  421s
 20670  1132 34864.2765   84 1223 35914.0000 34406.3377  4.20%  45.3  425s
 20672  1133 35914.0000  203 1246 35914.0000 34406.3377  4.20%  45.3  430s
 20675  1135 34406.3377   53 1259 35914.0000 34406.3377  4.20%  45.3  437s
 20676  1136 35277.7769  113 1259 35914.0000 34406.3377  4.20%  45.3  440s
 20679  1138 35914.0000  288 1259 35914.0000 34406.3377  4.20%  45.3  446s
 20681  1139 35409.1541  186 1221 35914.0000 34406.3377  4.20%  45.3  451s
 20685  1142 34406.3377   36 1243 35914.0000 34406.3377  4.20%  45.3  455s
 20690  1145 35071.2748   69 1234 35914.0000 34406.3377  4.20%  45.3  460s
 20697  1155 34409.3157   36 1176 35914.0000 34409.0315  4.19%  47.2  465s
H20773  1146                    35913.000000 34409.7442  4.19%  47.9  469s
H20775  1089                    35879.000000 34409.7442  4.10%  47.9  469s
 20777  1096 34429.7609   47  917 35879.0000 34409.7442  4.10%  48.0  470s
H20819  1065                    35868.000000 34409.7442  4.07%  48.3  471s
H20882  1055                    35867.000000 34409.7442  4.06%  48.4  473s
 20935  1092 34546.7909   64  308 35867.0000 34409.7442  4.06%  48.5  475s
 21044  1157 34670.1824   82  306 35867.0000 34409.7442  4.06%  48.9  480s
 21163  1232 35259.7239   92  966 35867.0000 34409.7442  4.06%  49.7  485s
 21307  1303 35447.3736  105  792 35867.0000 34409.7442  4.06%  50.1  490s
 21476  1408 35639.7299  122  318 35867.0000 34409.7442  4.06%  50.9  495s
 21674  1495 34422.2834   42 1003 35867.0000 34411.5257  4.06%  51.3  500s
 21897  1641 infeasible   66      35867.0000 34411.5257  4.06%  52.1  506s
 22077  1686 35038.6877   90  381 35867.0000 34411.5257  4.06%  52.8  511s
 22115  1742 infeasible   93      35867.0000 34414.1897  4.05%  53.0  516s
 22255  1839 35349.0905  102  371 35867.0000 34414.1897  4.05%  53.4  520s
 22473  1940 35571.1384  119  748 35867.0000 34414.3978  4.05%  54.1  526s
 22619  2045 35540.2831  129  714 35867.0000 34415.6056  4.05%  54.8  530s
 22823  2172 34437.6742   46 1073 35867.0000 34416.1212  4.05%  55.4  535s
 23076  2287 35520.5335   85  644 35867.0000 34416.7970  4.04%  55.7  540s
 23325  2423 35750.2976  141  380 35867.0000 34416.7970  4.04%  56.1  546s
 23580  2544 35425.9433   69 1037 35867.0000 34419.6876  4.04%  56.9  552s
 23677  2690 34489.3026   56 1008 35867.0000 34419.6876  4.04%  57.0  555s
 24082  3144 35545.7010  127  892 35867.0000 34419.6876  4.04%  57.5  562s
 24355  3338 34693.6850   48 1088 35867.0000 34420.8275  4.03%  58.0  565s
 24824  3736 34709.1226   63 1006 35867.0000 34421.9045  4.03%  59.4  573s
 25149  3977 34858.0567   81  571 35867.0000 34421.9045  4.03%  60.0  576s
 25420  4222 35546.6720  141  662 35867.0000 34422.1775  4.03%  60.6  580s
 25673  4546 34599.7991   60  783 35867.0000 34422.1775  4.03%  61.3  585s
 26354  5083 35072.8926   81  887 35867.0000 34423.3640  4.02%  62.7  593s
 26745  5398 35558.7371  107  653 35867.0000 34424.2930  4.02%  63.3  598s
 27162  5826 35796.9807  126  540 35867.0000 34424.6484  4.02%  63.8  602s
 27661  6236 35322.8753  200  344 35867.0000 34425.1493  4.02%  64.2  607s
 28111  6653 34545.9276   54 1061 35867.0000 34425.7935  4.02%  64.5  613s
 28629  7184 34908.6934   74  908 35867.0000 34426.3318  4.02%  64.9  618s
 29165  7815 35339.1679  194  182 35867.0000 34426.3318  4.02%  65.4  624s
 29841  8296 35819.2562  393   67 35867.0000 34426.7692  4.02%  65.0  630s
 30471  8642 35680.4871  118  697 35867.0000 34428.4145  4.01%  64.9  636s
 30890  9059 35434.5802  102  724 35867.0000 34428.4145  4.01%  65.3  643s
 31426  9199 35153.9628   76  871 35867.0000 34429.6175  4.01%  65.9  648s
 31607  9567 35710.1693  122  434 35867.0000 34429.6175  4.01%  66.0  653s
 32072  9880 35502.7828   75  941 35867.0000 34430.6294  4.00%  66.9  659s
 32418 10221 35427.5885   84  644 35867.0000 34431.6726  4.00%  67.3  665s
 32873 10673 35713.4134  117  693 35867.0000 34432.1400  4.00%  67.6  672s
 33445 11011 34536.5949   52 1202 35867.0000 34432.6291  4.00%  67.7  677s
 33843 11094 34697.9184   65  988 35867.0000 34433.1599  4.00%  68.3  682s
 33943 11493 34781.5154   78  831 35867.0000 34433.1599  4.00%  68.5  688s
 34388 11833 34942.9504   75  707 35867.0000 34433.1599  4.00%  69.1  694s
 34854 12282 35550.1048  162  561 35867.0000 34433.1599  4.00%  69.5  700s
 35406 12655 34713.5843   54 1121 35867.0000 34435.1624  3.99%  69.6  705s
 35906 13031 34751.4916   61  980 35867.0000 34436.1531  3.99%  70.1  711s
 36441 13401 34553.7619   50  853 35867.0000 34437.2228  3.99%  70.5  716s
 36959 13874 34872.2451   74  780 35867.0000 34437.4836  3.99%  70.9  721s
 37485 14197 35147.8289  117  549 35867.0000 34438.0985  3.98%  71.3  727s
 37889 14568 34506.9342   41 1167 35867.0000 34438.3695  3.98%  71.4  732s
 38332 14675 35264.6083  117  828 35867.0000 34438.3695  3.98%  71.8  737s
 38490 14753 35423.6629  122  782 35867.0000 34438.3695  3.98%  71.9  742s
 38614 14832 35424.0157  123  877 35867.0000 34438.9668  3.98%  72.0  746s
H38652 14214                    35802.000000 34438.9668  3.81%  72.0  746s
 38741 14571 35632.1714  136  748 35802.0000 34438.9668  3.81%  72.2  752s
 39205 14741 35276.4133   86 1001 35802.0000 34440.4124  3.80%  72.6  757s
H39313 14565                    35788.000000 34440.4124  3.77%  72.7  757s
 39416 14895     cutoff  130      35788.0000 34441.2956  3.76%  72.8  762s
 39861 15099 35443.3214   74  728 35788.0000 34442.0472  3.76%  73.4  768s
 40116 15538 34522.8304   44 1122 35788.0000 34442.4874  3.76%  73.7  774s
 40634 15804 35427.7916   83  846 35788.0000 34442.5296  3.76%  74.1  780s
 41035 16225 34593.0184   60  935 35788.0000 34443.7150  3.76%  74.2  785s
 41569 16624 35124.1093  128  717 35788.0000 34445.1862  3.75%  74.4  791s
 42049 16980 35299.0032   73  795 35788.0000 34445.1862  3.75%  74.8  796s
 42577 17311 infeasible   65      35788.0000 34446.2742  3.75%  74.8  801s
 43094 17611 34579.6614   63 1110 35788.0000 34446.5838  3.75%  74.9  805s
 43836 18144 34534.8027   48 1189 35788.0000 34447.3589  3.75%  75.3  813s
 44137 18439 34940.9173   73  866 35788.0000 34447.6786  3.75%  75.8  818s
 44514 18722 infeasible   57      35788.0000 34448.6129  3.74%  76.2  822s
 44860 19084 34590.5607   54 1173 35788.0000 34448.7435  3.74%  76.6  826s
H44959 19051                    35786.000000 34448.7435  3.74%  76.7  826s
 45256 19508 35118.0585  153  671 35786.0000 34448.7435  3.74%  77.0  831s

In [38]:
results_knn = []

for K in [10,20,50]:

    print(f"\nRunning K={K}")

    res = solve_tsp_knn(
        distance_matrix,
        500,
        K,
        timelimit=900
    )

    print(res)

    results_knn.append(res)

Running K=10
Set parameter TimeLimit to value 900
Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: AMD Ryzen 5 7520U with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Non-default parameters:
TimeLimit  900

Academic license 2835067 - for non-commercial use only - registered to mq___@isibang.ac.in
Optimize a model with 7124 rows, 6645 columns and 30664 nonzeros (Min)
Model fingerprint: 0xa8e7fbae
Model has 6146 linear objective coefficients
Variable types: 499 continuous, 6146 integer (6146 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+02]
  Objective range  [1e+00, 7e+02]
  Bounds range     [1e+00, 5e+02]
  RHS range        [1e+00, 5e+02]

Presolve time: 0.23s
Presolved: 7124 rows, 6645 columns, 61331 nonzeros
Variable types: 499 continuous, 6146 integer (6146 binary)

Root relaxation: objective 2.688721e+04, 2085 iterations, 0.07 seconds (0.03 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 26887.2120    0  886          - 26887.2120      -     -    0s
     0     0 32478.8653    0  970          - 32478.8653      -     -    1s
     0     0 32538.3386    0  969          - 32538.3386      -     -    1s
     0     0 32538.3386    0  967          - 32538.3386      -     -    1s
     0     0 32857.0766    0 1003          - 32857.0766      -     -    2s
     0     0 32902.5448    0 1021          - 32902.5448      -     -    2s
     0     0 32908.9311    0 1027          - 32908.9311      -     -    2s
     0     0 32908.9311    0 1025          - 32908.9311      -     -    2s
     0     0 33023.7214    0  996          - 33023.7214      -     -    3s
     0     0 33038.4707    0 1014          - 33038.4707      -     -    3s
     0     0 33049.0886    0 1018          - 33049.0886      -     -    3s
     0     0 33049.1209    0 1019          - 33049.1209      -     -    3s
     0     0 33165.3434    0 1014          - 33165.3434      -     -    4s
     0     0 33212.0470    0 1019          - 33212.0470      -     -    4s
     0     0 33212.3775    0 1008          - 33212.3775      -     -    4s
     0     0 33222.1103    0 1011          - 33222.1103      -     -    4s
     0     0 33247.5104    0 1018          - 33247.5104      -     -    4s
     0     0 33247.9232    0 1015          - 33247.9232      -     -    4s
     0     0 33326.5934    0 1029          - 33326.5934      -     -    5s
     0     0 33333.0934    0  989          - 33333.0934      -     -    5s
     0     0 33333.0934    0  980          - 33333.0934      -     -    5s
     0     0 33357.6320    0  978          - 33357.6320      -     -    5s
     0     0 33366.8017    0  973          - 33366.8017      -     -    5s
     0     0 33366.8017    0  973          - 33366.8017      -     -    5s
     0     0 33373.7607    0  972          - 33373.7607      -     -    5s
     0     0 33374.4501    0  972          - 33374.4501      -     -    5s
     0     0 33385.1835    0  987          - 33385.1835      -     -    6s
     0     0 33389.8710    0  997          - 33389.8710      -     -    6s
     0     0 33389.8710    0 1002          - 33389.8710      -     -    6s
     0     0 33390.4331    0 1002          - 33390.4331      -     -    6s
     0     0 33390.4331    0  976          - 33390.4331      -     -    6s
     0     2 33415.2286    0  972          - 33415.2286      -     -    7s
    81    91 33663.4860   18  832          - 33540.6344      -  90.0   10s
   221   233 34828.2156   87  770          - 33540.6344      -  76.0   15s
  1091  1012 33670.3038   13  976          - 33554.4870      -  46.8   20s
  1104  1021 34685.0585  116  780          - 33861.9414      -  46.3   25s
  1117  1029 34081.8685   39 1087          - 34081.8685      -  45.7   30s
  1125  1035 34586.6572   89 1042          - 34135.6974      -  45.4   35s
  1135  1041 34601.1000  110 1136          - 34169.9210      -  45.0   40s
  1141  1045 35117.2565  103 1090          - 34181.3625      -  44.8   45s
  1145  1048 34191.5477   23 1098          - 34191.5477      -  44.6   50s
  1158  1057 34925.2297   92 1116          - 34232.8151      -  44.1   55s
  1175  1070 34236.4241   46 1166          - 34236.4241      -  71.7   60s
  1182  1074 34262.7177   22 1100          - 34262.7177      -  71.3   65s
  1189  1079 34275.2000   12 1149          - 34275.2000      -  70.9   70s
  1193  1082 34670.2342   66 1117          - 34283.2528      -  70.6   75s
  1199  1089 34289.2062   20 1149          - 34289.2062      -  84.9   80s
  1359  1205 34525.0654   38  924          - 34289.2062      -   100   85s
  1697  1393 35672.7079   79  729          - 34289.2062      -  94.8   90s
  1920  1547 36039.9691  111  595          - 34289.2062      -  94.1   95s
  2236  1796 36760.3037  148  561          - 34289.2062      -  89.7  100s
  2800  2183 37187.1711  217  392          - 34289.2062      -  82.5  105s
  3317  2525 38130.1070  285  396          - 34289.2062      -  78.2  110s
  4158  3125 40871.6426  404  233          - 34289.2062      -  69.1  115s
  5172  3741 34556.6464   58  785          - 34289.2062      -  62.2  120s
  5259  3767 34571.1986   64  599          - 34289.2062      -  61.9  125s
  5749  4200 36416.7540  108  452          - 34290.0994      -  61.2  131s
  6133  4732 36816.1314  154  380          - 34290.1888      -  61.2  135s
  6888  5395 38968.6057  236  350          - 34290.3356      -  59.6  141s
  7450  5899 36848.4115  206  287          - 34290.3356      -  58.3  145s
  8684  7181 41593.6628  479  118          - 34290.3356      -  53.9  151s
  9992  8172 infeasible  576               - 34290.3356      -  50.2  156s
 11000  9097 40240.8639  403  159          - 34290.3356      -  47.6  160s
H12196  9558                    42143.000000 34290.9629  18.6%  45.3  163s
 12304  9538 34315.1753   34  901 42143.0000 34290.9629  18.6%  45.2  165s
H12792  9689                    42078.000000 34290.9629  18.5%  45.5  167s
H12805  9613                    42055.000000 34290.9629  18.5%  45.6  167s
 13009 10071 34373.0311   30  971 42055.0000 34290.9629  18.5%  45.4  171s
H13328  9625                    41728.000000 34290.9629  17.8%  45.4  173s
H13347  9061                    41569.000000 34290.9629  17.5%  45.5  173s
 13744  9854 37093.6631  202  738 41569.0000 34290.9629  17.5%  45.6  176s
H14630  9391                    40871.999984 34290.9629  16.1%  44.8  180s
H14802  7897                    39916.000000 34290.9629  14.1%  44.7  182s
H14869  7840                    39844.000000 34290.9629  13.9%  44.8  184s
H14870  7513                    39513.000000 34290.9629  13.2%  44.8  184s
 14873  7822 34524.2412   72  947 39513.0000 34290.9629  13.2%  44.8  186s
 15669  8619 38534.0620  309  460 39513.0000 34293.1769  13.2%  44.6  190s
H16084  8564                    39307.000000 34293.1769  12.8%  44.5  192s
H16229  8531                    39275.000000 34293.1769  12.7%  44.5  192s
H16397  8082                    38929.000000 34293.1769  11.9%  44.3  194s
H16431  7628                    38626.000000 34293.1769  11.2%  44.3  194s
H16452  7103                    38126.000000 34293.1769  10.1%  44.4  194s
 16497  7360 34928.2558   86  620 38126.0000 34293.1769  10.1%  44.5  196s
 17132  7862 34421.4715   64  946 38126.0000 34293.4906  10.1%  45.0  200s
H17434  7658                    37887.000000 34293.4906  9.48%  45.3  202s
H17611  7621                    37860.000000 34293.4906  9.42%  45.3  202s
 18162  8326 34357.1306   31  986 37860.0000 34293.4906  9.42%  45.3  206s
H18543  8448                    37809.000000 34293.4906  9.30%  45.4  208s
H18579  7879                    37470.000000 34293.4906  8.48%  45.6  208s
 18758  8257 34615.7595   95  841 37470.0000 34293.4906  8.48%  45.6  210s
H19154  8000                    37373.000000 34293.4906  8.24%  45.6  212s
H19156  7918                    37327.000000 34293.4906  8.13%  45.6  212s
 19534  8735 35711.2680  215  539 37327.0000 34293.4906  8.13%  45.6  217s
H20048  8899                    37320.000000 34293.4906  8.11%  45.3  219s
H20048  8376                    37115.000000 34293.4906  7.60%  45.3  219s
 20244  8633 36177.6291  355  386 37115.0000 34293.4906  7.60%  45.2  221s
H20569  8632                    37114.000000 34293.6535  7.60%  45.5  261s
H20569  8630                    37111.000000 34293.6535  7.59%  45.5  261s
H20569  8609                    37097.000000 34293.6535  7.56%  45.5  261s
H20571  8180                    37074.000000 34293.4906  7.50%  45.5  263s
H20571  7771                    37052.000000 34293.4906  7.44%  45.5  263s
H20572  7382                    37028.000000 34293.4906  7.38%  45.5  263s
H20572  7013                    37000.000000 34293.4906  7.31%  45.5  263s
H20572  6662                    36998.000000 34293.4906  7.31%  45.5  263s
 20574  6664 35968.1434  125 1037 36998.0000 34293.4906  7.31%  45.5  265s
H20574  6331                    36962.000000 34293.4906  7.22%  45.5  265s
H20580  6018                    36946.000000 34311.3553  7.13%  45.5  268s
H20580  5717                    36903.000000 34311.3553  7.02%  45.5  268s
H20580  5431                    36901.000000 34313.6130  7.01%  45.5  270s
H20581  5159                    36730.000000 34313.6130  6.58%  45.5  270s
H20581  4901                    36720.000000 34313.6130  6.55%  45.5  270s
H20581  4656                    36663.000000 34313.6130  6.41%  45.5  270s
H20581  4423                    36526.000000 34313.6130  6.06%  45.5  270s
H20583  4203                    36515.000000 34324.7570  6.00%  45.5  276s
 20588  4206 35538.7476  147 1139 36515.0000 34339.5379  5.96%  45.5  283s
 20592  4209 35389.9758   58 1157 36515.0000 34339.5379  5.96%  45.5  285s
H20594  3999                    36501.000000 34351.3652  5.89%  45.5  292s
 20596  4000 34891.1070  159  983 36501.0000 34351.4013  5.89%  45.5  296s
 20599  4002 35255.3800  128 1071 36501.0000 34372.0543  5.83%  45.5  302s
H20599  3802                    36434.000000 34372.0543  5.66%  45.5  303s
 20600  3803 34672.3551   71 1076 36434.0000 34372.0543  5.66%  45.5  305s
H20601  3613                    36425.000000 34372.7591  5.63%  45.5  309s
H20601  3432                    36423.000000 34372.7591  5.63%  45.5  309s
H20601  3260                    36381.000000 34372.7591  5.52%  45.5  309s
H20601  3096                    36369.000000 34372.7591  5.49%  45.5  309s
H20601  2941                    36331.000000 34372.7591  5.39%  45.5  309s
H20602  2793                    36315.000000 34372.9211  5.35%  45.5  312s
H20602  2653                    36313.000000 34372.9211  5.34%  45.5  312s
H20603  2521                    36296.000000 34381.4190  5.27%  45.5  315s
H20604  2395                    36240.000000 34382.1582  5.13%  45.4  316s
H20604  2275                    36238.000000 34382.1582  5.12%  45.4  316s
H20604  2160                    36237.000000 34382.1582  5.12%  45.4  316s
H20604  2052                    36233.000000 34382.1582  5.11%  45.4  316s
H20605  1949                    36208.000000 34382.4762  5.04%  45.4  319s
H20605  1851                    36179.000000 34382.4762  4.97%  45.4  319s
 20607  1853 35843.0483  210 1060 36179.0000 34389.9670  4.94%  45.4  322s
 20609  1854 34389.9670   43 1150 36179.0000 34389.9670  4.94%  45.4  326s
 20610  1855 34482.2569   93 1161 36179.0000 34390.9642  4.94%  45.4  330s
 20613  1857 36076.0948  162 1117 36179.0000 34396.4217  4.93%  45.4  337s
 20614  1857 34563.9110   60 1120 36179.0000 34396.4217  4.93%  45.4  340s
 20616  1859 35822.3992  144 1206 36179.0000 34396.4217  4.93%  45.4  347s
 20617  1859 34457.4816   63 1153 36179.0000 34396.7987  4.93%  45.4  352s
H20617  1765                    36157.000000 34396.7987  4.87%  45.4  355s
H20619  1678                    36129.000000 34398.7221  4.79%  45.4  359s
H20619  1593                    36123.000000 34398.7221  4.77%  45.4  359s
 20621  1594 36123.0000  431 1194 36123.0000 34398.9474  4.77%  45.4  362s
 20622  1595 34399.8335   30 1164 36123.0000 34399.8335  4.77%  45.4  365s
H20622  1514                    36085.000000 34399.8335  4.67%  45.4  365s
 20624  1515 34444.0942   32 1211 36085.0000 34400.6716  4.67%  45.4  371s
 20626  1516 36085.0000  342 1218 36085.0000 34400.6716  4.67%  45.4  376s
H20626  1440                    36004.000000 34400.6716  4.45%  45.4  377s
 20628  1442 36004.0000  144 1200 36004.0000 34401.3091  4.45%  45.4  382s
 20630  1443 34602.6607   59 1218 36004.0000 34401.3091  4.45%  45.4  387s
 20632  1444 36004.0000  192 1246 36004.0000 34405.3649  4.44%  45.4  392s
 20633  1445 34712.4288   66 1213 36004.0000 34405.3649  4.44%  45.4  395s
 20635  1446 34413.7819   43 1234 36004.0000 34405.3649  4.44%  45.4  401s
 20637  1448 35081.2748   73 1215 36004.0000 34405.3649  4.44%  45.4  406s
 20639  1449 35355.1504  132 1216 36004.0000 34406.3377  4.44%  45.4  411s
 20640  1450 34462.2760   67 1218 36004.0000 34406.3377  4.44%  45.4  415s
 20642  1451 36004.0000  169 1177 36004.0000 34406.3377  4.44%  45.4  420s
 20644  1452 34699.2318  107 1195 36004.0000 34406.3377  4.44%  45.4  426s
 20646  1454 36004.0000  380 1163 36004.0000 34406.3377  4.44%  45.4  432s
 20648  1455 34602.1740   66 1169 36004.0000 34406.3377  4.44%  45.4  437s
H20648  1380                    35999.000000 34406.3377  4.42%  45.4  438s
 20649  1381 35999.0000  215 1216 35999.0000 34406.3377  4.42%  45.4  440s
H20649  1311                    35989.000000 34406.3377  4.40%  45.4  444s
 20651  1312 35989.0000  138 1193 35989.0000 34406.3377  4.40%  45.3  446s
 20652  1313 35229.7191  173 1177 35989.0000 34406.3377  4.40%  45.3  450s
 20654  1314 34406.3377   41 1190 35989.0000 34406.3377  4.40%  45.3  455s
 20656  1315 34604.4596   64 1173 35989.0000 34406.3377  4.40%  45.3  461s
 20658  1317 35989.0000  180 1203 35989.0000 34406.3377  4.40%  45.3  466s
 20660  1318 34756.4668   83 1214 35989.0000 34406.3377  4.40%  45.3  472s
H20660  1251                    35968.000000 34406.3377  4.34%  45.3  475s
H20660  1187                    35924.000000 34406.3377  4.22%  45.3  475s
 20663  1189 35231.1656  131 1224 35924.0000 34406.3377  4.22%  45.3  480s
 20665  1190 35050.0639  170 1245 35924.0000 34406.3377  4.22%  45.3  486s
H20665  1128                    35914.000000 34406.3377  4.20%  45.3  490s
 20668  1130 35914.0000  154 1253 35914.0000 34406.3377  4.20%  45.3  496s
 20670  1132 34864.2765   84 1223 35914.0000 34406.3377  4.20%  45.3  501s
 20672  1133 35914.0000  203 1246 35914.0000 34406.3377  4.20%  45.3  507s
 20674  1134 35914.0000  125 1259 35914.0000 34406.3377  4.20%  45.3  512s
 20675  1135 34406.3377   53 1259 35914.0000 34406.3377  4.20%  45.3  515s
 20677  1136 35492.0922  108 1259 35914.0000 34406.3377  4.20%  45.3  520s
 20679  1138 35914.0000  288 1259 35914.0000 34406.3377  4.20%  45.3  526s
 20681  1139 35409.1541  186 1221 35914.0000 34406.3377  4.20%  45.3  532s
 20684  1141 35839.4229  175 1229 35914.0000 34406.3377  4.20%  45.3  536s
 20688  1144 35538.7476  147 1231 35914.0000 34406.3377  4.20%  45.3  540s
 20692  1146 35389.9758   58 1244 35914.0000 34406.3377  4.20%  45.3  545s
 20713  1166 34420.0823   39 1143 35914.0000 34409.7442  4.19%  47.4  550s
H20773  1146                    35913.000000 34409.7442  4.19%  47.9  554s
H20775  1089                    35879.000000 34409.7442  4.10%  47.9  554s
 20777  1096 34429.7609   47  917 35879.0000 34409.7442  4.10%  48.0  555s
H20819  1065                    35868.000000 34409.7442  4.07%  48.3  556s
H20882  1055                    35867.000000 34409.7442  4.06%  48.4  559s
 20913  1096 34566.5715   62  318 35867.0000 34409.7442  4.06%  48.5  560s
 21007  1124 34656.0047   72  305 35867.0000 34409.7442  4.06%  48.7  565s
 21073  1177 35041.5800   85  300 35867.0000 34409.7442  4.06%  49.0  570s
 21226  1244 35260.4598   96  266 35867.0000 34409.7442  4.06%  49.9  576s
 21307  1303 35447.3736  105  792 35867.0000 34409.7442  4.06%  50.1  580s
 21439  1386 35629.6380  119  442 35867.0000 34409.7442  4.06%  50.7  585s
 21611  1473 35714.9370  135  264 35867.0000 34411.5257  4.06%  51.2  591s
 21766  1561 34471.1573   52  859 35867.0000 34411.5257  4.06%  51.8  595s
 21958  1676 35200.8653   77  801 35867.0000 34411.5257  4.06%  52.2  601s
 22077  1686 35038.6877   90  381 35867.0000 34411.5257  4.06%  52.8  605s
 22115  1742 infeasible   93      35867.0000 34414.1897  4.05%  53.0  611s
 22255  1839 35349.0905  102  371 35867.0000 34414.1897  4.05%  53.4  616s
 22404  1911 35612.9175  116  762 35867.0000 34414.3978  4.05%  53.8  620s
 22541  1986 35518.0339  124  818 35867.0000 34415.6056  4.05%  54.5  626s
 22721  2092 35524.9561  138  365 35867.0000 34415.6056  4.05%  55.1  631s
 22946  2230 34476.7216   66  617 35867.0000 34416.1212  4.05%  55.5  638s
 23076  2287 35520.5335   85  644 35867.0000 34416.7970  4.04%  55.7  641s
 23325  2423 35750.2976  141  380 35867.0000 34416.7970  4.04%  56.1  648s
 23451  2472 34657.3499   43 1136 35867.0000 34419.6876  4.04%  56.5  651s
 23580  2544 35425.9433   69 1037 35867.0000 34419.6876  4.04%  56.9  655s
 23836  2884 35200.4441   90  538 35867.0000 34419.6876  4.04%  57.2  663s
 24082  3144 35545.7010  127  892 35867.0000 34419.6876  4.04%  57.5  667s
 24355  3338 34693.6850   48 1088 35867.0000 34420.8275  4.03%  58.0  672s
 24618  3522 34561.9283   49 1184 35867.0000 34421.8594  4.03%  58.6  676s
 24824  3736 34709.1226   63 1006 35867.0000 34421.9045  4.03%  59.4  681s
 25149  3977 34858.0567   81  571 35867.0000 34421.9045  4.03%  60.0  685s
 25420  4222 35546.6720  141  662 35867.0000 34422.1775  4.03%  60.6  690s
 25673  4546 34599.7991   60  783 35867.0000 34422.1775  4.03%  61.3  696s
 26083  4761 34757.3698   59 1031 35867.0000 34423.3640  4.02%  61.7  701s
 26354  5083 35072.8926   81  887 35867.0000 34423.3640  4.02%  62.7  706s
 26745  5398 35558.7371  107  653 35867.0000 34424.2930  4.02%  63.3  712s
 27162  5826 35796.9807  126  540 35867.0000 34424.6484  4.02%  63.8  719s
 27661  6236 35322.8753  200  344 35867.0000 34425.1493  4.02%  64.2  725s
 28111  6653 34545.9276   54 1061 35867.0000 34425.7935  4.02%  64.5  731s
 28629  7184 34908.6934   74  908 35867.0000 34426.3318  4.02%  64.9  738s
 29165  7815 35339.1679  194  182 35867.0000 34426.3318  4.02%  65.4  745s
 29841  8296 35819.2562  393   67 35867.0000 34426.7692  4.02%  65.0  753s
 30471  8642 35680.4871  118  697 35867.0000 34428.4145  4.01%  64.9  760s
 30890  9059 35434.5802  102  724 35867.0000 34428.4145  4.01%  65.3  769s
 31426  9199 35153.9628   76  871 35867.0000 34429.6175  4.01%  65.9  775s
 31607  9567 35710.1693  122  434 35867.0000 34429.6175  4.01%  66.0  782s
 32072  9880 35502.7828   75  941 35867.0000 34430.6294  4.00%  66.9  790s
 32418 10221 35427.5885   84  644 35867.0000 34431.6726  4.00%  67.3  797s
 32873 10673 35713.4134  117  693 35867.0000 34432.1400  4.00%  67.6  805s
 33445 11011 34536.5949   52 1202 35867.0000 34432.6291  4.00%  67.7  812s
 33843 11094 34697.9184   65  988 35867.0000 34433.1599  4.00%  68.3  818s
 33943 11493 34781.5154   78  831 35867.0000 34433.1599  4.00%  68.5  825s
 34388 11833 34942.9504   75  707 35867.0000 34433.1599  4.00%  69.1  833s
 34854 12282 35550.1048  162  561 35867.0000 34433.1599  4.00%  69.5  842s
 35406 12655 34713.5843   54 1121 35867.0000 34435.1624  3.99%  69.6  849s
 35906 13031 34751.4916   61  980 35867.0000 34436.1531  3.99%  70.1  856s
 36441 13401 34553.7619   50  853 35867.0000 34437.2228  3.99%  70.5  863s
 36959 13874 34872.2451   74  780 35867.0000 34437.4836  3.99%  70.9  870s
 37485 14197 35147.8289  117  549 35867.0000 34438.0985  3.98%  71.3  875s
 37889 14568 34506.9342   41 1167 35867.0000 34438.3695  3.98%  71.4  881s
 38332 14675 35264.6083  117  828 35867.0000 34438.3695  3.98%  71.8  886s
 38490 14753 35423.6629  122  782 35867.0000 34438.3695  3.98%  71.9  891s

## Task 3: K-Nearest Neighbour Sparsification

Instead of considering every possible edge, the optimization model was restricted to the K nearest neighbours of each city.

This experiment evaluates the trade-off between:

- Computational complexity
- Memory consumption
- Solution quality

Different values of K were tested to study how graph sparsification affects optimization performance.

In [39]:
task3_df = pd.DataFrame(
    results_knn
)

task3_df

     N   K   Arcs  Status  Runtime_sec   ObjVal  ObjBound        Gap
0  500  10   6146       9      900.105  35802.0   34440.0   3.804257
1  500  20  12316       9      900.449  39125.0   34380.0  12.127796
2  500  50  30862       9      900.159  38877.0   33798.0  13.064280

### Observations

- Smaller values of K significantly reduced the number of decision variables.
- Solver runtime decreased due to the reduced search space.
- Increasing K generally improved solution quality but increased computational effort.
- KNN sparsification provides an effective balance between optimization accuracy and computational efficiency for large-scale TSP instances.

In [40]:
task3_df.to_csv(
    "Task3_KNN.csv",
    index=False
)

# Conclusions

This project compared heuristic and exact optimization techniques for solving the Traveling Salesman Problem on real-world road network data.

### Key Findings

- Google OR-Tools generated high-quality feasible tours within a short computation time, making it an excellent heuristic for large-scale instances.
- The MTZ-based MILP formulation successfully obtained optimal or near-optimal solutions for smaller problem instances but became computationally expensive as the number of cities increased.
- Using the OR-Tools solution as a warm start substantially improved the quality of the incumbent solution and reduced the optimality gap under identical time limits.
- K-Nearest Neighbour sparsification reduced the size of the optimization model and improved computational efficiency while maintaining competitive solution quality.

### Limitations

- The MTZ formulation scales poorly for very large instances because of the large number of binary variables and subtour elimination constraints.
- Large instances may exceed available memory before optimality can be proven.

### Future Work

Potential improvements include:

- Stronger subtour elimination methods (Lazy Constraints / Branch-and-Cut)
- Christofides or Lin-Kernighan heuristics
- Parallel optimization
- Metaheuristics such as Genetic Algorithms, Simulated Annealing and Ant Colony Optimization
- Vehicle Routing Problem (VRP) extensions with capacity and time-window constraints